#pragma once

#include <cstdint>
#include <sstream>

#include "fsm_model.hpp"

namespace fsm::codegen {

enum class CppStandard : std::uint8_t { Cpp17, Cpp20 };

struct GeneratorOptions {
    CppStandard cpp_standard = CppStandard::Cpp17;
    bool standalone = true;     // Generate completely self-contained file (no
                                // external includes needed)
    bool include_stubs = true;  // Generate default functor definitions for guards and actions
    bool thread_safe = true;    // Generate thread_safe_fsm wrapper
};

class CppGenerator {
  public:
    static std::string generate_header(const FsmModel& model, const GeneratorOptions& options = {}) {
        std::ostringstream out;

        std::string std_str = (options.cpp_standard == CppStandard::Cpp20) ? "C++20" : "C++17";

        out << "// "
               "==================================================================="
               "=========\n";
        out << "// Auto-generated by fsm-gen (" << std_str << " State Machine Compiler)\n";
        out << "// Target: Compile-time Zero-Overhead FSM (" << std_str << ")\n";
        if (options.standalone) {
            out << "// Mode: Standalone Self-Contained Header (Zero External "
                   "Dependencies)\n";
        }
        out << "// "
               "==================================================================="
               "=========\n\n";

        out << "#pragma once\n\n";

        if (options.standalone) {
            if (options.cpp_standard == CppStandard::Cpp20) {
                generate_cpp20_standalone_runtime(out, options);
            } else {
                generate_cpp17_standalone_runtime(out, options);
            }
        } else {
            out << "#include \"fsm/fsm.hpp\"\n";
            if (options.thread_safe) {
                out << "#include \"fsm/thread_safe_fsm.hpp\"\n";
            }
            out << "#include <string_view>\n";
            out << "#include <iostream>\n\n";
        }

        if (!model.ns.empty()) {
            out << "namespace " << model.ns << " {\n\n";
        }

        // 1. Forward declaration of Context if custom
        if (!model.context_type.empty() && model.context_type != "no_context" &&
            model.context_type != "fsm::no_context" && model.context_type != "void") {
            out << "// Forward declaration of Context\n";
            out << "struct " << model.context_type << ";\n\n";
        }

        // 2. Event Definitions
        out << "// "
               "==================================================================="
               "=========\n";
        out << "// Events\n";
        out << "// "
               "==================================================================="
               "=========\n\n";

        for (const auto& event_item : model.events) {
            out << "struct " << event_item.name << " {\n";
            if (!event_item.description.empty()) {
                out << "    // Description: " << event_item.description << "\n";
            }
            out << "};\n\n";
        }

        // 3. State Definitions
        out << "// "
               "==================================================================="
               "=========\n";
        out << "// States\n";
        out << "// "
               "==================================================================="
               "=========\n\n";

        for (const auto& state_item : model.states) {
            out << "struct " << state_item.name << " {\n";
            out << "    static constexpr std::string_view name = \"" << state_item.name << "\";\n";
            if (!state_item.parent_state.empty()) {
                out << "    static constexpr std::string_view parent = \"" << state_item.parent_state << "\";\n";
            }
            if (!state_item.deferred_events.empty()) {
                out << "    using deferred_events = ::fsm::type_list<";
                for (std::size_t i = 0; i < state_item.deferred_events.size(); ++i) {
                    if (i > 0) {
                        out << ", ";
                    }
                    out << state_item.deferred_events[i];
                }
                out << ">;\n";
            }
            if (!state_item.description.empty()) {
                out << "    // Description: " << state_item.description << "\n";
            }
            out << "};\n\n";
        }

        // 4. Guards Definitions (if include_stubs)
        // 4. Guards Definitions (if include_stubs)
        if (!model.guards.empty()) {
            if (options.include_stubs) {
                out << "// "
                       "================================================================="
                       "===========\n";
                out << "// Guards\n";
                out << "// "
                       "================================================================="
                       "===========\n\n";

                for (const auto& guard_item : model.guards) {
                    out << "struct " << guard_item.name << " {\n";
                    if (options.cpp_standard == CppStandard::Cpp20) {
                        out << "    [[nodiscard]] constexpr bool operator()(const auto& "
                               "/*evt*/, const auto& /*state*/, const auto& /*ctx*/) const "
                               "noexcept {\n";
                        out << "        // TODO: Implement guard logic for " << guard_item.name << "\n";
                        out << "        return true;\n";
                        out << "    }\n";
                    } else {
                        out << "    template <typename Event, typename State, typename "
                               "Context>\n";
                        out << "    bool operator()(const Event& /*evt*/, const State& "
                               "/*state*/, const Context& /*ctx*/) const {\n";
                        out << "        // TODO: Implement guard logic for " << guard_item.name << "\n";
                        out << "        return true;\n";
                        out << "    }\n";
                    }
                    out << "};\n\n";
                }
            } else {
                out << "// Forward declaration of custom Guards\n";
                for (const auto& guard_item : model.guards) {
                    out << "struct " << guard_item.name << ";\n";
                }
                out << "\n";
            }
        }

        // 5. Actions Definitions (if include_stubs)
        if (!model.actions.empty()) {
            if (options.include_stubs) {
                out << "// "
                       "================================================================="
                       "===========\n";
                out << "// Actions\n";
                out << "// "
                       "================================================================="
                       "===========\n\n";

                for (const auto& action_item : model.actions) {
                    out << "struct " << action_item.name << " {\n";
                    if (options.cpp_standard == CppStandard::Cpp20) {
                        out << "    constexpr void operator()(const auto& /*evt*/, auto& "
                               "/*src*/, auto& /*dst*/, auto& /*ctx*/) const {\n";
                        out << "        // TODO: Implement action logic for " << action_item.name << "\n";
                        out << "    }\n";
                    } else {
                        out << "    template <typename Event, typename SrcState, typename "
                               "DstState, typename Context>\n";
                        out << "    void operator()(const Event& /*evt*/, SrcState& /*src*/, "
                               "DstState& /*dst*/, Context& /*ctx*/) const {\n";
                        out << "        // TODO: Implement action logic for " << action_item.name << "\n";
                        out << "    }\n";
                    }
                    out << "};\n\n";
                }
            } else {
                out << "// Forward declaration of custom Actions\n";
                for (const auto& action_item : model.actions) {
                    out << "struct " << action_item.name << ";\n";
                }
                out << "\n";
            }
        }

        // 6. Transition Table (using Fluent DSL fsm::row)
        out << "// "
               "==================================================================="
               "=========\n";
        out << "// Transition Table (Compile-Time Fluent DSL)\n";
        out << "// "
               "==================================================================="
               "=========\n\n";

        std::string table_type_name = model.name + "Table";
        out << "using " << table_type_name << " = fsm::transition_table<\n";

        auto find_state_by_name = [&](const std::string& name) -> const StateModel* {
            for (const auto& s : model.states) {
                if (s.name == name) return &s;
            }
            return nullptr;
        };

        auto find_leaf_substates = [&](auto& self, const std::string& parent_name) -> std::vector<std::string> {
            std::vector<std::string> leaves;
            for (const auto& s : model.states) {
                if (s.parent_state == parent_name) {
                    if (s.is_composite) {
                        auto sub_leaves = self(self, s.name);
                        leaves.insert(leaves.end(), sub_leaves.begin(), sub_leaves.end());
                    } else {
                        leaves.push_back(s.name);
                    }
                }
            }
            return leaves;
        };

        auto find_initial_leaf_substate = [&](auto& self, const std::string& state_name) -> std::string {
            const auto* s = find_state_by_name(state_name);
            if (s != nullptr && s->is_composite && !s->initial_sub_state.empty()) {
                return self(self, s->initial_sub_state);
            }
            return state_name;
        };

        struct EffectiveTransition {
            std::string source;
            std::string target;
            std::string event;
            std::optional<std::string> guard;
            std::optional<std::string> action;
            bool is_internal = false;
        };

        struct BaseTransition {
            std::string source;
            std::string target;
            std::string event;
            std::optional<std::string> guard;
            std::optional<std::string> action;
            bool is_internal = false;
            bool target_is_history = false;
        };

        std::vector<BaseTransition> base_transitions;
        for (const auto& transition_item : model.transitions) {
            if (model.is_choice_node(transition_item.source)) {
                continue;
            }
            if (model.is_choice_node(transition_item.target)) {
                for (const auto& branch : model.transitions) {
                    if (branch.source == transition_item.target) {
                        BaseTransition bt;
                        bt.source = transition_item.source;
                        bt.target = branch.target;
                        bt.event = transition_item.event;
                        if (transition_item.guard && branch.guard) {
                            bt.guard = "fsm::and_<" + *transition_item.guard + ", " + *branch.guard + ">";
                        } else if (branch.guard) {
                            bt.guard = branch.guard;
                        } else {
                            bt.guard = transition_item.guard;
                        }
                        bt.action = branch.action ? branch.action : transition_item.action;
                        bt.is_internal = false;
                        bt.target_is_history = branch.target_is_history;
                        base_transitions.push_back(std::move(bt));
                    }
                }
            } else {
                BaseTransition bt;
                bt.source = transition_item.source;
                bt.target = transition_item.target;
                bt.event = transition_item.event;
                bt.guard = transition_item.guard;
                bt.action = transition_item.action;
                bt.is_internal = (transition_item.kind == TransitionKind::Internal);
                bt.target_is_history = transition_item.target_is_history;
                base_transitions.push_back(std::move(bt));
            }
        }

        std::vector<EffectiveTransition> effective_transitions;
        for (const auto& bt : base_transitions) {
            const auto* src_st = find_state_by_name(bt.source);
            std::vector<std::string> actual_sources;
            if (src_st != nullptr && src_st->is_composite) {
                auto leaves = find_leaf_substates(find_leaf_substates, bt.source);
                for (const auto& leaf : leaves) {
                    bool leaf_has_own = false;
                    for (const auto& other : base_transitions) {
                        if (other.source == leaf && other.event == bt.event) {
                            leaf_has_own = true;
                            break;
                        }
                    }
                    if (!leaf_has_own) {
                        actual_sources.push_back(leaf);
                    }
                }
                if (actual_sources.empty()) {
                    actual_sources.push_back(bt.source);
                }
            } else {
                actual_sources.push_back(bt.source);
            }

            for (const auto& src : actual_sources) {
                if (bt.target_is_history) {
                    auto sub_leaves = find_leaf_substates(find_leaf_substates, bt.target);
                    std::string init_leaf = find_initial_leaf_substate(find_initial_leaf_substate, bt.target);

                    for (const auto& sub : sub_leaves) {
                        EffectiveTransition eff;
                        eff.source = src;
                        eff.target = sub;
                        eff.event = bt.event;
                        std::string hist_guard = "fsm::history_is<" + bt.target + ", " + sub + ">";
                        if (bt.guard && !bt.guard->empty()) {
                            eff.guard = "fsm::and_<" + *bt.guard + ", " + hist_guard + ">";
                        } else {
                            eff.guard = hist_guard;
                        }
                        eff.action = bt.action;
                        eff.is_internal = false;
                        effective_transitions.push_back(std::move(eff));
                    }

                    EffectiveTransition fallback;
                    fallback.source = src;
                    fallback.target = init_leaf;
                    fallback.event = bt.event;
                    fallback.guard = bt.guard;
                    fallback.action = bt.action;
                    fallback.is_internal = false;
                    effective_transitions.push_back(std::move(fallback));
                } else {
                    std::string actual_target = find_initial_leaf_substate(find_initial_leaf_substate, bt.target);
                    EffectiveTransition eff;
                    eff.source = src;
                    eff.target = actual_target;
                    eff.event = bt.event;
                    eff.guard = bt.guard;
                    eff.action = bt.action;
                    eff.is_internal = bt.is_internal;
                    effective_transitions.push_back(std::move(eff));
                }
            }
        }

        for (size_t i = 0; i < effective_transitions.size(); ++i) {
            const auto& transition_item = effective_transitions[i];
            if (transition_item.is_internal) {
                out << "    fsm::internal_row<" << transition_item.source << ", " << transition_item.event << ">";
            } else {
                out << "    fsm::row<" << transition_item.source << ", " << transition_item.event << ", "
                    << transition_item.target << ">";
            }

            if (transition_item.guard && !transition_item.guard->empty()) {
                out << "::when<" << *transition_item.guard << ">";
            }
            if (transition_item.action && !transition_item.action->empty()) {
                out << "::then<" << *transition_item.action << ">";
            }

            if (i + 1 < effective_transitions.size()) {
                out << ",\n";
            } else {
                out << "\n";
            }
        }
        out << ">;\n\n";

        // 7. FSM Typedefs
        out << "// "
               "==================================================================="
               "=========\n";
        out << "// State Machine Type Aliases\n";
        out << "// "
               "==================================================================="
               "=========\n\n";

        std::string ctx_type =
            (model.context_type.empty() || model.context_type == "no_context" || model.context_type == "void")
                ? "fsm::no_context"
                : model.context_type;

        std::string raw_init_state = model.initial_state;
        if (raw_init_state.empty()) {
            if (!model.states.empty()) {
                raw_init_state = model.states[0].name;
            } else {
                raw_init_state = "Idle";
            }
        }
        std::string init_state = find_initial_leaf_substate(find_initial_leaf_substate, raw_init_state);

        out << "using " << model.name << " = fsm::fsm<" << table_type_name << ", " << ctx_type << ", " << init_state
            << ">;\n";

        if (options.thread_safe) {
            out << "using ThreadSafe" << model.name << " = fsm::thread_safe_fsm<" << table_type_name << ", " << ctx_type
                << ", " << init_state << ">;\n";
        }

        if (!model.ns.empty()) {
            out << "\n} // namespace " << model.ns << "\n";
        }

        return out.str();
    }

  private:
    static void generate_cpp20_standalone_runtime(std::ostream& out, const GeneratorOptions& opts) {
        out << "#include <variant>\n";
        out << "#include <tuple>\n";
        out << "#include <string_view>\n";
        out << "#include <concepts>\n";
        out << "#include <type_traits>\n";
        out << "#include <utility>\n";
        out << "#include <functional>\n";
        out << "#include <vector>\n";
        if (opts.thread_safe) {
            out << "#include <queue>\n";
            out << "#include <mutex>\n";
            out << "#include <condition_variable>\n";
            out << "#include <thread>\n";
            out << "#include <stop_token>\n";
            out << "#include <atomic>\n";
        }
        out << "\n";

        out << "namespace fsm {\n\n";
        out << "struct no_context {};\n\n";

        // Transition info
        out << "struct transition_info {\n";
        out << "    std::string_view source;\n";
        out << "    std::string_view target;\n";
        out << "    std::string_view event;\n";
        out << "    bool is_internal = false;\n";
        out << "};\n\n";

        // Type list helpers
        out << "template <typename... Ts> struct type_list {};\n\n";

        out << "namespace detail {\n";
        out << "template <typename T, typename List> struct contains;\n";
        out << "template <typename T> struct contains<T, type_list<>> : "
               "std::false_type {};\n";
        out << "template <typename T, typename... Rest> struct contains<T, "
               "type_list<T, Rest...>> : std::true_type {};\n";
        out << "template <typename T, typename Head, typename... Rest> struct "
               "contains<T, type_list<Head, Rest...>> : contains<T, "
               "type_list<Rest...>> {};\n\n";

        out << "template <typename InList, typename OutList = type_list<>> struct "
               "unique;\n";
        out << "template <typename OutList> struct unique<type_list<>, OutList> { "
               "using type = OutList; };\n";
        out << "template <typename Head, typename... Tail, typename... Out> struct "
               "unique<type_list<Head, Tail...>, type_list<Out...>> {\n";
        out << "    using type = std::conditional_t<contains<Head, "
               "type_list<Out...>>::value,\n";
        out << "        typename unique<type_list<Tail...>, "
               "type_list<Out...>>::type,\n";
        out << "        typename unique<type_list<Tail...>, type_list<Out..., "
               "Head>>::type>;\n";
        out << "};\n";
        out << "template <typename List> using unique_t = typename "
               "unique<List>::type;\n\n";

        out << "template <typename List> struct to_variant;\n";
        out << "template <typename... Ts> struct to_variant<type_list<Ts...>> { "
               "using type = std::variant<Ts...>; };\n";
        out << "template <typename List> using to_variant_t = typename "
               "to_variant<List>::type;\n";
        out << "} // namespace detail\n\n";

        out << "namespace detail {\n";
        out << "template <typename State, typename = void> struct has_deferred_events : std::false_type {};\n";
        out << "template <typename State> struct has_deferred_events<State, std::void_t<typename State::deferred_events>> : std::true_type {};\n";
        out << "} // namespace detail\n\n";

        out << "template <typename State, typename Event>\n";
        out << "inline constexpr bool is_deferred_event_v = []() constexpr {\n";
        out << "    if constexpr (detail::has_deferred_events<State>::value) {\n";
        out << "        return detail::contains<std::decay_t<Event>, typename State::deferred_events>::value;\n";
        out << "    } else {\n";
        out << "        return false;\n";
        out << "    }\n";
        out << "}();\n\n";

        out << "struct no_guard {\n";
        out << "    [[nodiscard]] constexpr bool operator()(const auto&...) const "
               "noexcept { return true; }\n";
        out << "};\n\n";

        out << "struct no_action {\n";
        out << "    constexpr void operator()(auto&...) const noexcept {}\n";
        out << "};\n\n";

        // Combinators
        out << "template <typename Guard, typename Event, typename State, typename Context>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx);\n\n";

        out << "template <typename Guard, typename Event, typename State, typename Context, typename Fsm>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx, const Fsm& fsm);\n\n";

        out << "template <typename Guard>\n";
        out << "struct not_ {\n";
        out << "    Guard guard_fn{};\n";
        out << "    constexpr not_() = default;\n";
        out << "    constexpr explicit not_(Guard g) : guard_fn(std::move(g)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        return !invoke_guard(guard_fn, evt, s, &ctx, fsm);\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        return !invoke_guard(guard_fn, evt, s, &ctx);\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename Guard1, typename Guard2, typename... Rest>\n";
        out << "struct and_ {\n";
        out << "    Guard1 g1{};\n";
        out << "    Guard2 g2{};\n";
        out << "    constexpr and_() = default;\n";
        out << "    constexpr and_(Guard1 first, Guard2 second) : g1(std::move(first)), g2(std::move(second)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        if (!invoke_guard(g1, evt, s, &ctx, fsm)) return false;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx, fsm);\n";
        out << "        } else {\n";
        out << "            return and_<Guard2, Rest...>{}(evt, s, ctx, fsm);\n";
        out << "        }\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        if (!invoke_guard(g1, evt, s, &ctx)) return false;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx);\n";
        out << "        } else {\n";
        out << "            return and_<Guard2, Rest...>{}(evt, s, ctx);\n";
        out << "        }\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename Guard1, typename Guard2, typename... Rest>\n";
        out << "struct or_ {\n";
        out << "    Guard1 g1{};\n";
        out << "    Guard2 g2{};\n";
        out << "    constexpr or_() = default;\n";
        out << "    constexpr or_(Guard1 first, Guard2 second) : g1(std::move(first)), g2(std::move(second)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        if (invoke_guard(g1, evt, s, &ctx, fsm)) return true;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx, fsm);\n";
        out << "        } else {\n";
        out << "            return or_<Guard2, Rest...>{}(evt, s, ctx, fsm);\n";
        out << "        }\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        if (invoke_guard(g1, evt, s, &ctx)) return true;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx);\n";
        out << "        } else {\n";
        out << "            return or_<Guard2, Rest...>{}(evt, s, ctx);\n";
        out << "        }\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename ParentState, typename SubState>\n";
        out << "struct history_is {\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event&, const State&, Context&, const Fsm& fsm) const {\n";
        out << "        return fsm.get_history(ParentState::name) == SubState::name;\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event&, const State&, Context&) const {\n";
        out << "        return false;\n";
        out << "    }\n";
        out << "};\n\n";

        // Row DSL
        out << "template <typename Src, typename Evt, typename Dst, typename "
               "GuardType = no_guard, typename ActionType = no_action>\n";
        out << "struct row {\n";
        out << "    using source_state = Src;\n";
        out << "    using event_type = Evt;\n";
        out << "    using target_state = Dst;\n";
        out << "    using guard_type = GuardType;\n";
        out << "    using action_type = ActionType;\n";
        out << "    static constexpr bool is_internal = false;\n\n";
        out << "    template <typename G> using when = row<Src, Evt, Dst, G, "
               "ActionType>;\n";
        out << "    template <typename A> using then = row<Src, Evt, Dst, "
               "GuardType, A>;\n";
        out << "};\n\n";

        out << "template <typename State, typename Evt, typename GuardType = no_guard, typename ActionType = "
               "no_action>\n";
        out << "struct internal_row {\n";
        out << "    using source_state = State;\n";
        out << "    using event_type = Evt;\n";
        out << "    using target_state = State;\n";
        out << "    using guard_type = GuardType;\n";
        out << "    using action_type = ActionType;\n";
        out << "    static constexpr bool is_internal = true;\n\n";
        out << "    template <typename G> using when = internal_row<State, Evt, G, ActionType>;\n";
        out << "    template <typename A> using then = internal_row<State, Evt, GuardType, A>;\n";
        out << "};\n\n";

        // Table
        out << "template <typename... Rows>\n";
        out << "struct transition_table {\n";
        out << "    using rows = std::tuple<Rows...>;\n";
        out << "    using raw_states = type_list<typename Rows::source_state..., "
               "typename Rows::target_state...>;\n";
        out << "    using unique_states = detail::unique_t<raw_states>;\n";
        out << "    using state_variant = detail::to_variant_t<unique_states>;\n";
        out << "};\n\n";

        // State name helper
        out << "template <typename State>\n";
        out << "constexpr std::string_view get_state_name(const State&) noexcept "
               "{\n";
        out << "    if constexpr (requires { State::name; }) {\n";
        out << "        return State::name;\n";
        out << "    } else {\n";
        out << "        return \"State\";\n";
        out << "    }\n";
        out << "}\n\n";

        // Invocations
        out << "template <typename Guard, typename Event, typename State, typename "
               "Context>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, "
               "const State& s, Context* ctx) {\n";
        out << "    if constexpr (requires { { g(evt, s, *ctx) } -> "
               "std::convertible_to<bool>; }) {\n";
        out << "        return ctx ? g(evt, s, *ctx) : true;\n";
        out << "    } else if constexpr (requires { { g(evt, s) } -> "
               "std::convertible_to<bool>; }) {\n";
        out << "        return g(evt, s);\n";
        out << "    } else if constexpr (requires { { g(evt) } -> "
               "std::convertible_to<bool>; }) {\n";
        out << "        return g(evt);\n";
        out << "    } else if constexpr (requires { { g() } -> "
               "std::convertible_to<bool>; }) {\n";
        out << "        return g();\n";
        out << "    } else { return true; }\n";
        out << "}\n\n";

        out << "template <typename Guard, typename Event, typename State, typename Context, typename Fsm>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx, const Fsm& fsm) {\n";
        out << "    if constexpr (requires { { g(evt, s, *ctx, fsm) } -> std::convertible_to<bool>; }) {\n";
        out << "        return ctx ? g(evt, s, *ctx, fsm) : true;\n";
        out << "    } else if constexpr (requires { { g(evt, s, fsm) } -> std::convertible_to<bool>; }) {\n";
        out << "        return g(evt, s, fsm);\n";
        out << "    } else if constexpr (requires { { g(fsm) } -> std::convertible_to<bool>; }) {\n";
        out << "        return g(fsm);\n";
        out << "    } else {\n";
        out << "        return invoke_guard(g, evt, s, ctx);\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename Action, typename Event, typename SrcState, "
               "typename DstState, typename Context>\n";
        out << "constexpr void invoke_action(const Action& a, const Event& evt, "
               "SrcState& src, DstState& dst, Context* ctx) {\n";
        out << "    if constexpr (requires { a(evt, src, dst, *ctx); }) {\n";
        out << "        if (ctx) a(evt, src, dst, *ctx);\n";
        out << "    } else if constexpr (requires { a(evt, src, dst); }) {\n";
        out << "        a(evt, src, dst);\n";
        out << "    } else if constexpr (requires { a(evt, dst); }) {\n";
        out << "        a(evt, dst);\n";
        out << "    } else if constexpr (requires { a(evt); }) {\n";
        out << "        a(evt);\n";
        out << "    } else if constexpr (requires { a(); }) {\n";
        out << "        a();\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename State, typename Context>\n";
        out << "constexpr void invoke_enter_hook(State& s, Context* ctx) {\n";
        out << "    if constexpr (requires(State& st, Context& c) { "
               "st.on_enter(c); }) {\n";
        out << "        if (ctx) s.on_enter(*ctx);\n";
        out << "    } else if constexpr (requires(State& st) { st.on_enter(); }) "
               "{\n";
        out << "        s.on_enter();\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename State, typename Context>\n";
        out << "constexpr void invoke_exit_hook(State& s, Context* ctx) {\n";
        out << "    if constexpr (requires(State& st, Context& c) { st.on_exit(c); "
               "}) {\n";
        out << "        if (ctx) s.on_exit(*ctx);\n";
        out << "    } else if constexpr (requires(State& st) { st.on_exit(); }) "
               "{\n";
        out << "        s.on_exit();\n";
        out << "    }\n";
        out << "}\n\n";

        // FSM class
        out << "template <typename Table, typename Context = no_context, typename "
               "InitialState = typename std::tuple_element_t<0, typename "
               "Table::rows>::source_state>\n";
        out << "class fsm {\n";
        out << "public:\n";
        out << "    using table_type = Table;\n";
        out << "    using context_type = Context;\n";
        out << "    using state_variant = typename Table::state_variant;\n";
        out << "    using observer_type = std::function<void(const transition_info&)>;\n\n";
        out << "    static constexpr std::size_t state_count = std::variant_size_v<state_variant>;\n";
        out << "    static constexpr std::size_t transition_count = std::tuple_size_v<typename Table::rows>;\n";
        out << "    template <typename State> static constexpr bool has_state = detail::contains<State, typename "
               "Table::unique_states>::value;\n\n";
        out << "    constexpr fsm() : current_state_(InitialState{}), "
               "context_(nullptr) { enter_initial(); }\n";
        out << "    constexpr explicit fsm(Context& ctx) : "
               "current_state_(InitialState{}), context_(&ctx) { enter_initial(); "
               "}\n";
        out << "    constexpr explicit fsm(Context& ctx, InitialState init) : "
               "current_state_(std::move(init)), context_(&ctx) { enter_initial(); "
               "}\n\n";

        out << "    template <typename Event>\n";
        out << "    bool dispatch_direct(const Event& event) {\n";
        out << "        return std::visit([this, &event](auto& src) -> bool {\n";
        out << "            return process_event<Event, "
               "std::decay_t<decltype(src)>>(event, src);\n";
        out << "        }, current_state_);\n";
        out << "    }\n\n";

        out << "    template <typename Event>\n";
        out << "    bool dispatch(const Event& event) {\n";
        out << "        bool handled = dispatch_direct(event);\n";
        out << "        if (handled) {\n";
        out << "            process_deferred_queue();\n";
        out << "        } else {\n";
        out << "            bool deferred = std::visit([this, &event](const auto& src) -> bool {\n";
        out << "                using CurrentSrc = std::decay_t<decltype(src)>;\n";
        out << "                if constexpr (is_deferred_event_v<CurrentSrc, Event>) {\n";
        out << "                    this->deferred_queue_.push_back([event](fsm& self) -> bool {\n";
        out << "                        return self.dispatch_direct(event);\n";
        out << "                    });\n";
        out << "                    return true;\n";
        out << "                } else {\n";
        out << "                    return false;\n";
        out << "                }\n";
        out << "            }, current_state_);\n";
        out << "            if (deferred) return true;\n";
        out << "        }\n";
        out << "        return handled;\n";
        out << "    }\n\n";

        out << "    void process_deferred_queue() {\n";
        out << "        if (deferred_queue_.empty() || is_replaying_deferred_) return;\n";
        out << "        is_replaying_deferred_ = true;\n";
        out << "        bool any_handled = true;\n";
        out << "        while (any_handled && !deferred_queue_.empty()) {\n";
        out << "            any_handled = false;\n";
        out << "            for (auto it = deferred_queue_.begin(); it != deferred_queue_.end();) {\n";
        out << "                if ((*it)(*this)) {\n";
        out << "                    it = deferred_queue_.erase(it);\n";
        out << "                    any_handled = true;\n";
        out << "                    break;\n";
        out << "                }\n";
        out << "                ++it;\n";
        out << "            }\n";
        out << "        }\n";
        out << "        is_replaying_deferred_ = false;\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::size_t deferred_count() const noexcept { return deferred_queue_.size(); }\n";
        out << "    void clear_deferred_events() noexcept { deferred_queue_.clear(); }\n\n";

        out << "    void set_observer(observer_type observer) { observer_ = std::move(observer); }\n\n";

        out << "    struct history_entry {\n";
        out << "        std::string_view parent;\n";
        out << "        std::string_view substate;\n";
        out << "    };\n\n";

        out << "    void record_history(std::string_view parent, std::string_view substate) {\n";
        out << "        if (parent.empty() || substate.empty()) return;\n";
        out << "        for (auto& entry : history_records_) {\n";
        out << "            if (entry.parent == parent) { entry.substate = substate; return; }\n";
        out << "        }\n";
        out << "        history_records_.push_back({parent, substate});\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::string_view get_history(std::string_view parent) const noexcept {\n";
        out << "        for (const auto& entry : history_records_) {\n";
        out << "            if (entry.parent == parent) return entry.substate;\n";
        out << "        }\n";
        out << "        return \"\";\n";
        out << "    }\n\n";

        out << "    template <typename State> [[nodiscard]] constexpr bool "
               "is_in_state() const noexcept {\n";
        out << "        return std::holds_alternative<State>(current_state_);\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::string_view current_state_name() const "
               "noexcept {\n";
        out << "        return std::visit([](const auto& s) { return "
               "::fsm::get_state_name(s); }, current_state_);\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] const state_variant& get_current_state_variant() "
               "const noexcept { return current_state_; }\n";
        out << "    [[nodiscard]] Context* get_context() noexcept { return "
               "context_; }\n\n";

        out << "private:\n";
        out << "    constexpr void enter_initial() {\n";
        out << "        std::visit([this](auto& s) { ::fsm::invoke_enter_hook(s, "
               "context_); }, current_state_);\n";
        out << "    }\n\n";

        out << "    template <typename Event, typename SrcState>\n";
        out << "    bool process_event(const Event& evt, SrcState& src) {\n";
        out << "        bool handled = false;\n";
        out << "        std::apply([&](auto... row_inst) {\n";
        out << "            ((!handled && (handled = "
               "try_transition<decltype(row_inst)>(evt, src))), ...);\n";
        out << "        }, typename Table::rows{});\n";
        out << "        return handled;\n";
        out << "    }\n\n";

        out << "    template <typename Row, typename Event, typename SrcState>\n";
        out << "    bool try_transition(const Event& evt, SrcState& src) {\n";
        out << "        if constexpr (std::is_same_v<SrcState, typename "
               "Row::source_state> && std::is_same_v<Event, typename "
               "Row::event_type>) {\n";
        out << "            if (::fsm::invoke_guard(typename Row::guard_type{}, "
               "evt, src, context_, *this)) {\n";
        out << "                if constexpr (Row::is_internal) {\n";
        out << "                    ::fsm::invoke_action(typename Row::action_type{}, evt, src, src, context_);\n";
        out << "                    if (observer_) observer_(transition_info{::fsm::get_state_name(src), ::fsm::get_state_name(src), \"Event\", true});\n";
        out << "                    return true;\n";
        out << "                } else {\n";
        out << "                    if constexpr (requires { SrcState::parent; }) {\n";
        out << "                        constexpr std::string_view src_p = SrcState::parent;\n";
        out << "                        std::string_view dst_p = \"\";\n";
        out << "                        if constexpr (requires { typename Row::target_state::parent; }) {\n";
        out << "                            dst_p = Row::target_state::parent;\n";
        out << "                        }\n";
        out << "                        if (src_p != dst_p) {\n";
        out << "                            record_history(src_p, ::fsm::get_state_name(src));\n";
        out << "                        }\n";
        out << "                    }\n";
        out << "                    ::fsm::invoke_exit_hook(src, context_);\n";
        out << "                    typename Row::target_state dst_state{};\n";
        out << "                    ::fsm::invoke_action(typename Row::action_type{}, "
               "evt, src, dst_state, context_);\n";
        out << "                    ::fsm::invoke_enter_hook(dst_state, context_);\n";
        out << "                    if (observer_) observer_(transition_info{::fsm::get_state_name(src), ::fsm::get_state_name(dst_state), \"Event\", false});\n";
        out << "                    current_state_.template emplace<typename "
               "Row::target_state>(std::move(dst_state));\n";
        out << "                    return true;\n";
        out << "                }\n";
        out << "            }\n";
        out << "        }\n";
        out << "        return false;\n";
        out << "    }\n\n";

        out << "    state_variant current_state_;\n";
        out << "    Context* context_{nullptr};\n";
        out << "    observer_type observer_{};\n";
        out << "    std::vector<history_entry> history_records_{};\n";
        out << "    std::vector<std::function<bool(fsm&)>> deferred_queue_{};\n";
        out << "    bool is_replaying_deferred_{false};\n";
        out << "};\n\n";

        // Thread-Safe wrapper in C++20 with std::jthread and std::stop_token
        if (opts.thread_safe) {
            out << "template <typename Table, typename Context = no_context, "
                   "typename InitialState = typename std::tuple_element_t<0, "
                   "typename Table::rows>::source_state>\n";
            out << "class thread_safe_fsm {\n";
            out << "public:\n";
            out << "    using fsm_type = fsm<Table, Context, InitialState>;\n";
            out << "    using event_handler = std::function<void(fsm_type&)>;\n\n";
            out << "    thread_safe_fsm() : fsm_() {}\n";
            out << "    explicit thread_safe_fsm(Context& ctx) : fsm_(ctx) {}\n";
            out << "    ~thread_safe_fsm() { stop_worker(); }\n\n";

            out << "    template <typename Event>\n";
            out << "    void post(Event&& event) {\n";
            out << "        {\n";
            out << "            std::scoped_lock lock(mutex_);\n";
            out << "            queue_.push([evt = "
                   "std::forward<Event>(event)](fsm_type& m) { m.dispatch(evt); "
                   "});\n";
            out << "        }\n";
            out << "        cv_.notify_one();\n";
            out << "    }\n\n";

            out << "    void set_observer(typename fsm_type::observer_type obs) {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        fsm_.set_observer(std::move(obs));\n";
            out << "    }\n\n";

            out << "    void start_worker() {\n";
            out << "        if (worker_.joinable()) return;\n";
            out << "        running_ = true;\n";
            out << "        worker_ = std::jthread([this](std::stop_token st) {\n";
            out << "            while (!st.stop_requested()) {\n";
            out << "                event_handler task;\n";
            out << "                {\n";
            out << "                    std::unique_lock<std::recursive_mutex> lock(mutex_);\n";
            out << "                    cv_.wait(lock, [&] { return !queue_.empty() "
                   "|| !running_.load(); });\n";
            out << "                    if (!running_.load() && queue_.empty()) "
                   "break;\n";
            out << "                    if (!queue_.empty()) {\n";
            out << "                        task = std::move(queue_.front());\n";
            out << "                        queue_.pop();\n";
            out << "                    }\n";
            out << "                }\n";
            out << "                if (task) {\n";
            out << "                    std::scoped_lock lock(mutex_);\n";
            out << "                    task(fsm_);\n";
            out << "                }\n";
            out << "            }\n";
            out << "        });\n";
            out << "    }\n\n";

            out << "    void stop_worker() {\n";
            out << "        running_ = false;\n";
            out << "        cv_.notify_all();\n";
            out << "        if (worker_.joinable()) {\n";
            out << "            worker_.request_stop();\n";
            out << "            worker_.join();\n";
            out << "        }\n";
            out << "    }\n\n";

            out << "    template <typename State> [[nodiscard]] bool is_in_state() "
                   "const {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return fsm_.template is_in_state<State>();\n";
            out << "    }\n\n";

            out << "    [[nodiscard]] std::string_view current_state_name() const "
                   "{\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return fsm_.current_state_name();\n";
            out << "    }\n\n";

            out << "    [[nodiscard]] bool is_queue_empty() const {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return queue_.empty();\n";
            out << "    }\n\n";

            out << "private:\n";
            out << "    fsm_type fsm_;\n";
            out << "    mutable std::recursive_mutex mutex_;\n";
            out << "    std::condition_variable_any cv_;\n";
            out << "    std::queue<event_handler> queue_;\n";
            out << "    std::atomic<bool> running_{false};\n";
            out << "    std::jthread worker_;\n";
            out << "};\n\n";
        }

        out << "} // namespace fsm\n\n";
    }

    static void generate_cpp17_standalone_runtime(std::ostream& out, const GeneratorOptions& opts) {
        out << "#include <variant>\n";
        out << "#include <tuple>\n";
        out << "#include <string_view>\n";
        out << "#include <type_traits>\n";
        out << "#include <utility>\n";
        out << "#include <functional>\n";
        out << "#include <vector>\n";
        if (opts.thread_safe) {
            out << "#include <queue>\n";
            out << "#include <mutex>\n";
            out << "#include <condition_variable>\n";
            out << "#include <thread>\n";
            out << "#include <atomic>\n";
        }
        out << "\n";

        out << "namespace fsm {\n\n";
        out << "struct no_context {};\n\n";

        out << "struct transition_info {\n";
        out << "    std::string_view source;\n";
        out << "    std::string_view target;\n";
        out << "    std::string_view event;\n";
        out << "    bool is_internal = false;\n";
        out << "};\n\n";

        out << "template <typename... Ts> struct type_list {};\n\n";

        out << "namespace detail {\n";
        out << "template <typename T, typename List> struct contains;\n";
        out << "template <typename T> struct contains<T, type_list<>> : "
               "std::false_type {};\n";
        out << "template <typename T, typename... Rest> struct contains<T, "
               "type_list<T, Rest...>> : std::true_type {};\n";
        out << "template <typename T, typename Head, typename... Rest> struct "
               "contains<T, type_list<Head, Rest...>> : contains<T, "
               "type_list<Rest...>> {};\n\n";

        out << "template <typename InList, typename OutList = type_list<>> struct "
               "unique;\n";
        out << "template <typename OutList> struct unique<type_list<>, OutList> { "
               "using type = OutList; };\n";
        out << "template <typename Head, typename... Tail, typename... Out> struct "
               "unique<type_list<Head, Tail...>, type_list<Out...>> {\n";
        out << "    using type = std::conditional_t<contains<Head, "
               "type_list<Out...>>::value,\n";
        out << "        typename unique<type_list<Tail...>, "
               "type_list<Out...>>::type,\n";
        out << "        typename unique<type_list<Tail...>, type_list<Out..., "
               "Head>>::type>;\n";
        out << "};\n";
        out << "template <typename List> using unique_t = typename "
               "unique<List>::type;\n\n";

        out << "template <typename List> struct to_variant;\n";
        out << "template <typename... Ts> struct to_variant<type_list<Ts...>> { "
               "using type = std::variant<Ts...>; };\n";
        out << "template <typename List> using to_variant_t = typename "
               "to_variant<List>::type;\n";
        out << "} // namespace detail\n\n";

        out << "namespace detail {\n";
        out << "template <typename State, typename = void> struct has_deferred_events : std::false_type {};\n";
        out << "template <typename State> struct has_deferred_events<State, std::void_t<typename State::deferred_events>> : std::true_type {};\n";
        out << "} // namespace detail\n\n";

        out << "template <typename State, typename Event>\n";
        out << "inline constexpr bool is_deferred_event_v = []() constexpr {\n";
        out << "    if constexpr (detail::has_deferred_events<State>::value) {\n";
        out << "        return detail::contains<std::decay_t<Event>, typename State::deferred_events>::value;\n";
        out << "    } else {\n";
        out << "        return false;\n";
        out << "    }\n";
        out << "}();\n\n";

        out << "struct no_guard {\n";
        out << "    template <typename... Args> constexpr bool operator()(const "
               "Args&...) const noexcept { return true; }\n";
        out << "};\n\n";

        out << "struct no_action {\n";
        out << "    template <typename... Args> constexpr void "
               "operator()(Args&...) const noexcept {}\n";
        out << "};\n\n";

        // Combinators
        out << "template <typename Guard, typename Event, typename State, typename Context>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx);\n\n";

        out << "template <typename Guard, typename Event, typename State, typename Context, typename Fsm>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx, const Fsm& fsm);\n\n";

        out << "template <typename Guard>\n";
        out << "struct not_ {\n";
        out << "    Guard guard_fn{};\n";
        out << "    constexpr not_() = default;\n";
        out << "    constexpr explicit not_(Guard g) : guard_fn(std::move(g)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        return !invoke_guard(guard_fn, evt, s, &ctx, fsm);\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        return !invoke_guard(guard_fn, evt, s, &ctx);\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename Guard1, typename Guard2, typename... Rest>\n";
        out << "struct and_ {\n";
        out << "    Guard1 g1{};\n";
        out << "    Guard2 g2{};\n";
        out << "    constexpr and_() = default;\n";
        out << "    constexpr and_(Guard1 first, Guard2 second) : g1(std::move(first)), g2(std::move(second)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        if (!invoke_guard(g1, evt, s, &ctx, fsm)) return false;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx, fsm);\n";
        out << "        } else {\n";
        out << "            return and_<Guard2, Rest...>{}(evt, s, ctx, fsm);\n";
        out << "        }\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        if (!invoke_guard(g1, evt, s, &ctx)) return false;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx);\n";
        out << "        } else {\n";
        out << "            return and_<Guard2, Rest...>{}(evt, s, ctx);\n";
        out << "        }\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename Guard1, typename Guard2, typename... Rest>\n";
        out << "struct or_ {\n";
        out << "    Guard1 g1{};\n";
        out << "    Guard2 g2{};\n";
        out << "    constexpr or_() = default;\n";
        out << "    constexpr or_(Guard1 first, Guard2 second) : g1(std::move(first)), g2(std::move(second)) {}\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx, const Fsm& fsm) const {\n";
        out << "        if (invoke_guard(g1, evt, s, &ctx, fsm)) return true;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx, fsm);\n";
        out << "        } else {\n";
        out << "            return or_<Guard2, Rest...>{}(evt, s, ctx, fsm);\n";
        out << "        }\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event& evt, const State& s, Context& ctx) const {\n";
        out << "        if (invoke_guard(g1, evt, s, &ctx)) return true;\n";
        out << "        if constexpr (sizeof...(Rest) == 0) {\n";
        out << "            return invoke_guard(g2, evt, s, &ctx);\n";
        out << "        } else {\n";
        out << "            return or_<Guard2, Rest...>{}(evt, s, ctx);\n";
        out << "        }\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename ParentState, typename SubState>\n";
        out << "struct history_is {\n";
        out << "    template <typename Event, typename State, typename Context, typename Fsm>\n";
        out << "    constexpr bool operator()(const Event&, const State&, Context&, const Fsm& fsm) const {\n";
        out << "        return fsm.get_history(ParentState::name) == SubState::name;\n";
        out << "    }\n";
        out << "    template <typename Event, typename State, typename Context>\n";
        out << "    constexpr bool operator()(const Event&, const State&, Context&) const {\n";
        out << "        return false;\n";
        out << "    }\n";
        out << "};\n\n";

        out << "template <typename Src, typename Evt, typename Dst, typename "
               "GuardType = no_guard, typename ActionType = no_action>\n";
        out << "struct row {\n";
        out << "    using source_state = Src;\n";
        out << "    using event_type = Evt;\n";
        out << "    using target_state = Dst;\n";
        out << "    using guard_type = GuardType;\n";
        out << "    using action_type = ActionType;\n";
        out << "    static constexpr bool is_internal = false;\n\n";
        out << "    template <typename G> using when = row<Src, Evt, Dst, G, "
               "ActionType>;\n";
        out << "    template <typename A> using then = row<Src, Evt, Dst, "
               "GuardType, A>;\n";
        out << "};\n\n";

        out << "template <typename State, typename Evt, typename GuardType = no_guard, typename ActionType = "
               "no_action>\n";
        out << "struct internal_row {\n";
        out << "    using source_state = State;\n";
        out << "    using event_type = Evt;\n";
        out << "    using target_state = State;\n";
        out << "    using guard_type = GuardType;\n";
        out << "    using action_type = ActionType;\n";
        out << "    static constexpr bool is_internal = true;\n\n";
        out << "    template <typename G> using when = internal_row<State, Evt, G, ActionType>;\n";
        out << "    template <typename A> using then = internal_row<State, Evt, GuardType, A>;\n";
        out << "};\n\n";

        out << "template <typename... Rows>\n";
        out << "struct transition_table {\n";
        out << "    using rows = std::tuple<Rows...>;\n";
        out << "    using raw_states = type_list<typename Rows::source_state..., "
               "typename Rows::target_state...>;\n";
        out << "    using unique_states = detail::unique_t<raw_states>;\n";
        out << "    using state_variant = detail::to_variant_t<unique_states>;\n";
        out << "};\n\n";

        // SFINAE helpers for C++17
        out << "namespace detail {\n";
        out << "template <typename T, typename = void> struct has_name : "
               "std::false_type {};\n";
        out << "template <typename T> struct has_name<T, "
               "std::void_t<decltype(T::name)>> : std::true_type {};\n\n";
        out << "template <typename T, typename = void> struct has_parent : "
               "std::false_type {};\n";
        out << "template <typename T> struct has_parent<T, "
               "std::void_t<decltype(T::parent)>> : std::true_type {};\n\n";
        out << "template <typename T, typename = void> struct has_on_enter : "
               "std::false_type {};\n";
        out << "template <typename T> struct has_on_enter<T, "
               "std::void_t<decltype(&T::on_enter)>> : std::true_type {};\n\n";
        out << "template <typename T, typename = void> struct has_on_exit : "
               "std::false_type {};\n";
        out << "template <typename T> struct has_on_exit<T, "
               "std::void_t<decltype(&T::on_exit)>> : std::true_type {};\n";
        out << "} // namespace detail\n\n";

        out << "template <typename State>\n";
        out << "constexpr std::string_view get_state_name(const State&) noexcept "
               "{\n";
        out << "    if constexpr (detail::has_name<State>::value) {\n";
        out << "        return State::name;\n";
        out << "    } else {\n";
        out << "        return \"State\";\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename Guard, typename Event, typename State, typename "
               "Context>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, "
               "const State& s, Context* ctx) {\n";
        out << "    if constexpr (std::is_invocable_v<Guard, const Event&, const "
               "State&, Context&>) {\n";
        out << "        return ctx ? g(evt, s, *ctx) : true;\n";
        out << "    } else if constexpr (std::is_invocable_v<Guard, const Event&, "
               "const State&>) {\n";
        out << "        return g(evt, s);\n";
        out << "    } else if constexpr (std::is_invocable_v<Guard, const Event&>) "
               "{\n";
        out << "        return g(evt);\n";
        out << "    } else if constexpr (std::is_invocable_v<Guard>) {\n";
        out << "        return g();\n";
        out << "    } else { return true; }\n";
        out << "}\n\n";

        out << "template <typename Guard, typename Event, typename State, typename Context, typename Fsm>\n";
        out << "constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx, const Fsm& fsm) {\n";
        out << "    if constexpr (std::is_invocable_v<Guard, const Event&, const State&, Context&, const Fsm&>) {\n";
        out << "        return ctx ? g(evt, s, *ctx, fsm) : true;\n";
        out << "    } else if constexpr (std::is_invocable_v<Guard, const Event&, const State&, const Fsm&>) {\n";
        out << "        return g(evt, s, fsm);\n";
        out << "    } else if constexpr (std::is_invocable_v<Guard, const Fsm&>) {\n";
        out << "        return g(fsm);\n";
        out << "    } else {\n";
        out << "        return invoke_guard(g, evt, s, ctx);\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename Action, typename Event, typename SrcState, "
               "typename DstState, typename Context>\n";
        out << "constexpr void invoke_action(const Action& a, const Event& evt, "
               "SrcState& src, DstState& dst, Context* ctx) {\n";
        out << "    if constexpr (std::is_invocable_v<Action, const Event&, "
               "SrcState&, DstState&, Context&>) {\n";
        out << "        if (ctx) a(evt, src, dst, *ctx);\n";
        out << "    } else if constexpr (std::is_invocable_v<Action, const Event&, "
               "SrcState&, DstState&>) {\n";
        out << "        a(evt, src, dst);\n";
        out << "    } else if constexpr (std::is_invocable_v<Action, const Event&, "
               "DstState&>) {\n";
        out << "        a(evt, dst);\n";
        out << "    } else if constexpr (std::is_invocable_v<Action, const "
               "Event&>) {\n";
        out << "        a(evt);\n";
        out << "    } else if constexpr (std::is_invocable_v<Action>) {\n";
        out << "        a();\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename State, typename Context>\n";
        out << "constexpr void invoke_enter_hook(State& s, Context* ctx) {\n";
        out << "    if constexpr (detail::has_on_enter<State>::value) {\n";
        out << "        if constexpr "
               "(std::is_invocable_v<decltype(&State::on_enter), State&, "
               "Context&>) {\n";
        out << "            if (ctx) s.on_enter(*ctx);\n";
        out << "        } else if constexpr "
               "(std::is_invocable_v<decltype(&State::on_enter), State&>) {\n";
        out << "            s.on_enter();\n";
        out << "        }\n";
        out << "    }\n";
        out << "}\n\n";

        out << "template <typename State, typename Context>\n";
        out << "constexpr void invoke_exit_hook(State& s, Context* ctx) {\n";
        out << "    if constexpr (detail::has_on_exit<State>::value) {\n";
        out << "        if constexpr "
               "(std::is_invocable_v<decltype(&State::on_exit), State&, Context&>) "
               "{\n";
        out << "            if (ctx) s.on_exit(*ctx);\n";
        out << "        } else if constexpr "
               "(std::is_invocable_v<decltype(&State::on_exit), State&>) {\n";
        out << "            s.on_exit();\n";
        out << "        }\n";
        out << "    }\n";
        out << "}\n\n";

        // FSM class
        out << "template <typename Table, typename Context = no_context, typename "
               "InitialState = typename std::tuple_element_t<0, typename "
               "Table::rows>::source_state>\n";
        out << "class fsm {\n";
        out << "public:\n";
        out << "    using table_type = Table;\n";
        out << "    using context_type = Context;\n";
        out << "    using state_variant = typename Table::state_variant;\n";
        out << "    using observer_type = std::function<void(const transition_info&)>;\n\n";
        out << "    static constexpr std::size_t state_count = std::variant_size_v<state_variant>;\n";
        out << "    static constexpr std::size_t transition_count = std::tuple_size_v<typename Table::rows>;\n";
        out << "    template <typename State> static constexpr bool has_state = detail::contains<State, typename "
               "Table::unique_states>::value;\n\n";
        out << "    constexpr fsm() : current_state_(InitialState{}), "
               "context_(nullptr) { enter_initial(); }\n";
        out << "    constexpr explicit fsm(Context& ctx) : "
               "current_state_(InitialState{}), context_(&ctx) { enter_initial(); "
               "}\n";
        out << "    constexpr explicit fsm(Context& ctx, InitialState init) : "
               "current_state_(std::move(init)), context_(&ctx) { enter_initial(); "
               "}\n\n";

        out << "    template <typename Event>\n";
        out << "    bool dispatch_direct(const Event& event) {\n";
        out << "        return std::visit([this, &event](auto& src) -> bool {\n";
        out << "            return process_event<Event, "
               "std::decay_t<decltype(src)>>(event, src);\n";
        out << "        }, current_state_);\n";
        out << "    }\n\n";

        out << "    template <typename Event>\n";
        out << "    bool dispatch(const Event& event) {\n";
        out << "        bool handled = dispatch_direct(event);\n";
        out << "        if (handled) {\n";
        out << "            process_deferred_queue();\n";
        out << "        } else {\n";
        out << "            bool deferred = std::visit([this, &event](const auto& src) -> bool {\n";
        out << "                using CurrentSrc = std::decay_t<decltype(src)>;\n";
        out << "                if constexpr (is_deferred_event_v<CurrentSrc, Event>) {\n";
        out << "                    this->deferred_queue_.push_back([event](fsm& self) -> bool {\n";
        out << "                        return self.dispatch_direct(event);\n";
        out << "                    });\n";
        out << "                    return true;\n";
        out << "                } else {\n";
        out << "                    return false;\n";
        out << "                }\n";
        out << "            }, current_state_);\n";
        out << "            if (deferred) return true;\n";
        out << "        }\n";
        out << "        return handled;\n";
        out << "    }\n\n";

        out << "    void process_deferred_queue() {\n";
        out << "        if (deferred_queue_.empty() || is_replaying_deferred_) return;\n";
        out << "        is_replaying_deferred_ = true;\n";
        out << "        bool any_handled = true;\n";
        out << "        while (any_handled && !deferred_queue_.empty()) {\n";
        out << "            any_handled = false;\n";
        out << "            for (auto it = deferred_queue_.begin(); it != deferred_queue_.end();) {\n";
        out << "                if ((*it)(*this)) {\n";
        out << "                    it = deferred_queue_.erase(it);\n";
        out << "                    any_handled = true;\n";
        out << "                    break;\n";
        out << "                }\n";
        out << "                ++it;\n";
        out << "            }\n";
        out << "        }\n";
        out << "        is_replaying_deferred_ = false;\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::size_t deferred_count() const noexcept { return deferred_queue_.size(); }\n";
        out << "    void clear_deferred_events() noexcept { deferred_queue_.clear(); }\n\n";

        out << "    void set_observer(observer_type observer) { observer_ = std::move(observer); }\n\n";

        out << "    struct history_entry {\n";
        out << "        std::string_view parent;\n";
        out << "        std::string_view substate;\n";
        out << "    };\n\n";

        out << "    void record_history(std::string_view parent, std::string_view substate) {\n";
        out << "        if (parent.empty() || substate.empty()) return;\n";
        out << "        for (auto& entry : history_records_) {\n";
        out << "            if (entry.parent == parent) { entry.substate = substate; return; }\n";
        out << "        }\n";
        out << "        history_records_.push_back({parent, substate});\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] std::string_view get_history(std::string_view parent) const noexcept {\n";
        out << "        for (const auto& entry : history_records_) {\n";
        out << "            if (entry.parent == parent) return entry.substate;\n";
        out << "        }\n";
        out << "        return \"\";\n";
        out << "    }\n\n";

        out << "    template <typename State> constexpr bool is_in_state() const "
               "noexcept {\n";
        out << "        return std::holds_alternative<State>(current_state_);\n";
        out << "    }\n\n";

        out << "    std::string_view current_state_name() const noexcept {\n";
        out << "        return std::visit([](const auto& s) { \n";
        out << "            if constexpr "
               "(detail::has_name<std::decay_t<decltype(s)>>::value) {\n";
        out << "                return std::decay_t<decltype(s)>::name;\n";
        out << "            } else { return std::string_view(\"State\"); }\n";
        out << "        }, current_state_);\n";
        out << "    }\n\n";

        out << "    const state_variant& get_current_state_variant() const "
               "noexcept { return current_state_; }\n";
        out << "    Context* get_context() noexcept { return context_; }\n\n";

        out << "private:\n";
        out << "    constexpr void enter_initial() {\n";
        out << "        std::visit([this](auto& s) { ::fsm::invoke_enter_hook(s, "
               "context_); }, current_state_);\n";
        out << "    }\n\n";

        out << "    template <typename Event, typename SrcState>\n";
        out << "    bool process_event(const Event& evt, SrcState& src) {\n";
        out << "        bool handled = false;\n";
        out << "        std::apply([&](auto... row_inst) {\n";
        out << "            ((!handled && (handled = "
               "try_transition<decltype(row_inst)>(evt, src))), ...);\n";
        out << "        }, typename Table::rows{});\n";
        out << "        return handled;\n";
        out << "    }\n\n";

        out << "    template <typename Row, typename Event, typename SrcState>\n";
        out << "    bool try_transition(const Event& evt, SrcState& src) {\n";
        out << "        if constexpr (std::is_same_v<SrcState, typename "
               "Row::source_state> && std::is_same_v<Event, typename "
               "Row::event_type>) {\n";
        out << "            if (::fsm::invoke_guard(typename Row::guard_type{}, "
               "evt, src, context_, *this)) {\n";
        out << "                if constexpr (Row::is_internal) {\n";
        out << "                    ::fsm::invoke_action(typename Row::action_type{}, evt, src, src, context_);\n";
        out << "                    if (observer_) observer_(transition_info{::fsm::get_state_name(src), ::fsm::get_state_name(src), \"Event\", true});\n";
        out << "                    return true;\n";
        out << "                } else {\n";
        out << "                    if constexpr (detail::has_parent<SrcState>::value) {\n";
        out << "                        constexpr std::string_view src_p = SrcState::parent;\n";
        out << "                        std::string_view dst_p = \"\";\n";
        out << "                        if constexpr (detail::has_parent<typename Row::target_state>::value) {\n";
        out << "                            dst_p = Row::target_state::parent;\n";
        out << "                        }\n";
        out << "                        if (src_p != dst_p) {\n";
        out << "                            record_history(src_p, ::fsm::get_state_name(src));\n";
        out << "                        }\n";
        out << "                    }\n";
        out << "                    ::fsm::invoke_exit_hook(src, context_);\n";
        out << "                    typename Row::target_state dst_state{};\n";
        out << "                    ::fsm::invoke_action(typename Row::action_type{}, "
               "evt, src, dst_state, context_);\n";
        out << "                    ::fsm::invoke_enter_hook(dst_state, context_);\n";
        out << "                    if (observer_) observer_(transition_info{::fsm::get_state_name(src), ::fsm::get_state_name(dst_state), \"Event\", false});\n";
        out << "                    current_state_.template emplace<typename "
               "Row::target_state>(std::move(dst_state));\n";
        out << "                    return true;\n";
        out << "                }\n";
        out << "            }\n";
        out << "        }\n";
        out << "        return false;\n";
        out << "    }\n\n";

        out << "    state_variant current_state_;\n";
        out << "    Context* context_{nullptr};\n";
        out << "    observer_type observer_{};\n";
        out << "    std::vector<history_entry> history_records_{};\n";
        out << "    std::vector<std::function<bool(fsm&)>> deferred_queue_{};\n";
        out << "    bool is_replaying_deferred_{false};\n";
        out << "};\n\n";

        // Thread-Safe wrapper in C++17
        if (opts.thread_safe) {
            out << "template <typename Table, typename Context = no_context, "
                   "typename InitialState = typename std::tuple_element_t<0, "
                   "typename Table::rows>::source_state>\n";
            out << "class thread_safe_fsm {\n";
            out << "public:\n";
            out << "    using fsm_type = fsm<Table, Context, InitialState>;\n";
            out << "    using event_handler = std::function<void(fsm_type&)>;\n\n";
            out << "    thread_safe_fsm() : fsm_() {}\n";
            out << "    explicit thread_safe_fsm(Context& ctx) : fsm_(ctx) {}\n";
            out << "    ~thread_safe_fsm() { stop_worker(); }\n\n";

            out << "    template <typename Event>\n";
            out << "    void post(Event&& event) {\n";
            out << "        {\n";
            out << "            std::scoped_lock lock(mutex_);\n";
            out << "            queue_.push([evt = "
                   "std::forward<Event>(event)](fsm_type& m) { m.dispatch(evt); "
                   "});\n";
            out << "        }\n";
            out << "        cv_.notify_one();\n";
            out << "    }\n\n";

            out << "    void set_observer(typename fsm_type::observer_type obs) {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        fsm_.set_observer(std::move(obs));\n";
            out << "    }\n\n";

            out << "    void start_worker() {\n";
            out << "        if (worker_.joinable()) return;\n";
            out << "        running_ = true;\n";
            out << "        worker_ = std::thread([this]() {\n";
            out << "            while (running_.load()) {\n";
            out << "                event_handler task;\n";
            out << "                {\n";
            out << "                    std::unique_lock<std::recursive_mutex> lock(mutex_);\n";
            out << "                    cv_.wait(lock, [&] { return !queue_.empty() "
                   "|| !running_.load(); });\n";
            out << "                    if (!running_.load() && queue_.empty()) "
                   "break;\n";
            out << "                    if (!queue_.empty()) {\n";
            out << "                        task = std::move(queue_.front());\n";
            out << "                        queue_.pop();\n";
            out << "                    }\n";
            out << "                }\n";
            out << "                if (task) {\n";
            out << "                    std::scoped_lock lock(mutex_);\n";
            out << "                    task(fsm_);\n";
            out << "                }\n";
            out << "            }\n";
            out << "        });\n";
            out << "    }\n\n";

            out << "    void stop_worker() {\n";
            out << "        running_ = false;\n";
            out << "        cv_.notify_all();\n";
            out << "        if (worker_.joinable()) {\n";
            out << "            worker_.join();\n";
            out << "        }\n";
            out << "    }\n\n";

            out << "    template <typename State> bool is_in_state() const {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return fsm_.template is_in_state<State>();\n";
            out << "    }\n\n";

            out << "    std::string_view current_state_name() const {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return fsm_.current_state_name();\n";
            out << "    }\n\n";

            out << "    bool is_queue_empty() const {\n";
            out << "        std::scoped_lock lock(mutex_);\n";
            out << "        return queue_.empty();\n";
            out << "    }\n\n";

            out << "private:\n";
            out << "    fsm_type fsm_;\n";
            out << "    mutable std::recursive_mutex mutex_;\n";
            out << "    std::condition_variable_any cv_;\n";
            out << "    std::queue<event_handler> queue_;\n";
            out << "    std::atomic<bool> running_{false};\n";
            out << "    std::thread worker_;\n";
            out << "};\n\n";
        }

        out << "} // namespace fsm\n\n";
    }
};

}  // namespace fsm::codegen
