#include <chrono>
#include <cstdint>
#include <iomanip>
#include <iostream>
#include <string_view>
#include <thread>

// Include generated standalone FSM (generated by fsmc_target_sources during CMake build)
#include "motor_fsm.hpp"

// Include hard real-time SPSC lock-free ring buffer for simulated ISR event injection
#include "fsm/spsc_ring_buffer.hpp"

// User context containing device hardware state
namespace fsm_generated {
struct MotorHardwareContext {
    int target_rpm = 0;
    int current_rpm = 0;
    float inverter_temp_celsius = 25.0F;
    float phase_current_amps = 0.0F;
    uint64_t total_odometry_ticks = 0;
    bool inverter_powered = false;
    bool pid_engaged = false;
    bool brake_engaged = false;
    bool fault_active = false;
};
}  // namespace fsm_generated

// Implement user guards
struct fsm_generated::HasValidRpmGuard {
    [[nodiscard]] bool operator()(const fsm_generated::StartCmd& /*evt*/, const auto& /*src*/,
                                  const MotorHardwareContext& ctx) const noexcept {
        return ctx.target_rpm > 0 && ctx.target_rpm <= 8000;
    }
};

struct fsm_generated::IsThermalSafeGuard {
    [[nodiscard]] bool operator()(const fsm_generated::ResetFaultCmd& /*evt*/, const auto& /*src*/,
                                  const MotorHardwareContext& ctx) const noexcept {
        return ctx.inverter_temp_celsius < 75.0F;
    }
};

// Implement user actions
struct fsm_generated::PowerOnInverterAction {
    void operator()(const fsm_generated::StartCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.inverter_powered = true;
        ctx.phase_current_amps = 12.5F;
        std::cout << "\033[1;32m  [HW Action]\033[0m Gate drivers energized -> 3-phase inverter ON (Target: "
                  << ctx.target_rpm << " RPM, Current: " << ctx.phase_current_amps << " A)\n";
    }
};

struct fsm_generated::EngageSpeedPidAction {
    void operator()(const fsm_generated::SpeedReachedEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.pid_engaged = true;
        ctx.current_rpm = ctx.target_rpm;
        std::cout << "\033[1;32m  [HW Action]\033[0m Target velocity acquired -> Closed-loop PID engaged at "
                  << ctx.current_rpm << " RPM.\n";
    }
};

struct fsm_generated::UpdateOdometryAction {
    void operator()(const fsm_generated::SpeedSensorTick& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.total_odometry_ticks += 64;
        std::cout << "\033[1;36m  [HW Action/INTERNAL]\033[0m Hall sensor pulse -> Odometry ticks: "
                  << ctx.total_odometry_ticks << " (Zero entry/exit lifecycle cost)\n";
    }
};

struct fsm_generated::ApplyRegenerativeBrakeAction {
    void operator()(const fsm_generated::StopCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.pid_engaged = false;
        ctx.brake_engaged = true;
        std::cout << "\033[1;33m  [HW Action]\033[0m Deceleration requested -> Regenerative braking active, energy "
                     "recuperated.\n";
    }
};

struct fsm_generated::DisengageInverterAction {
    void operator()(const fsm_generated::StoppedEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.brake_engaged = false;
        ctx.inverter_powered = false;
        ctx.current_rpm = 0;
        ctx.phase_current_amps = 0.0F;
        std::cout << "\033[1;32m  [HW Action]\033[0m Rotor stationary -> Inverter shut down safely. Ready for next "
                     "cycle.\n";
    }
};

struct fsm_generated::EmergencyCutoffAction {
    void operator()(const fsm_generated::OvercurrentEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.inverter_powered = false;
        ctx.pid_engaged = false;
        ctx.fault_active = true;
        ctx.current_rpm = 0;
        ctx.phase_current_amps = 0.0F;
        std::cout << "\033[1;31m  [HW Action/SAFETY]\033[0m OVERCURRENT TRIP: Hardware gate driver disabled in <20ns! "
                     "System locked in FAULT.\n";
    }
};

struct fsm_generated::ClearFaultFlagsAction {
    void operator()(const fsm_generated::ResetFaultCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.fault_active = false;
        std::cout << "\033[1;32m  [HW Action]\033[0m Thermal check passed (" << ctx.inverter_temp_celsius
                  << " C) -> Fault flags reset. Hardware ready.\n";
    }
};

namespace {

void print_header(std::string_view title) {
    std::cout << "\n\033[1;35m======================================================================\033[0m\n";
    std::cout << "\033[1;37m  " << title << "\033[0m\n";
    std::cout << "\033[1;35m======================================================================\033[0m\n";
}

void print_telemetry_hud(const fsm_generated::MotorHardwareContext& ctx, std::string_view state_name) {
    std::cout << "  ┌─────────────────────────────────────────────────────────────┐\n";
    std::cout << "  │ \033[1mState:\033[0m " << std::left << std::setw(15) << state_name
              << " │ \033[1mInverter:\033[0m " << std::left << std::setw(6)
              << (ctx.inverter_powered ? "\033[32mON\033[0m" : "\033[31mOFF\033[0m") << " │ \033[1mTemp:\033[0m "
              << std::fixed << std::setprecision(1) << ctx.inverter_temp_celsius << " °C │\n";
    std::cout << "  │ \033[1mRPM:\033[0m   " << std::left << std::setw(15) << ctx.current_rpm
              << " │ \033[1mPID:\033[0m      " << std::left << std::setw(6)
              << (ctx.pid_engaged ? "\033[32mACTIVE\033[0m" : "\033[33mIDLE\033[0m") << " │ \033[1mFault:\033[0m "
              << (ctx.fault_active ? "\033[31mTRIPPED\033[0m" : "\033[32mCLEAR\033[0m") << "  │\n";
    std::cout << "  └─────────────────────────────────────────────────────────────┘\n";
}

}  // namespace

int main() {
    print_header("fsmc Automotive ECU: Asynchronous BLDC Motor Controller");

    fsm_generated::MotorHardwareContext hw_ctx;
    hw_ctx.target_rpm = 4500;
    hw_ctx.inverter_temp_celsius = 34.5F;

    // Instantiate thread-safe FSM with asynchronous worker thread
    fsm_generated::ThreadSafeMotorFSM async_fsm(hw_ctx);

    // Attach live telemetry observer
    async_fsm.set_observer([](const fsm::transition_info& info) {
        std::cout << "\033[1;34m[TELEMETRY OBSERVER]\033[0m " << info.source << " --(\033[1m" << info.event
                  << "\033[0m)--> " << info.target << (info.is_internal() ? " \033[36m[INTERNAL]\033[0m" : "") << "\n";
    });

    // Start background worker thread
    async_fsm.start_worker();
    std::cout << "\033[32m[INIT]\033[0m Background worker thread running. State: " << async_fsm.current_state_name()
              << "\n\n";

    // ------------------------------------------------------------------------
    // Scenario 1: Nominal Acceleration & Cruising Speed
    // ------------------------------------------------------------------------
    print_header("SCENARIO 1: Nominal Acceleration & Closed-Loop Speed Control");
    print_telemetry_hud(async_fsm.context(), async_fsm.current_state_name());

    std::cout << "\n--> [App] Dispatching StartCmd (Target: 4500 RPM)...\n";
    async_fsm.post(fsm_generated::StartCmd{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));

    std::cout << "\n--> [App] Simulating speed acquisition ramp...\n";
    async_fsm.post(fsm_generated::SpeedReachedEvent{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));

    // ------------------------------------------------------------------------
    // Scenario 2: High-Frequency Hardware ISR via Lock-Free Ring Buffer
    // ------------------------------------------------------------------------
    print_header("SCENARIO 2: Zero-Overhead Hardware Sensor ISR Ticks");
    fsm::spsc_ring_buffer<fsm_generated::SpeedSensorTick, 128> isr_queue;

    // Simulate 4 interrupt service routine pulses injected into lock-free SPSC queue
    for (int i = 0; i < 4; ++i) {
        isr_queue.push(fsm_generated::SpeedSensorTick{});
    }

    // Drain ISR queue into async FSM worker
    fsm_generated::SpeedSensorTick tick;
    while (isr_queue.pop(tick)) {
        async_fsm.post(tick);
    }
    std::this_thread::sleep_for(std::chrono::milliseconds(40));

    // ------------------------------------------------------------------------
    // Scenario 3: Regenerative Braking & Controlled Stop
    // ------------------------------------------------------------------------
    print_header("SCENARIO 3: Controlled Deceleration & Regenerative Braking");
    std::cout << "\n--> [App] Dispatching StopCmd...\n";
    async_fsm.post(fsm_generated::StopCmd{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));

    std::cout << "\n--> [App] Rotor stopped...\n";
    async_fsm.post(fsm_generated::StoppedEvent{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));
    print_telemetry_hud(async_fsm.context(), async_fsm.current_state_name());

    // ------------------------------------------------------------------------
    // Scenario 4: Hardware Fault Injection & Safety Interlock Recovery
    // ------------------------------------------------------------------------
    print_header("SCENARIO 4: Overcurrent Fault Trip & Thermal Recovery Interlock");
    std::cout << "\n--> [App] Restarting motor...\n";
    async_fsm.post(fsm_generated::StartCmd{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));

    std::cout << "\n--> [App] INJECTING HARDWARE FAULT: 150A Phase Overcurrent Spike!\n";
    async_fsm.post(fsm_generated::OvercurrentEvent{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));
    print_telemetry_hud(async_fsm.context(), async_fsm.current_state_name());

    std::cout << "\n--> [App] Attempting Reset while Inverter Overheated (85°C)...\n";
    async_fsm.context().inverter_temp_celsius = 85.0F;
    async_fsm.post(fsm_generated::ResetFaultCmd{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));
    std::cout << "  (Reset correctly REJECTED by IsThermalSafeGuard! State remains: " << async_fsm.current_state_name()
              << ")\n";

    std::cout << "\n--> [App] Inverter cooled down to 42°C -> Retrying Reset...\n";
    async_fsm.context().inverter_temp_celsius = 42.0F;
    async_fsm.post(fsm_generated::ResetFaultCmd{});
    std::this_thread::sleep_for(std::chrono::milliseconds(40));
    print_telemetry_hud(async_fsm.context(), async_fsm.current_state_name());

    // Clean shutdown
    async_fsm.stop_worker();
    std::cout << "\n\033[32m[SHUTDOWN]\033[0m Worker thread stopped gracefully. All safety guarantees verified!\n";
    return 0;
}
