#include <chrono>
#include <iostream>
#include <thread>

// Include generated standalone FSM (generated by fsmc_target_sources during CMake build)
#include "motor_fsm.hpp"

// User context containing device hardware state
namespace fsm_generated {
struct MotorHardwareContext {
    int target_rpm = 0;
    int current_rpm = 0;
    float inverter_temp_celsius = 25.0f;
    bool inverter_powered = false;
    bool pid_engaged = false;
    bool brake_engaged = false;
    bool fault_active = false;
};
}  // namespace fsm_generated

// Implement user guards
struct fsm_generated::HasValidRpmGuard {
    [[nodiscard]] bool operator()(const fsm_generated::StartCmd& /*evt*/, const auto& /*src*/,
                                  const MotorHardwareContext& ctx) const noexcept {
        return ctx.target_rpm > 0 && ctx.target_rpm <= 8000;
    }
};

struct fsm_generated::IsThermalSafeGuard {
    [[nodiscard]] bool operator()(const fsm_generated::ResetFaultCmd& /*evt*/, const auto& /*src*/,
                                  const MotorHardwareContext& ctx) const noexcept {
        return ctx.inverter_temp_celsius < 75.0f;
    }
};

// Implement user actions
struct fsm_generated::PowerOnInverterAction {
    void operator()(const fsm_generated::StartCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.inverter_powered = true;
        std::cout << "  [HW Action] Inverter powered ON. Target RPM: " << ctx.target_rpm << "\n";
    }
};

struct fsm_generated::EngageSpeedPidAction {
    void operator()(const fsm_generated::SpeedReachedEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.pid_engaged = true;
        std::cout << "  [HW Action] Speed PID engaged at " << ctx.current_rpm << " RPM.\n";
    }
};

struct fsm_generated::UpdateOdometryAction {
    void operator()(const fsm_generated::SpeedSensorTick& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& /*ctx*/) const {
        std::cout << "  [HW Action] Odometry tick processed (internal transition).\n";
    }
};

struct fsm_generated::ApplyRegenerativeBrakeAction {
    void operator()(const fsm_generated::StopCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.pid_engaged = false;
        ctx.brake_engaged = true;
        std::cout << "  [HW Action] Regenerative brake applied.\n";
    }
};

struct fsm_generated::DisengageInverterAction {
    void operator()(const fsm_generated::StoppedEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.brake_engaged = false;
        ctx.inverter_powered = false;
        ctx.current_rpm = 0;
        std::cout << "  [HW Action] Inverter powered OFF. Motor halted safely.\n";
    }
};

struct fsm_generated::EmergencyCutoffAction {
    void operator()(const fsm_generated::OvercurrentEvent& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.inverter_powered = false;
        ctx.pid_engaged = false;
        ctx.fault_active = true;
        std::cout << "  [HW Action] EMERGENCY CUTOFF: Hardware tripped into FAULT state!\n";
    }
};

struct fsm_generated::ClearFaultFlagsAction {
    void operator()(const fsm_generated::ResetFaultCmd& /*evt*/, auto& /*src*/, auto& /*dst*/,
                    MotorHardwareContext& ctx) const {
        ctx.fault_active = false;
        std::cout << "  [HW Action] Fault flags cleared. Ready for restart.\n";
    }
};

int main() {
    std::cout << "=======================================================\n";
    std::cout << "  fsmc Showcase: Asynchronous Thread-Safe Motor FSM   \n";
    std::cout << "=======================================================\n\n";

    fsm_generated::MotorHardwareContext hw_ctx;
    hw_ctx.target_rpm = 3000;

    // 1. Instantiate the thread-safe state machine
    fsm_generated::ThreadSafeMotorFSM async_fsm(hw_ctx);

    std::cout << "[Init] Starting background async event worker...\n";
    async_fsm.start_worker();

    std::cout << "[State] Initial: " << async_fsm.current_state_name() << "\n\n";

    // 2. Post events from main thread asynchronously
    std::cout << "[Thread: Main] Posting StartCmd...\n";
    async_fsm.post(fsm_generated::StartCmd{});

    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    hw_ctx.current_rpm = 3000;

    std::cout << "\n[Thread: Sensor] Posting SpeedReachedEvent...\n";
    async_fsm.post(fsm_generated::SpeedReachedEvent{});

    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    std::cout << "\n[Thread: Sensor] Posting SpeedSensorTick (internal transition)...\n";
    async_fsm.post(fsm_generated::SpeedSensorTick{});

    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    std::cout << "\n[Thread: Operator] Posting StopCmd...\n";
    async_fsm.post(fsm_generated::StopCmd{});

    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    std::cout << "\n[Thread: Sensor] Posting StoppedEvent...\n";
    async_fsm.post(fsm_generated::StoppedEvent{});

    std::this_thread::sleep_for(std::chrono::milliseconds(50));
    std::cout << "\n[State] Final state: " << async_fsm.current_state_name() << "\n";

    // 3. Clean shutdown
    std::cout << "\n[Shutdown] Stopping async worker...\n";
    async_fsm.stop_worker();

    std::cout << "=======================================================\n";
    std::cout << "  [PASS] Async Motor Controller executed successfully! \n";
    std::cout << "=======================================================\n";
    return 0;
}
