/**
 * fsmc Playground — C++ Code Generator
 * Generates idiomatic C++17/20 FSM code from a canonical model.
 * Falls back to this JS implementation when WASM is not available.
 */

/**
 * Generate C++ source from a canonical model.
 * @param {object} model
 * @param {boolean} isCpp20
 * @returns {string}
 */
export function generateCpp(model, isCpp20 = true) {
  let rawName = model.name;
  if (!rawName || rawName === "GeneratedFSM" || rawName === "StateMachine") {
    rawName = model.initialState || "IndustrialController";
  }
  const fsmName = rawName.endsWith("FSM") ? rawName : rawName + "FSM";

  let code = `// ============================================================================\n`;
  code += `// Generated by fsmc v0.5.0 (The Universal State Machine Compiler)\n`;
  code += `// Target: C++${isCpp20 ? '20' : '17'} (Standalone 0-Deps)\n`;
  code += `// ============================================================================\n#pragma once\n\n`;
  code += `#include <iostream>\n#include <string_view>\n\n`;
  code += `namespace fsm_generated {\n\n`;

  // Events
  code += `// --- Event Trigger Definitions ---\n`;
  for (const evt of model.events) code += `struct ${evt} {};\n`;
  code += `\n`;

  // States enum
  code += `// --- State Enumeration ---\n`;
  code += `enum class State {\n`;
  for (const st of model.states) code += `    ${st},\n`;
  code += `};\n\n`;

  // Collect guards & actions
  const guards  = new Set();
  const actions = new Set();
  for (const t of model.transitions) {
    if (t.guard) {
      for (const tok of (t.guard.match(/[A-Za-z0-9_]+/g) || [])) {
        if (!["true","false","and","or","not"].includes(tok)) guards.add(tok);
      }
    }
    if (t.action) {
      for (const tok of (t.action.match(/[A-Za-z0-9_]+/g) || [])) actions.add(tok);
    }
  }

  // FSM class
  code += `// --- Finite State Machine Implementation ---\n`;
  code += `class ${fsmName} {\npublic:\n`;
  code += `    constexpr ${fsmName}() noexcept : current_state_(State::${model.initialState}) {}\n`;
  code += `    virtual ~${fsmName}() = default;\n\n`;
  code += `    [[nodiscard]] constexpr State current_state() const noexcept { return current_state_; }\n`;
  code += `    [[nodiscard]] std::string_view current_state_name() const noexcept {\n`;
  code += `        switch (current_state_) {\n`;
  for (const st of model.states) code += `            case State::${st}: return "${st}";\n`;
  code += `        }\n        return "Unknown";\n    }\n\n`;

  if (guards.size > 0) {
    code += `    // --- Guard Predicates (Override in derived class) ---\n`;
    for (const g of guards) code += `    [[nodiscard]] virtual bool check_${g}() const noexcept { return true; }\n`;
    code += `\n`;
  }

  if (actions.size > 0) {
    code += `    // --- Action Handlers (Override in derived class) ---\n`;
    for (const a of actions) code += `    virtual void on_${a}() noexcept {}\n`;
    code += `\n`;
  }

  code += `    // --- Event Dispatchers ---\n`;
  for (const evt of model.events) {
    code += `    bool dispatch(const ${evt}&) noexcept {\n`;
    code += `        switch (current_state_) {\n`;
    for (const t of model.transitions.filter(t => t.event === evt)) {
      code += `            case State::${t.source}: {\n`;
      if (t.guard) {
        let gCond = t.guard;
        for (const tok of (t.guard.match(/[A-Za-z0-9_]+/g) || [])) {
          if (guards.has(tok)) gCond = gCond.replace(new RegExp(`\\b${tok}\\b`, 'g'), `check_${tok}()`);
        }
        code += `                if (!(${gCond})) return false;\n`;
      }
      if (t.action) {
        for (const tok of (t.action.match(/[A-Za-z0-9_]+/g) || [])) {
          if (actions.has(tok)) code += `                on_${tok}();\n`;
        }
      }
      if (!t.is_internal && t.target) code += `                current_state_ = State::${t.target};\n`;
      code += `                return true;\n            }\n`;
    }
    code += `            default: return false;\n        }\n    }\n\n`;
  }

  code += `private:\n    State current_state_;\n};\n\n} // namespace fsm_generated\n`;
  return code;
}
