#pragma once

// ============================================================================
// Auto-generated by scripts/generate_standalone_runtime.py
// DO NOT EDIT DIRECTLY. Edit files in include/fsm/runtime/cpp/ instead.
// Target: C++20 Standalone Runtime Emitter
// ============================================================================

#include <ostream>

#include "fsm/backend/cpp/cpp_options.hpp"

namespace fsm::codegen {

class Cpp20StandaloneRuntime {
  public:
    static void emit(std::ostream& out, const GeneratorOptions& opts) {
        out << R"raw_fsm_runtime(
// Core System Includes
#include <chrono>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <functional>
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>
#include <vector>
)raw_fsm_runtime";

        if (opts.thread_safe) {
            out << R"raw_fsm_runtime(
// Thread-Safe System Includes
#include <array>
#include <atomic>
#include <cassert>
#include <condition_variable>
#include <exception>
#include <future>
#include <memory>
#include <mutex>
#include <new>
#include <optional>
#include <queue>
#include <string>
#include <thread>
)raw_fsm_runtime";
        }

        out << R"raw_fsm_runtime(

// ============================================================================
// Core Runtime (C++20)
// ============================================================================
// --- Begin: traits/type_list.hpp ---
namespace fsm {

// ============================================================================
// Type List Utilities
// ============================================================================

template <typename... Ts>
struct type_list {
    static constexpr std::size_t size = sizeof...(Ts);
};

// Concatenate type_lists
template <typename List1, typename List2>
struct type_list_cat;

template <typename... Ts1, typename... Ts2>
struct type_list_cat<type_list<Ts1...>, type_list<Ts2...>> {
    using type = type_list<Ts1..., Ts2...>;
};

template <typename List1, typename List2>
using type_list_cat_t = typename type_list_cat<List1, List2>::type;

// Check if type_list contains T
template <typename T, typename List>
struct type_list_contains;

template <typename T>
struct type_list_contains<T, type_list<>> : std::false_type {};

template <typename T, typename Head, typename... Tail>
struct type_list_contains<T, type_list<Head, Tail...>>
    : std::conditional_t<std::is_same_v<T, Head>, std::true_type, type_list_contains<T, type_list<Tail...>>> {};

template <typename T, typename List>
inline constexpr bool type_list_contains_v = type_list_contains<T, List>::value;

// Append type to list if not already present
template <typename List, typename T>
struct type_list_append_unique;

template <typename... Ts, typename T>
struct type_list_append_unique<type_list<Ts...>, T> {
    using type = std::conditional_t<type_list_contains_v<T, type_list<Ts...>>, type_list<Ts...>, type_list<Ts..., T>>;
};

// Make unique type_list while preserving first-occurrence order
template <typename List, typename Result = type_list<>>
struct type_list_unique;

template <typename Result>
struct type_list_unique<type_list<>, Result> {
    using type = Result;
};

template <typename Head, typename... Tail, typename Result>
struct type_list_unique<type_list<Head, Tail...>, Result> {
  private:
    using next_result = typename type_list_append_unique<Result, Head>::type;

  public:
    using type = typename type_list_unique<type_list<Tail...>, next_result>::type;
};

template <typename List>
using type_list_unique_t = typename type_list_unique<List>::type;

// Convert type_list to std::variant
template <typename List>
struct to_variant;

template <typename... Ts>
struct to_variant<type_list<Ts...>> {
    using type = std::variant<Ts...>;
};

template <typename List>
using to_variant_t = typename to_variant<List>::type;

// Convert type_list to std::tuple
template <typename List>
struct to_tuple;

template <typename... Ts>
struct to_tuple<type_list<Ts...>> {
    using type = std::tuple<Ts...>;
};

template <typename List>
using to_tuple_t = typename to_tuple<List>::type;

// First element of type_list
template <typename List>
struct type_list_front;

template <typename Head, typename... Tail>
struct type_list_front<type_list<Head, Tail...>> {
    using type = Head;
};

template <typename List>
using type_list_front_t = typename type_list_front<List>::type;

}  // namespace fsm

// --- End: traits/type_list.hpp ---

// --- Begin: traits/dispatch_result.hpp ---
namespace fsm {

// Result of an event dispatch operation
enum class dispatch_status : std::uint8_t {
    success,         // Transition successfully executed
    deferred,        // Event was deferred by the active state
    guard_rejected,  // Transition matched event, but all candidate guard conditions evaluated to false
    unhandled        // No transition defined for (current_state, event)
};

inline constexpr std::string_view to_string(dispatch_status s) noexcept {
    switch (s) {
        case dispatch_status::success:
            return "success";
        case dispatch_status::deferred:
            return "deferred";
        case dispatch_status::guard_rejected:
            return "guard_rejected";
        case dispatch_status::unhandled:
            return "unhandled";
    }
    return "unknown";
}

struct dispatch_result {
    dispatch_status status = dispatch_status::unhandled;

    constexpr dispatch_result() noexcept = default;
    constexpr dispatch_result(dispatch_status s) noexcept : status(s) {}

    [[nodiscard]] constexpr bool is_success() const noexcept { return status == dispatch_status::success; }
    [[nodiscard]] constexpr bool is_deferred() const noexcept { return status == dispatch_status::deferred; }
    [[nodiscard]] constexpr bool is_guard_rejected() const noexcept {
        return status == dispatch_status::guard_rejected;
    }
    [[nodiscard]] constexpr bool is_unhandled() const noexcept { return status == dispatch_status::unhandled; }
    [[nodiscard]] constexpr bool is_ok() const noexcept { return is_success() || is_deferred(); }

    [[nodiscard]] constexpr explicit operator bool() const noexcept { return is_ok(); }
    constexpr bool operator==(const dispatch_result& other) const noexcept { return status == other.status; }
    constexpr bool operator==(dispatch_status other_status) const noexcept { return status == other_status; }
    constexpr bool operator!=(const dispatch_result& other) const noexcept { return status != other.status; }
    constexpr bool operator!=(dispatch_status other_status) const noexcept { return status != other_status; }

    [[nodiscard]] constexpr std::string_view to_string() const noexcept { return fsm::to_string(status); }
};

enum class transition_kind : std::uint8_t { external, internal };

inline constexpr std::string_view to_string(transition_kind k) noexcept {
    switch (k) {
        case transition_kind::external:
            return "external";
        case transition_kind::internal:
            return "internal";
    }
    return "external";
}

// Information about a transition or dispatch attempt passed to observers
struct transition_info {
    std::string_view source;
    std::string_view target;
    std::string_view event;
    dispatch_status status = dispatch_status::success;
    transition_kind kind = transition_kind::external;

    [[nodiscard]] constexpr bool is_internal() const noexcept { return kind == transition_kind::internal; }
    [[nodiscard]] constexpr bool is_external() const noexcept { return kind == transition_kind::external; }
    [[nodiscard]] constexpr bool is_success() const noexcept { return status == dispatch_status::success; }
    [[nodiscard]] constexpr bool is_deferred() const noexcept { return status == dispatch_status::deferred; }
    [[nodiscard]] constexpr bool is_guard_rejected() const noexcept {
        return status == dispatch_status::guard_rejected;
    }
    [[nodiscard]] constexpr bool is_unhandled() const noexcept { return status == dispatch_status::unhandled; }
};

}  // namespace fsm

// --- End: traits/dispatch_result.hpp ---

// --- Begin: traits/reflection.hpp ---
namespace fsm {

// ----------------------------------------------------------------------------
// Compile-time Type Name & State Name Reflection
// ----------------------------------------------------------------------------

template <typename T>
constexpr std::string_view get_type_name() {
#if defined(__clang__) || defined(__GNUC__)
    std::string_view name = __PRETTY_FUNCTION__;
    auto start = name.find("T = ");
    if (start != std::string_view::npos) {
        start += 4;
        auto end = name.find_first_of(";]", start);
        if (end != std::string_view::npos) {
            auto full_type = name.substr(start, end - start);
            auto last_scope = full_type.rfind("::");
            if (last_scope != std::string_view::npos) {
                return full_type.substr(last_scope + 2);
            }
            return full_type;
        }
    }
#elif defined(_MSC_VER)
    std::string_view name = __FUNCSIG__;
    auto start = name.find("get_type_name<");
    if (start != std::string_view::npos) {
        start += 14;
        auto end = name.find(">(void)", start);
        if (end == std::string_view::npos) {
            end = name.rfind('>');
        }
        if (end != std::string_view::npos && end > start) {
            auto full_type = name.substr(start, end - start);
            while (full_type.rfind("struct ", 0) == 0) {
                full_type.remove_prefix(7);
            }
            while (full_type.rfind("class ", 0) == 0) {
                full_type.remove_prefix(6);
            }
            while (full_type.rfind("enum ", 0) == 0) {
                full_type.remove_prefix(5);
            }
            auto last_scope = full_type.rfind("::");
            if (last_scope != std::string_view::npos) {
                return full_type.substr(last_scope + 2);
            }
            return full_type;
        }
    }
#endif
    return "UnknownState";
}

namespace detail {

template <typename State, typename = void>
struct has_custom_name_method : std::false_type {};

template <typename State>
struct has_custom_name_method<State, std::void_t<decltype(std::declval<const State&>().name())>> : std::true_type {};

template <typename State, typename = void>
struct has_custom_name_static : std::false_type {};

template <typename State>
struct has_custom_name_static<State, std::void_t<decltype(State::name)>> : std::true_type {};

template <typename T, typename = void>
struct has_name : std::false_type {};

template <typename T>
struct has_name<T, std::void_t<decltype(T::name)>> : std::true_type {};

template <typename State, typename = void>
struct has_parent_name : std::false_type {};

template <typename State>
struct has_parent_name<State, std::void_t<decltype(State::parent)>> : std::true_type {};

}  // namespace detail

template <typename State>
constexpr std::string_view get_state_name(const State& state) {
    if constexpr (detail::has_custom_name_method<State>::value) {
        return state.name();
    } else if constexpr (detail::has_custom_name_static<State>::value) {
        return State::name;
    } else {
        return get_type_name<State>();
    }
}

template <typename Event>
constexpr std::string_view get_event_name(const Event& event) {
    if constexpr (detail::has_custom_name_method<Event>::value) {
        return event.name();
    } else if constexpr (detail::has_custom_name_static<Event>::value) {
        return Event::name;
    } else {
        return get_type_name<Event>();
    }
}

template <typename Event>
constexpr std::string_view event_name() noexcept {
    if constexpr (detail::has_name<std::decay_t<Event>>::value) {
        return std::decay_t<Event>::name;
    } else {
        return "AnonymousEvent";
    }
}

template <typename State>
constexpr std::string_view get_parent_name() noexcept {
    if constexpr (detail::has_parent_name<State>::value) {
        return State::parent;
    } else {
        return "";
    }
}

}  // namespace fsm

// --- End: traits/reflection.hpp ---

// --- Begin: traits/hook_traits.hpp ---
namespace fsm {

// ============================================================================
// Detection Idiom & Hook Invocations (on_enter, on_exit, guard, action, context)
// ============================================================================

namespace detail {

// on_enter(event, ctx)
template <typename State, typename Event, typename Context, typename = void>
struct has_on_enter_event_ctx : std::false_type {};

template <typename State, typename Event, typename Context>
struct has_on_enter_event_ctx<
    State, Event, Context,
    std::void_t<decltype(std::declval<State&>().on_enter(std::declval<const Event&>(), std::declval<Context&>()))>>
    : std::true_type {};

// on_enter(ctx)
template <typename State, typename Context, typename = void>
struct has_on_enter_ctx : std::false_type {};

template <typename State, typename Context>
struct has_on_enter_ctx<State, Context,
                        std::void_t<decltype(std::declval<State&>().on_enter(std::declval<Context&>()))>>
    : std::true_type {};

// on_enter(event)
template <typename State, typename Event, typename = void>
struct has_on_enter_event : std::false_type {};

template <typename State, typename Event>
struct has_on_enter_event<State, Event,
                          std::void_t<decltype(std::declval<State&>().on_enter(std::declval<const Event&>()))>>
    : std::true_type {};

// on_enter()
template <typename State, typename = void>
struct has_on_enter_void : std::false_type {};

template <typename State>
struct has_on_enter_void<State, std::void_t<decltype(std::declval<State&>().on_enter())>> : std::true_type {};

// on_exit(event, ctx)
template <typename State, typename Event, typename Context, typename = void>
struct has_on_exit_event_ctx : std::false_type {};

template <typename State, typename Event, typename Context>
struct has_on_exit_event_ctx<
    State, Event, Context,
    std::void_t<decltype(std::declval<State&>().on_exit(std::declval<const Event&>(), std::declval<Context&>()))>>
    : std::true_type {};

// on_exit(ctx)
template <typename State, typename Context, typename = void>
struct has_on_exit_ctx : std::false_type {};

template <typename State, typename Context>
struct has_on_exit_ctx<State, Context, std::void_t<decltype(std::declval<State&>().on_exit(std::declval<Context&>()))>>
    : std::true_type {};

// on_exit(event)
template <typename State, typename Event, typename = void>
struct has_on_exit_event : std::false_type {};

template <typename State, typename Event>
struct has_on_exit_event<State, Event,
                         std::void_t<decltype(std::declval<State&>().on_exit(std::declval<const Event&>()))>>
    : std::true_type {};

// on_exit()
template <typename State, typename = void>
struct has_on_exit_void : std::false_type {};

template <typename State>
struct has_on_exit_void<State, std::void_t<decltype(std::declval<State&>().on_exit())>> : std::true_type {};

}  // namespace detail

// ----------------------------------------------------------------------------
// Safe invocation of on_enter hook (with context and event)
// ----------------------------------------------------------------------------
template <typename State, typename Event, typename Context>
constexpr void call_on_enter(State& state, const Event& event, Context& ctx) {
    if constexpr (detail::has_on_enter_event_ctx<State, Event, Context>::value) {
        state.on_enter(event, ctx);
    } else if constexpr (detail::has_on_enter_ctx<State, Context>::value) {
        state.on_enter(ctx);
    } else if constexpr (detail::has_on_enter_event<State, Event>::value) {
        state.on_enter(event);
    } else if constexpr (detail::has_on_enter_void<State>::value) {
        state.on_enter();
    }
}

// Overload for on_enter without event (initial state enter)
template <typename State, typename Context>
constexpr void call_on_enter(State& state, Context& ctx) {
    if constexpr (detail::has_on_enter_ctx<State, Context>::value) {
        state.on_enter(ctx);
    } else if constexpr (detail::has_on_enter_void<State>::value) {
        state.on_enter();
    }
}

// ----------------------------------------------------------------------------
// Safe invocation of on_exit hook
// ----------------------------------------------------------------------------
template <typename State, typename Event, typename Context>
constexpr void call_on_exit(State& state, const Event& event, Context& ctx) {
    if constexpr (detail::has_on_exit_event_ctx<State, Event, Context>::value) {
        state.on_exit(event, ctx);
    } else if constexpr (detail::has_on_exit_ctx<State, Context>::value) {
        state.on_exit(ctx);
    } else if constexpr (detail::has_on_exit_event<State, Event>::value) {
        state.on_exit(event);
    } else if constexpr (detail::has_on_exit_void<State>::value) {
        state.on_exit();
    }
}

// ----------------------------------------------------------------------------
// Safe invocation of guard
// ----------------------------------------------------------------------------
template <typename Guard, typename Event, typename SrcState, typename Context>
constexpr bool call_guard(const Guard& guard, const Event& event, const SrcState& src, Context& ctx) {
    if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, const SrcState&, Context&>) {
        return guard(event, src, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, Context&>) {
        return guard(event, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const SrcState&, Context&>) {
        return guard(src, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, Context&>) {
        return guard(ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, const SrcState&>) {
        return guard(event, src);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&>) {
        return guard(event);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const SrcState&>) {
        return guard(src);
    } else if constexpr (std::is_invocable_r_v<bool, Guard>) {
        return guard();
    } else {
        return true;
    }
}

template <typename Guard, typename Event, typename SrcState, typename Context, typename Fsm>
constexpr bool call_guard(const Guard& guard, const Event& event, const SrcState& src, Context& ctx, const Fsm& fsm) {
    if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, const SrcState&, Context&, const Fsm&>) {
        return guard(event, src, ctx, fsm);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, const SrcState&, Context&>) {
        return guard(event, src, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, Context&>) {
        return guard(event, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const SrcState&, Context&>) {
        return guard(src, ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, Context&>) {
        return guard(ctx);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Event&, const SrcState&, const Fsm&>) {
        return guard(event, src, fsm);
    } else if constexpr (std::is_invocable_r_v<bool, Guard, const Fsm&>) {
        return guard(fsm);
    } else {
        return call_guard(guard, event, src, ctx);
    }
}

// ----------------------------------------------------------------------------
// Safe invocation of action
// ----------------------------------------------------------------------------
template <typename Action, typename Event, typename SrcState, typename DstState, typename Context>
constexpr void call_action(Action& action, const Event& event, SrcState& src, DstState& dst, Context& ctx) {
    if constexpr (std::is_invocable_v<Action, const Event&, SrcState&, DstState&, Context&>) {
        action(event, src, dst, ctx);
    } else if constexpr (std::is_invocable_v<Action, const Event&, SrcState&, Context&>) {
        action(event, src, ctx);
    } else if constexpr (std::is_invocable_v<Action, const Event&, Context&>) {
        action(event, ctx);
    } else if constexpr (std::is_invocable_v<Action, Context&>) {
        action(ctx);
    } else if constexpr (std::is_invocable_v<Action, const Event&, SrcState&, DstState&>) {
        action(event, src, dst);
    } else if constexpr (std::is_invocable_v<Action, const Event&, SrcState&>) {
        action(event, src);
    } else if constexpr (std::is_invocable_v<Action, const Event&>) {
        action(event);
    } else if constexpr (std::is_invocable_v<Action>) {
        action();
    }
}

}  // namespace fsm

// --- End: traits/hook_traits.hpp ---

// --- Begin: traits/observer_traits.hpp ---
namespace fsm {

// ============================================================================
// Zero-Overhead Observer Policies & Storage Utilities
// ============================================================================

// Compile-time no-op observer policy (occupies 0 bytes with [[no_unique_address]])
struct no_observer {
    template <typename Info>
    constexpr void operator()(const Info&) const noexcept {}
};

// Dynamic observer policy for runtime lambda / function registration
struct dynamic_observer {
    using callback_type = std::function<void(const transition_info&)>;
    callback_type callback{};

    constexpr dynamic_observer() noexcept = default;
    dynamic_observer(callback_type cb) : callback(std::move(cb)) {}

    template <typename F, typename = std::enable_if_t<!std::is_same_v<std::decay_t<F>, dynamic_observer> &&
                                                      !std::is_same_v<std::decay_t<F>, callback_type>>>
    dynamic_observer(F&& cb) : callback(std::forward<F>(cb)) {}

    void operator()(const transition_info& info) const {
        if (callback) {
            callback(info);
        }
    }
};

template <typename T>
struct is_dynamic_observer : std::false_type {};

template <>
struct is_dynamic_observer<dynamic_observer> : std::true_type {};

template <>
struct is_dynamic_observer<std::function<void(const transition_info&)>> : std::true_type {};

template <typename T>
inline constexpr bool is_dynamic_observer_v = is_dynamic_observer<T>::value;

// Empty tag type for non-allocated optional sub-objects
struct empty_storage {};

namespace detail {

template <typename State, typename = void>
struct has_deferred_events : std::false_type {};

template <typename State>
struct has_deferred_events<State, std::void_t<typename State::deferred_events>> : std::true_type {};

template <typename Event, typename List>
struct type_list_contains_event : std::false_type {};

template <typename Event, typename... Ts>
struct type_list_contains_event<Event, type_list<Ts...>> : std::disjunction<std::is_same<Event, Ts>...> {};

template <typename Event, typename... Ts>
struct type_list_contains_event<Event, std::tuple<Ts...>> : std::disjunction<std::is_same<Event, Ts>...> {};

}  // namespace detail

template <typename State>
inline constexpr bool has_deferred_events_v = detail::has_deferred_events<State>::value;

template <typename State, typename Event>
inline constexpr bool is_deferred_event_v = []() constexpr {
    if constexpr (has_deferred_events_v<State>) {
        return detail::type_list_contains_event<std::decay_t<Event>, typename State::deferred_events>::value;
    } else {
        return false;
    }
}();

// Introspection for History & Deferred events across unique state list
template <typename StateList>
struct any_state_has_history : std::false_type {};

template <typename... States>
struct any_state_has_history<type_list<States...>> : std::disjunction<detail::has_parent_name<States>...> {};

template <typename StateList>
struct any_state_has_deferred : std::false_type {};

template <typename... States>
struct any_state_has_deferred<type_list<States...>> : std::disjunction<detail::has_deferred_events<States>...> {};

}  // namespace fsm

// --- End: traits/observer_traits.hpp ---

// --- Begin: traits/concepts.hpp ---
#if __cplusplus >= 202002L
#endif

namespace fsm {

// Default empty context tag
struct no_context {};

#if __cplusplus >= 202002L
template <typename GuardType, typename EventType, typename StateType, typename ContextType>
concept Guard =
    requires(const GuardType& guard, const EventType& event, const StateType& state, const ContextType& context) {
        { guard(event, state, context) } -> std::convertible_to<bool>;
    } || requires(const GuardType& guard, const EventType& event, const StateType& state) {
        { guard(event, state) } -> std::convertible_to<bool>;
    } || requires(const GuardType& guard, const EventType& event) {
        { guard(event) } -> std::convertible_to<bool>;
    } || requires(const GuardType& guard) {
        { guard() } -> std::convertible_to<bool>;
    };

template <typename ActionType, typename EventType, typename SrcStateType, typename DstStateType, typename ContextType>
concept Action =
    requires(const ActionType& action, const EventType& event, SrcStateType& src_state, DstStateType& dst_state,
             ContextType& context) { action(event, src_state, dst_state, context); } ||
    requires(const ActionType& action, const EventType& event, SrcStateType& src_state, DstStateType& dst_state) {
        action(event, src_state, dst_state);
    } ||
    requires(const ActionType& action, const EventType& event, DstStateType& dst_state) { action(event, dst_state); } ||
    requires(const ActionType& action, const EventType& event) { action(event); } ||
    requires(const ActionType& action) { action(); };
#endif

}  // namespace fsm

// --- End: traits/concepts.hpp ---

// --- Begin: type_traits.hpp ---

// --- End: type_traits.hpp ---

// --- Begin: transition.hpp ---
namespace fsm {

// Default no-op action
struct no_action {
    constexpr void operator()() const noexcept {}
};

// Default always-true guard
struct no_guard {
    constexpr bool operator()() const noexcept { return true; }
};

// Anonymous / Eventless Transition Trigger Event
struct anonymous_event {};
using completion_event = anonymous_event;

// Timed Transition Event Types
template <typename Duration = std::chrono::milliseconds>
struct after {
    Duration duration{};
    constexpr explicit after(Duration d = Duration{0}) : duration(d) {}
};

template <std::int64_t Milliseconds>
struct after_ms {
    static constexpr std::chrono::milliseconds duration{Milliseconds};
};

// Logical NOT guard combinator
template <typename Guard>
struct not_ {
    constexpr not_() = default;

    template <typename Event, typename SrcState, typename Context, typename... Extra>
    constexpr bool operator()(const Event& evt, const SrcState& src, Context& ctx, const Extra&... extra) const {
        return !call_guard(Guard{}, evt, src, ctx, extra...);
    }
};

// Logical AND guard combinator
template <typename Guard1, typename Guard2, typename... Rest>
struct and_ {
    constexpr and_() = default;

    template <typename Event, typename SrcState, typename Context, typename... Extra>
    constexpr bool operator()(const Event& evt, const SrcState& src, Context& ctx, const Extra&... extra) const {
        if (!call_guard(Guard1{}, evt, src, ctx, extra...)) {
            return false;
        }
        if constexpr (sizeof...(Rest) == 0) {
            return call_guard(Guard2{}, evt, src, ctx, extra...);
        } else {
            return and_<Guard2, Rest...>{}(evt, src, ctx, extra...);
        }
    }
};

// Logical OR guard combinator
template <typename Guard1, typename Guard2, typename... Rest>
struct or_ {
    constexpr or_() = default;

    template <typename Event, typename SrcState, typename Context, typename... Extra>
    constexpr bool operator()(const Event& evt, const SrcState& src, Context& ctx, const Extra&... extra) const {
        if (call_guard(Guard1{}, evt, src, ctx, extra...)) {
            return true;
        }
        if constexpr (sizeof...(Rest) == 0) {
            return call_guard(Guard2{}, evt, src, ctx, extra...);
        } else {
            return or_<Guard2, Rest...>{}(evt, src, ctx, extra...);
        }
    }
};

// History check guard for shallow / deep history transitions
template <typename ParentState, typename SubState>
struct history_is {
    template <typename Event, typename State, typename Context, typename Fsm>
    constexpr bool operator()(const Event& /*evt*/, const State& /*state*/, Context& /*ctx*/, const Fsm& fsm) const {
        return fsm.get_history(ParentState::name) == SubState::name;
    }

    template <typename Event, typename State, typename Context>
    constexpr bool operator()(const Event& /*evt*/, const State& /*state*/, Context& /*ctx*/) const {
        return false;
    }
};

// Single transition specification in compile-time transition table
template <typename SourceState, typename EventType, typename TargetState, typename ActionType = no_action,
          typename GuardType = no_guard>
struct transition {
    using source = SourceState;
    using event = EventType;
    using target = TargetState;
    using action_type = ActionType;
    using guard_type = GuardType;
    static constexpr bool is_internal = false;

    constexpr transition() = default;
};

// Internal transition specification (executes action without exiting/entering state)
template <typename State, typename EventType, typename ActionType = no_action, typename GuardType = no_guard>
struct internal_transition : transition<State, EventType, State, ActionType, GuardType> {
    static constexpr bool is_internal = true;
    constexpr internal_transition() = default;
};

// ============================================================================
// Fluent Transition Builders: row, on, and internal_row
// ============================================================================

// Fluent Transition Builder: row<Src, Event, Dst>::when<Guard>::then<Action>
template <typename SourceState, typename EventType, typename TargetState, typename ActionType = no_action,
          typename GuardType = no_guard>
struct row : transition<SourceState, EventType, TargetState, ActionType, GuardType> {
    using base = transition<SourceState, EventType, TargetState, ActionType, GuardType>;

    constexpr row() = default;

    // Add / override Guard
    template <typename NewGuard>
    using guard = row<SourceState, EventType, TargetState, ActionType, NewGuard>;

    template <typename NewGuard>
    using when = row<SourceState, EventType, TargetState, ActionType, NewGuard>;

    // Add / override Action
    template <typename NewAction>
    using action = row<SourceState, EventType, TargetState, NewAction, GuardType>;

    template <typename NewAction>
    using then = row<SourceState, EventType, TargetState, NewAction, GuardType>;
};

// Fluent Internal Transition Builder: internal_row<State, Event>::when<Guard>::then<Action>
template <typename State, typename EventType, typename ActionType = no_action, typename GuardType = no_guard>
struct internal_row : internal_transition<State, EventType, ActionType, GuardType> {
    using base = internal_transition<State, EventType, ActionType, GuardType>;

    constexpr internal_row() = default;

    template <typename NewGuard>
    using guard = internal_row<State, EventType, ActionType, NewGuard>;

    template <typename NewGuard>
    using when = internal_row<State, EventType, ActionType, NewGuard>;

    template <typename NewAction>
    using action = internal_row<State, EventType, NewAction, GuardType>;

    template <typename NewAction>
    using then = internal_row<State, EventType, NewAction, GuardType>;
};

// Fluent Event-First Builder: on<Event, Source>::to<Target>::when<Guard>::then<Action>
template <typename EventType, typename SourceState>
struct on {
    template <typename TargetState>
    using to = row<SourceState, EventType, TargetState>;
};

// Helper for fluent creation
template <typename SourceState, typename EventType, typename TargetState, typename ActionType = no_action,
          typename GuardType = no_guard>
constexpr auto make_transition(ActionType action = {}, GuardType guard = {}) {
    return transition<SourceState, EventType, TargetState, ActionType, GuardType>{std::move(action), std::move(guard)};
}

}  // namespace fsm

// --- End: transition.hpp ---

// --- Begin: transition_table.hpp ---
namespace fsm {

namespace detail {

// Helper to extract source and target states from a list of transitions
template <typename... Transitions>
struct extract_states {
    using raw_list =
        type_list_cat_t<type_list<typename Transitions::source...>, type_list<typename Transitions::target...>>;
    using unique_list = type_list_unique_t<raw_list>;
};

// Helper to extract unique events from a list of transitions
template <typename... Transitions>
struct extract_events {
    using raw_list = type_list<typename Transitions::event...>;
    using unique_list = type_list_unique_t<raw_list>;
};

}  // namespace detail

// Compile-time transition table
template <typename... Transitions>
struct transition_table {
    using transitions_list = type_list<Transitions...>;
    using states = typename detail::extract_states<Transitions...>::unique_list;
    using events = typename detail::extract_events<Transitions...>::unique_list;

    using state_variant = to_variant_t<states>;
    using event_variant = to_variant_t<events>;
    using initial_state = type_list_front_t<states>;

    static constexpr std::size_t state_count = states::size;
    static constexpr std::size_t transition_count = sizeof...(Transitions);
    static constexpr std::size_t event_count = events::size;

    template <typename S>
    static constexpr bool has_state = type_list_contains_v<S, states>;

    template <typename E>
    static constexpr bool has_event = type_list_contains_v<E, events>;

    std::tuple<Transitions...> rows;

    constexpr transition_table() = default;
    constexpr explicit transition_table(Transitions... trs) : rows(std::move(trs)...) {}
    constexpr explicit transition_table(std::tuple<Transitions...> tr_tuple) : rows(std::move(tr_tuple)) {}
};

// Helper function to create transition_table
template <typename... Transitions>
constexpr auto make_transition_table(Transitions&&... trs) {
    return transition_table<std::decay_t<Transitions>...>(std::forward<Transitions>(trs)...);
}

}  // namespace fsm

// --- End: transition_table.hpp ---

// --- Begin: fsm.hpp ---
namespace fsm {

// Core synchronous compile-time Finite State Machine with Context Injection
template <typename Table, typename Context = no_context, typename InitialState = typename Table::initial_state,
          typename Observer = no_observer>
class fsm {
  public:
    using table_type = Table;
    using context_type = Context;
    using state_variant = typename Table::state_variant;
    using initial_state_type = InitialState;
    using observer_type = Observer;

    static constexpr bool has_history = any_state_has_history<typename Table::states>::value;
    static constexpr bool has_deferred = any_state_has_deferred<typename Table::states>::value;
    static constexpr bool has_observer = !std::is_same_v<Observer, no_observer>;

    struct history_entry {
        std::string_view parent;
        std::string_view substate;
    };

    // Static compile-time introspection
    static constexpr std::size_t state_count = Table::state_count;
    static constexpr std::size_t transition_count = Table::transition_count;
    static constexpr std::size_t event_count = Table::event_count;

    template <typename State>
    static constexpr bool has_state = Table::template has_state<State>;

    template <typename Event>
    static constexpr bool has_event = Table::template has_event<Event>;

    // Default constructor (enabled only when Context is no_context)
    template <typename C = Context, typename = std::enable_if_t<std::is_same_v<C, no_context>>>
    constexpr fsm() : current_state_(InitialState{}), table_(), context_(nullptr) {
        enter_initial_state();
    }

    // Constructor with Context reference
    constexpr explicit fsm(Context& ctx, Table table = Table{})
        : current_state_(InitialState{}), table_(std::move(table)), context_(&ctx) {
        enter_initial_state();
    }

    // Constructor with Context reference and specific initial state instance
    constexpr explicit fsm(Context& ctx, InitialState initial, Table table = Table{})
        : current_state_(std::move(initial)), table_(std::move(table)), context_(&ctx) {
        enter_initial_state();
    }

    // Dispatches an event directly (without deferred queue processing)
    template <typename Event>
    dispatch_result dispatch_direct(const Event& event) {
        return std::visit(
            [this, &event](auto& src_state) -> dispatch_result {
                using CurrentSrc = std::decay_t<decltype(src_state)>;
                return this->try_transition_from<CurrentSrc>(
                    src_state, event, std::make_index_sequence<std::tuple_size_v<decltype(this->table_.rows)>>{});
            },
            current_state_);
    }

    // Dispatches an event to the FSM. Returns dispatch_result (evaluates to true if executed or deferred).
    template <typename Event>
    dispatch_result dispatch(const Event& event) {
        dispatch_result res = dispatch_direct(event);

        if (res.is_success()) {
            // Process/replay any deferred events that can now fire in the new state
            process_deferred_queue();
        } else {
            const auto src_name = current_state_name();
            const auto evt_name = get_event_name(event);

            if constexpr (has_deferred) {
                // Check if the current state defers this event
                bool deferred = std::visit(
                    [this, &event](const auto& src_state) -> bool {
                        using CurrentSrc = std::decay_t<decltype(src_state)>;
                        if constexpr (is_deferred_event_v<CurrentSrc, Event>) {
                            this->defer_event(event);
                            return true;
                        } else {
                            return false;
                        }
                    },
                    current_state_);

                if (deferred) {
                    if constexpr (has_observer) {
                        observer_(transition_info{src_name, src_name, evt_name, dispatch_status::deferred,
                                                  transition_kind::external});
                    }
                    return dispatch_result{dispatch_status::deferred};
                }
            }

            if (res.is_guard_rejected()) {
                if constexpr (has_observer) {
                    observer_(transition_info{src_name, src_name, evt_name, dispatch_status::guard_rejected,
                                              transition_kind::external});
                }
            } else if (res.is_unhandled()) {
                if constexpr (has_observer) {
                    observer_(transition_info{src_name, src_name, evt_name, dispatch_status::unhandled,
                                              transition_kind::external});
                }
                std::visit([this, &event](const auto& src_state) { this->on_unhandled_event(event, src_state); },
                           current_state_);
            }
        }

        return res;
    }

    template <typename Event>
    void defer_event(const Event& event) {
        if constexpr (has_deferred) {
            deferred_queue_.push_back([event](fsm& self) -> bool { return self.dispatch_direct(event).is_success(); });
        }
    }

    // Process all deferred events in queue until no more can fire
    template <bool D = has_deferred>
    void process_deferred_queue() {
        if constexpr (D) {
            if (deferred_queue_.empty() || is_replaying_deferred_) {
                return;
            }
            is_replaying_deferred_ = true;

            bool any_handled = true;
            while (any_handled && !deferred_queue_.empty()) {
                any_handled = false;
                for (auto it = deferred_queue_.begin(); it != deferred_queue_.end();) {
                    if ((*it)(*this)) {
                        it = deferred_queue_.erase(it);
                        any_handled = true;
                        // State may have transitioned, re-scan queue
                        break;
                    }
                    ++it;
                }
            }

            is_replaying_deferred_ = false;
        }
    }

    // Deferred events introspection
    template <bool D = has_deferred>
    [[nodiscard]] std::size_t deferred_count() const noexcept {
        if constexpr (D) {
            return deferred_queue_.size();
        } else {
            return 0;
        }
    }

    template <bool D = has_deferred>
    void clear_deferred_events() noexcept {
        if constexpr (D) {
            deferred_queue_.clear();
        }
    }

    // Observer management (available for dynamic_observer or custom functor)
    template <typename Obs = Observer, typename = std::enable_if_t<is_dynamic_observer_v<Obs>>>
    void set_observer(typename Obs::callback_type observer) {
        if constexpr (std::is_same_v<Observer, dynamic_observer>) {
            observer_.callback = std::move(observer);
        } else {
            observer_ = std::move(observer);
        }
    }

    template <typename Obs = Observer, typename = std::enable_if_t<is_dynamic_observer_v<Obs>>>
    void clear_observer() noexcept {
        if constexpr (std::is_same_v<Observer, dynamic_observer>) {
            observer_.callback = nullptr;
        } else {
            observer_ = nullptr;
        }
    }

    // History state management
    template <bool H = has_history>
    void record_history(std::string_view parent, std::string_view substate) {
        if constexpr (H) {
            if (parent.empty() || substate.empty()) {
                return;
            }
            for (auto& entry : history_records_) {
                if (entry.parent == parent) {
                    entry.substate = substate;
                    return;
                }
            }
            history_records_.push_back({parent, substate});
        }
    }

    template <bool H = has_history>
    [[nodiscard]] std::string_view get_history(std::string_view parent) const noexcept {
        if constexpr (H) {
            for (const auto& entry : history_records_) {
                if (entry.parent == parent) {
                    return entry.substate;
                }
            }
        }
        return "";
    }

    // Context management
    void set_context(Context& ctx) noexcept { context_ = &ctx; }

    [[nodiscard]] Context& context() noexcept { return get_ctx(); }

    [[nodiscard]] const Context& context() const noexcept { return get_ctx(); }

    [[nodiscard]] Context* get_context() noexcept { return context_; }

    [[nodiscard]] const Context* get_context() const noexcept { return context_; }

    // Query if the current state is of type State
    template <typename State>
    [[nodiscard]] bool is_in_state() const noexcept {
        return std::holds_alternative<State>(current_state_);
    }

    template <typename State>
    [[nodiscard]] bool is_in() const noexcept {
        return is_in_state<State>();
    }

    // Get pointer to current state if it matches State, nullptr otherwise
    template <typename State>
    [[nodiscard]] const State* get_state() const noexcept {
        return std::get_if<State>(&current_state_);
    }

    template <typename State>
    [[nodiscard]] State* get_state() noexcept {
        return std::get_if<State>(&current_state_);
    }

    // Access the raw variant holding current state
    [[nodiscard]] const state_variant& get_current_state_variant() const noexcept { return current_state_; }

    // Query current state name as string_view
    [[nodiscard]] std::string_view current_state_name() const {
        return std::visit([](const auto& state) -> std::string_view { return ::fsm::get_state_name(state); },
                          current_state_);
    }

  protected:
    template <typename Event, typename State>
    void on_unhandled_event(const Event& /*event*/, const State& /*src*/) {
        // Default: no-op
    }

  private:
    Context& get_ctx() noexcept {
        if constexpr (std::is_same_v<Context, no_context>) {
            return dummy_ctx_;
        } else {
            return *context_;
        }
    }

    [[nodiscard]] const Context& get_ctx() const noexcept {
        if constexpr (std::is_same_v<Context, no_context>) {
            return dummy_ctx_;
        } else {
            return *context_;
        }
    }

    void enter_initial_state() {
        if (auto* state = std::get_if<InitialState>(&current_state_)) {
            call_on_enter(*state, get_ctx());
        }
    }

    template <typename CurrentSrc, typename Event, std::size_t... Indices>
    dispatch_result try_transition_from(CurrentSrc& src_state, const Event& event,
                                        std::index_sequence<Indices...> /*indices*/) {
        bool any_guard_rejected = false;

        auto try_index = [&](auto idx_constant) -> bool {
            constexpr std::size_t Index = decltype(idx_constant)::value;
            using RowType = std::tuple_element_t<Index, decltype(table_.rows)>;
            using TransSrc = typename RowType::source;
            using TransEvt = typename RowType::event;

            if constexpr (std::is_same_v<CurrentSrc, TransSrc> && std::is_same_v<std::decay_t<Event>, TransEvt>) {
                using Guard = typename RowType::guard_type;
                using Action = typename RowType::action_type;
                auto& ctx = get_ctx();

                if (!call_guard(Guard{}, event, src_state, ctx, *this)) {
                    any_guard_rejected = true;
                    return false;
                }

                const auto src_name = get_state_name(src_state);
                const auto evt_name = get_event_name(event);

                if constexpr (RowType::is_internal) {
                    Action act{};
                    call_action(act, event, src_state, src_state, ctx);
                    if constexpr (has_observer) {
                        observer_(transition_info{src_name, src_name, evt_name, dispatch_status::success,
                                                  transition_kind::internal});
                    }
                    return true;
                } else {
                    using TransDst = typename RowType::target;
                    constexpr std::string_view src_parent = get_parent_name<CurrentSrc>();
                    constexpr std::string_view dst_parent = get_parent_name<TransDst>();
                    if constexpr (!src_parent.empty()) {
                        if constexpr (src_parent != dst_parent) {
                            record_history(src_parent, src_name);
                        }
                    }

                    TransDst dst_state{};
                    call_on_exit(src_state, event, ctx);
                    Action act{};
                    call_action(act, event, src_state, dst_state, ctx);
                    current_state_ = std::move(dst_state);
                    call_on_enter(std::get<TransDst>(current_state_), event, ctx);

                    const auto dst_name = get_state_name(std::get<TransDst>(current_state_));
                    if constexpr (has_observer) {
                        observer_(transition_info{src_name, dst_name, evt_name, dispatch_status::success,
                                                  transition_kind::external});
                    }
                    return true;
                }
            }
            return false;
        };

        bool executed = (try_index(std::integral_constant<std::size_t, Indices>{}) || ...);
        if (executed) {
            return dispatch_result{dispatch_status::success};
        }
        if (any_guard_rejected) {
            return dispatch_result{dispatch_status::guard_rejected};
        }
        return dispatch_result{dispatch_status::unhandled};
    }

    using history_storage = std::conditional_t<has_history, std::vector<history_entry>, empty_storage>;
    using deferred_storage = std::conditional_t<has_deferred, std::vector<std::function<bool(fsm&)>>, empty_storage>;

    state_variant current_state_;
    [[no_unique_address]] Table table_{};
    Context* context_{nullptr};
    [[no_unique_address]] no_context dummy_ctx_{};
    [[no_unique_address]] Observer observer_{};
    [[no_unique_address]] history_storage history_records_{};
    [[no_unique_address]] deferred_storage deferred_queue_{};
    [[no_unique_address]] std::conditional_t<has_deferred, bool, empty_storage> is_replaying_deferred_{};
};

template <typename Table, typename Context = no_context, typename InitialState = typename Table::initial_state>
using dynamic_fsm = fsm<Table, Context, InitialState, dynamic_observer>;

}  // namespace fsm

// --- End: fsm.hpp ---

)raw_fsm_runtime";

        if (opts.thread_safe) {
            out << R"raw_fsm_runtime(
// ============================================================================
// Thread-Safe & Asynchronous Runtime (C++20)
// ============================================================================
// --- Begin: spsc_ring_buffer.hpp ---
namespace fsm {

// Cache line size constant to prevent false sharing without compiler-specific ABI interference-size warnings
inline constexpr std::size_t cache_line_size = 64;

/**
 * @brief Lock-Free Single-Producer Single-Consumer (SPSC) Ring Buffer.
 *
 * @tparam T Value type stored in the queue.
 * @tparam Capacity Power-of-two queue capacity.
 */
template <typename T, std::size_t Capacity = 1024>
class spsc_ring_buffer {
    static_assert((Capacity > 1) && ((Capacity & (Capacity - 1)) == 0),
                  "spsc_ring_buffer Capacity must be a power of two");

  public:
    using value_type = T;
    using size_type = std::size_t;

    spsc_ring_buffer() = default;

    ~spsc_ring_buffer() {
        T item;
        while (pop(item)) {
            // Drain remaining elements invoking destructors
        }
    }

    // Non-copyable, non-movable
    spsc_ring_buffer(const spsc_ring_buffer&) = delete;
    spsc_ring_buffer& operator=(const spsc_ring_buffer&) = delete;
    spsc_ring_buffer(spsc_ring_buffer&&) = delete;
    spsc_ring_buffer& operator=(spsc_ring_buffer&&) = delete;

    template <typename... Args>
    bool emplace(Args&&... args) noexcept(std::is_nothrow_constructible_v<T, Args...>) {
        const std::size_t head = head_.load(std::memory_order_relaxed);
        const std::size_t tail = tail_.load(std::memory_order_acquire);

        if ((head - tail) >= Capacity) {
            return false;  // Full
        }

        new (get_slot(head)) T(std::forward<Args>(args)...);
        head_.store(head + 1, std::memory_order_release);
        return true;
    }

    bool push(const T& item) noexcept(std::is_nothrow_copy_constructible_v<T>) { return emplace(item); }

    bool push(T&& item) noexcept(std::is_nothrow_move_constructible_v<T>) { return emplace(std::move(item)); }

    bool pop(T& out_item) noexcept(std::is_nothrow_move_assignable_v<T>) {
        const std::size_t tail = tail_.load(std::memory_order_relaxed);
        const std::size_t head = head_.load(std::memory_order_acquire);

        if (tail == head) {
            return false;  // Empty
        }

        T* slot = get_slot(tail);
        out_item = std::move(*slot);
        slot->~T();
        tail_.store(tail + 1, std::memory_order_release);
        return true;
    }

    [[nodiscard]] std::optional<T> pop() noexcept(std::is_nothrow_move_constructible_v<T>) {
        T item;
        if (pop(item)) {
            return item;
        }
        return std::nullopt;
    }

    [[nodiscard]] bool empty() const noexcept {
        return head_.load(std::memory_order_relaxed) == tail_.load(std::memory_order_relaxed);
    }

    [[nodiscard]] bool full() const noexcept {
        return (head_.load(std::memory_order_relaxed) - tail_.load(std::memory_order_relaxed)) >= Capacity;
    }

    [[nodiscard]] std::size_t size() const noexcept {
        const std::size_t head = head_.load(std::memory_order_relaxed);
        const std::size_t tail = tail_.load(std::memory_order_relaxed);
        return head >= tail ? (head - tail) : 0;
    }

    [[nodiscard]] constexpr std::size_t capacity() const noexcept { return Capacity; }

  private:
    static constexpr std::size_t IndexMask = Capacity - 1;

    T* get_slot(std::size_t index) noexcept { return reinterpret_cast<T*>(&storage_[index & IndexMask]); }

    alignas(cache_line_size) std::atomic<std::size_t> head_{0};
    alignas(cache_line_size) std::atomic<std::size_t> tail_{0};
    alignas(alignof(T)) std::array<std::aligned_storage_t<sizeof(T), alignof(T)>, Capacity> storage_;
};

}  // namespace fsm

// --- End: spsc_ring_buffer.hpp ---

// --- Begin: static_ring_buffer.hpp ---
namespace fsm {

/**
 * @brief Overflow policy when pushing into a saturated bounded ring buffer.
 */
enum class OverflowPolicy : std::uint8_t {
    DropOldest,        ///< Discards the oldest element at the head to accommodate the newest element
    DropIncoming,      ///< Rejects the incoming element, leaving the existing buffer unmodified
    AssertOnOverflow   ///< Triggers an assertion in debug/safety builds if the queue overflows
};

// Zero-allocation, static capacity ring buffer designed for hard real-time / embedded systems
template <typename T, std::size_t Capacity>
class static_ring_buffer {
    static_assert(Capacity > 0, "static_ring_buffer Capacity must be greater than 0");

  public:
    using value_type = T;
    using size_type = std::size_t;

    constexpr static_ring_buffer() noexcept = default;

    [[nodiscard]] constexpr bool empty() const noexcept { return size_ == 0; }
    [[nodiscard]] constexpr bool full() const noexcept { return size_ == Capacity; }
    [[nodiscard]] constexpr size_type size() const noexcept { return size_; }
    [[nodiscard]] constexpr size_type capacity() const noexcept { return Capacity; }

    constexpr bool push(const T& value, OverflowPolicy policy = OverflowPolicy::DropIncoming) noexcept {
        if (full()) {
            if (policy == OverflowPolicy::DropIncoming) {
                return false;
            }
            if (policy == OverflowPolicy::AssertOnOverflow) {
                assert(!full() && "static_ring_buffer overflow with AssertOnOverflow policy");
                return false;
            }
            if (policy == OverflowPolicy::DropOldest) {
                // Advance head to drop oldest item
                head_ = (head_ + 1) % Capacity;
                --size_;
            }
        }
        buffer_[tail_] = value;
        tail_ = (tail_ + 1) % Capacity;
        ++size_;
        return true;
    }

    constexpr bool push(T&& value, OverflowPolicy policy = OverflowPolicy::DropIncoming) noexcept {
        if (full()) {
            if (policy == OverflowPolicy::DropIncoming) {
                return false;
            }
            if (policy == OverflowPolicy::AssertOnOverflow) {
                assert(!full() && "static_ring_buffer overflow with AssertOnOverflow policy");
                return false;
            }
            if (policy == OverflowPolicy::DropOldest) {
                // Advance head to drop oldest item
                head_ = (head_ + 1) % Capacity;
                --size_;
            }
        }
        buffer_[tail_] = std::move(value);
        tail_ = (tail_ + 1) % Capacity;
        ++size_;
        return true;
    }

    constexpr std::optional<T> pop() noexcept {
        if (empty()) {
            return std::nullopt;
        }
        T item = std::move(buffer_[head_]);
        head_ = (head_ + 1) % Capacity;
        --size_;
        return item;
    }

    [[nodiscard]] constexpr const T* peek() const noexcept {
        if (empty()) {
            return nullptr;
        }
        return &buffer_[head_];
    }

    [[nodiscard]] constexpr T* peek() noexcept {
        if (empty()) {
            return nullptr;
        }
        return &buffer_[head_];
    }

    constexpr void clear() noexcept {
        head_ = 0;
        tail_ = 0;
        size_ = 0;
    }

  private:
    std::array<T, Capacity> buffer_{};
    size_type head_{0};
    size_type tail_{0};
    size_type size_{0};
};

}  // namespace fsm

// --- End: static_ring_buffer.hpp ---

// --- Begin: async_types.hpp ---
namespace fsm {

// Handler callback types for lifecycle, failures, and unhandled conditions
using unhandled_handler = std::function<void(std::string_view /*event*/, std::string_view /*state*/)>;
using guard_rejected_handler = std::function<void(std::string_view /*event*/, std::string_view /*state*/)>;
using deferred_handler = std::function<void(std::string_view /*event*/, std::string_view /*state*/)>;
using dispatch_failure_handler =
    std::function<void(std::string_view /*event*/, std::string_view /*state*/, dispatch_status /*status*/)>;
using exception_handler = std::function<void(std::exception_ptr)>;

// Snapshot taken under lock to invoke notifications/observers outside lock
struct dispatch_snapshot {
    dispatch_result result{dispatch_status::unhandled};
    std::string state_name{};
    std::vector<transition_info> notifications{};
    unhandled_handler unhandled_h{};
    guard_rejected_handler guard_rejected_h{};
    deferred_handler deferred_h{};
    dispatch_failure_handler failure_h{};
    exception_handler exception_h{};
    std::function<void(const transition_info&)> observer_h{};
};

// Represents a timed / delayed event task in the priority queue
template <typename HandlerType>
struct timed_event {
    std::chrono::steady_clock::time_point deadline;
    HandlerType task;

    bool operator>(const timed_event& other) const noexcept { return deadline > other.deadline; }
};

}  // namespace fsm

// --- End: async_types.hpp ---

// --- Begin: async_event_queue.hpp ---
namespace fsm {

template <typename HandlerType>
class async_event_queue {
  public:
    using timed_event_type = timed_event<HandlerType>;

    async_event_queue() = default;

    void push(HandlerType task) {
        {
            std::scoped_lock lock(mutex_);
            event_queue_.push(std::move(task));
        }
        cv_.notify_one();
    }

    void push_timed(std::chrono::steady_clock::time_point deadline, HandlerType task) {
        {
            std::scoped_lock lock(mutex_);
            timed_queue_.push(timed_event_type{deadline, std::move(task)});
        }
        cv_.notify_one();
    }

    [[nodiscard]] std::size_t size() const {
        std::scoped_lock lock(mutex_);
        return event_queue_.size() + timed_queue_.size();
    }

    [[nodiscard]] bool empty() const {
        std::scoped_lock lock(mutex_);
        return event_queue_.empty() && timed_queue_.empty();
    }

    void clear() {
        std::scoped_lock lock(mutex_);
        std::queue<HandlerType> empty_q;
        std::swap(event_queue_, empty_q);
        std::priority_queue<timed_event_type, std::vector<timed_event_type>, std::greater<>> empty_timed;
        std::swap(timed_queue_, empty_timed);
    }

    // Single-event pop for manual polling or worker loop
    bool try_pop(HandlerType& out_task) {
        std::scoped_lock lock(mutex_);
        const auto now = std::chrono::steady_clock::now();
        if (!timed_queue_.empty() && now >= timed_queue_.top().deadline) {
            out_task = timed_queue_.top().task;
            timed_queue_.pop();
            return true;
        }
        if (!event_queue_.empty()) {
            out_task = std::move(event_queue_.front());
            event_queue_.pop();
            return true;
        }
        return false;
    }

    // Drain all ready tasks (for process_all or stop_worker)
    std::vector<HandlerType> drain_ready_batch() {
        std::vector<HandlerType> batch;
        std::scoped_lock lock(mutex_);
        const auto now = std::chrono::steady_clock::now();
        while (!timed_queue_.empty() && now >= timed_queue_.top().deadline) {
            batch.push_back(timed_queue_.top().task);
            timed_queue_.pop();
        }
        while (!event_queue_.empty()) {
            batch.push_back(std::move(event_queue_.front()));
            event_queue_.pop();
        }
        return batch;
    }

    std::mutex& mutex() noexcept { return mutex_; }
    std::condition_variable& cv() noexcept { return cv_; }
    std::queue<HandlerType>& event_queue() noexcept { return event_queue_; }
    std::priority_queue<timed_event_type, std::vector<timed_event_type>, std::greater<>>& timed_queue() noexcept {
        return timed_queue_;
    }

  private:
    mutable std::mutex mutex_;
    std::condition_variable cv_;
    std::queue<HandlerType> event_queue_;
    std::priority_queue<timed_event_type, std::vector<timed_event_type>, std::greater<>> timed_queue_;
};

}  // namespace fsm

// --- End: async_event_queue.hpp ---

// --- Begin: thread_safe_fsm.hpp ---
namespace fsm {

/**
 * @brief Thread-safe Finite State Machine wrapper supporting both synchronous and asynchronous dispatch.
 *
 * @details
 * `thread_safe_fsm` supports two primary operational models:
 *
 * 1. **Background Worker Model (Asynchronous)**:
 *    - Events pushed via `post()`, `post(evt, cb)`, and `post_async()` automatically start the background
 *      worker thread if not already active, ensuring `post_async().get()` never hangs.
 *    - `stop_worker()` signals termination, joins the worker thread safely, and systematically drains
 *      all pending and cascading events.
 *    - `request_stop()` allows asynchronous, non-blocking stop requests (e.g. from within callbacks/actions).
 *
 * 2. **Manual Polling / Game Loop Model (Synchronous / Single-Threaded Event Loop)**:
 *    - Push events via `enqueue()`.
 *    - Process them deterministically on the calling thread when desired using `process_one()` or `process_all()`.
 *
 * 3. **Synchronous Immediate Dispatch**:
 *    - `send()` is always available for immediate, synchronous dispatch from any thread.
 *
 * 4. **Thread-Safe Context Access**:
 *    - Use `with_context([](Context& ctx) { ... })` for synchronized, lock-protected access to the shared Context.
 */
template <typename Table, typename Context = no_context, typename InitialState = typename Table::initial_state>
class thread_safe_fsm {
  public:
    using fsm_type = fsm<Table, Context, InitialState, dynamic_observer>;
    using context_type = Context;
    using event_handler = std::function<void(fsm_type&)>;
    using unhandled_handler = ::fsm::unhandled_handler;
    using guard_rejected_handler = ::fsm::guard_rejected_handler;
    using deferred_handler = ::fsm::deferred_handler;
    using dispatch_failure_handler = ::fsm::dispatch_failure_handler;
    using exception_handler = ::fsm::exception_handler;

    // Static compile-time introspection
    static constexpr std::size_t state_count = fsm_type::state_count;
    static constexpr std::size_t transition_count = fsm_type::transition_count;
    static constexpr std::size_t event_count = fsm_type::event_count;

    template <typename State>
    static constexpr bool has_state = fsm_type::template has_state<State>;

    template <typename Event>
    static constexpr bool has_event = fsm_type::template has_event<Event>;

    // Default constructor (enabled only when Context is no_context)
    template <typename C = Context, typename = std::enable_if_t<std::is_same_v<C, no_context>>>
    thread_safe_fsm() {}

    explicit thread_safe_fsm(Context& ctx, Table table = Table{}) : fsm_(ctx, std::move(table)) {}

    explicit thread_safe_fsm(Context& ctx, InitialState initial, Table table = Table{})
        : fsm_(ctx, std::move(initial), std::move(table)) {}

    /**
     * @brief Destructor: ensures background worker (if running) is cleanly stopped and joined,
     * drains all remaining queue tasks before destruction, and purges queues.
     */
    ~thread_safe_fsm() {
        stop_worker();
        clear_queue();
    }

    // Non-copyable
    thread_safe_fsm(const thread_safe_fsm&) = delete;
    thread_safe_fsm& operator=(const thread_safe_fsm&) = delete;

    // Move operations
    thread_safe_fsm(thread_safe_fsm&&) = delete;
    thread_safe_fsm& operator=(thread_safe_fsm&&) = delete;

    // ========================================================================
    // Context & Observer Management
    // ========================================================================
    void set_context(Context& ctx) {
        std::scoped_lock lock(dispatch_mutex_);
        fsm_.set_context(ctx);
    }

    template <typename Callable>
    auto with_context(Callable&& callable) {
        std::scoped_lock lock(dispatch_mutex_);
        return std::forward<Callable>(callable)(fsm_.context());
    }

    template <typename Callable>
    auto with_context(Callable&& callable) const {
        std::scoped_lock lock(dispatch_mutex_);
        return std::forward<Callable>(callable)(fsm_.context());
    }

    [[nodiscard]] Context& context() noexcept { return fsm_.context(); }
    [[nodiscard]] const Context& context() const noexcept { return fsm_.context(); }

    [[nodiscard]] Context* get_context() noexcept { return fsm_.get_context(); }
    [[nodiscard]] const Context* get_context() const noexcept { return fsm_.get_context(); }

    void set_observer(std::function<void(const transition_info&)> observer) {
        std::scoped_lock lock(dispatch_mutex_);
        user_observer_ = std::move(observer);
        if (user_observer_) {
            fsm_.set_observer([this](const transition_info& info) { notification_buffer_.push_back(info); });
        } else {
            fsm_.set_observer(nullptr);
        }
    }

    void set_unhandled_handler(unhandled_handler handler) {
        std::scoped_lock lock(dispatch_mutex_);
        unhandled_handler_ = std::move(handler);
    }

    void set_guard_rejected_handler(guard_rejected_handler handler) {
        std::scoped_lock lock(dispatch_mutex_);
        guard_rejected_handler_ = std::move(handler);
    }

    void set_deferred_handler(deferred_handler handler) {
        std::scoped_lock lock(dispatch_mutex_);
        deferred_handler_ = std::move(handler);
    }

    void set_dispatch_failure_handler(dispatch_failure_handler handler) {
        std::scoped_lock lock(dispatch_mutex_);
        failure_handler_ = std::move(handler);
    }

    void set_exception_handler(exception_handler handler) {
        std::scoped_lock lock(dispatch_mutex_);
        exception_handler_ = std::move(handler);
    }

    [[nodiscard]] std::exception_ptr last_exception() const {
        std::scoped_lock lock(dispatch_mutex_);
        return last_exception_;
    }

    void clear_last_exception() {
        std::scoped_lock lock(dispatch_mutex_);
        last_exception_ = nullptr;
    }

    // ========================================================================
    // Synchronous Dispatch
    // ========================================================================
    template <typename Event>
    dispatch_result send(const Event& event) {
        dispatch_snapshot snap;
        try {
            snap = execute_dispatch_under_lock(event);
        } catch (...) {
            auto ex = std::current_exception();
            handle_exception_outside_lock(ex, get_exception_handler_copy());
            std::rethrow_exception(ex);
        }
        invoke_notifications_outside_lock(event, snap);
        return snap.result;
    }

    // ========================================================================
    // Asynchronous Queue
    // ========================================================================
    template <typename Event>
    void post(Event event) {
        if (!worker_running_.load() && !is_calling_from_worker_thread()) {
            start_worker();
        }
        enqueue(std::move(event));
    }

    template <typename Event, typename Callback>
    void post(Event event, Callback&& on_complete) {
        if (!worker_running_.load() && !is_calling_from_worker_thread()) {
            start_worker();
        }
        auto task = [this, evt = std::move(event), cb = std::forward<Callback>(on_complete)](fsm_type&) mutable {
            dispatch_snapshot snap;
            bool success = false;
            try {
                snap = execute_dispatch_under_lock(evt);
                invoke_notifications_outside_lock(evt, snap);
                success = true;
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
            }
            if (success) {
                try {
                    cb(snap.result);
                } catch (...) {
                    handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
                }
            }
        };
        queue_.push(std::move(task));
    }

    template <typename Event>
    std::future<dispatch_result> post_async(Event event) {
        if (!worker_running_.load() && !is_calling_from_worker_thread()) {
            start_worker();
        }
        auto promise = std::make_shared<std::promise<dispatch_result>>();
        auto future = promise->get_future();
        auto task = [this, evt = std::move(event), p = promise](fsm_type&) {
            try {
                auto snap = execute_dispatch_under_lock(evt);
                invoke_notifications_outside_lock(evt, snap);
                p->set_value(snap.result);
            } catch (...) {
                auto ex = std::current_exception();
                handle_exception_outside_lock(ex, get_exception_handler_copy());
                p->set_exception(ex);
            }
        };
        queue_.push(std::move(task));
        return future;
    }

    template <typename Event>
    void enqueue(Event event) {
        auto task = [this, evt = std::move(event)](fsm_type&) {
            try {
                auto snap = execute_dispatch_under_lock(evt);
                invoke_notifications_outside_lock(evt, snap);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
            }
        };
        {
            std::scoped_lock lock(queue_.mutex());
            if (is_stopping_.load(std::memory_order_acquire) && !is_calling_from_worker_thread() &&
                !is_calling_from_stopping_thread()) {
                return;
            }
            queue_.event_queue().push(std::move(task));
        }
        queue_.cv().notify_one();
    }

    // ========================================================================
    // Manual Polling (Single-Consumer Loop)
    // ========================================================================
    bool process_one() {
        if (worker_running_.load(std::memory_order_acquire)) {
            return false;
        }
        bool expected = false;
        if (!is_polling_.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
            return false;
        }
        struct PollingGuard {
            std::atomic<bool>& flag;
            ~PollingGuard() { flag.store(false, std::memory_order_release); }
        } guard{is_polling_};

        event_handler task;
        if (!queue_.try_pop(task)) {
            return false;
        }
        if (task) {
            try {
                task(fsm_);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
                return false;
            }
        }
        return true;
    }

    std::size_t process_all() {
        if (worker_running_.load(std::memory_order_acquire)) {
            return 0;
        }
        bool expected = false;
        if (!is_polling_.compare_exchange_strong(expected, true, std::memory_order_acq_rel)) {
            return 0;
        }
        struct PollingGuard {
            std::atomic<bool>& flag;
            ~PollingGuard() { flag.store(false, std::memory_order_release); }
        } guard{is_polling_};

        std::size_t total = 0;
        while (true) {
            auto batch = queue_.drain_ready_batch();
            if (batch.empty()) {
                break;
            }
            for (auto& task : batch) {
                if (task) {
                    try {
                        task(fsm_);
                    } catch (...) {
                        handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
                    }
                }
            }
            total += batch.size();
        }
        return total;
    }

    [[nodiscard]] std::size_t pending_events() const { return queue_.size(); }
    [[nodiscard]] bool is_queue_empty() const { return queue_.empty(); }
    void clear_queue() { queue_.clear(); }

    [[nodiscard]] std::size_t deferred_count() const {
        std::scoped_lock lock(dispatch_mutex_);
        return fsm_.deferred_count();
    }

    void clear_deferred_events() {
        std::scoped_lock lock(dispatch_mutex_);
        fsm_.clear_deferred_events();
    }

    [[nodiscard]] bool is_calling_from_worker_thread() const noexcept {
        const auto id = worker_thread_id_.load(std::memory_order_acquire);
        return id != std::thread::id{} && std::this_thread::get_id() == id;
    }

    [[nodiscard]] bool is_calling_from_stopping_thread() const noexcept {
        const auto id = stopping_thread_id_.load(std::memory_order_acquire);
        return id != std::thread::id{} && std::this_thread::get_id() == id;
    }

    // ========================================================================
    // Background Worker Thread Management
    // ========================================================================
    void start_worker() {
        if (is_calling_from_worker_thread()) {
            return;
        }
        std::scoped_lock lock(lifecycle_mutex_);
        {
            std::scoped_lock q_lock(queue_.mutex());
            if (worker_running_ || is_stopping_) {
                return;
            }
            if (worker_thread_.joinable()) {
                worker_thread_.join();
            }
            worker_running_ = true;
        }
        worker_thread_ = std::thread([this]() { this->worker_loop(); });
    }

    void request_stop() noexcept {
        {
            std::scoped_lock q_lock(queue_.mutex());
            if (!worker_running_) {
                return;
            }
            worker_running_ = false;
        }
        queue_.cv().notify_all();
    }

    void stop_worker() {
        if (is_calling_from_worker_thread()) {
            request_stop();
            return;
        }

        std::scoped_lock lock(lifecycle_mutex_);
        stopping_thread_id_.store(std::this_thread::get_id(), std::memory_order_release);
        {
            std::scoped_lock q_lock(queue_.mutex());
            worker_running_ = false;
            is_stopping_ = true;
        }
        queue_.cv().notify_all();

        if (worker_thread_.joinable()) {
            worker_thread_.join();
        }

        // Systematically drain all pending and chained events until queue is empty
        process_all();

        {
            std::scoped_lock q_lock(queue_.mutex());
            is_stopping_ = false;
            stopping_thread_id_.store(std::thread::id{}, std::memory_order_release);
        }
    }

    [[nodiscard]] bool is_worker_running() const { return worker_running_.load(); }

    // ========================================================================
    // Thread-safe State Inspection
    // ========================================================================
    template <typename State>
    [[nodiscard]] bool is_in_state() const {
        std::scoped_lock lock(dispatch_mutex_);
        return fsm_.template is_in_state<State>();
    }

    [[nodiscard]] std::string current_state_name() const {
        std::scoped_lock lock(dispatch_mutex_);
        return std::string(fsm_.current_state_name());
    }

    template <typename Callable>
    auto with_state(Callable&& callable) const {
        std::scoped_lock lock(dispatch_mutex_);
        return std::visit(std::forward<Callable>(callable), fsm_.get_current_state_variant());
    }

    template <typename Callable>
    auto with_fsm(Callable&& callable) {
        std::scoped_lock lock(dispatch_mutex_);
        return std::forward<Callable>(callable)(fsm_);
    }

    template <typename Event, typename Rep, typename Period>
    void post_delayed(Event event, std::chrono::duration<Rep, Period> delay) {
        if (!worker_running_.load() && !is_calling_from_worker_thread()) {
            start_worker();
        }
        auto deadline = std::chrono::steady_clock::now() + delay;
        auto task = [this, evt = std::move(event)](fsm_type&) {
            try {
                auto snap = execute_dispatch_under_lock(evt);
                invoke_notifications_outside_lock(evt, snap);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
            }
        };
        queue_.push_timed(deadline, std::move(task));
    }

  private:
    template <typename Event>
    dispatch_snapshot execute_dispatch_under_lock(const Event& evt) {
        dispatch_snapshot snap;
        std::scoped_lock lock(dispatch_mutex_);
        notification_buffer_.clear();
        snap.result = fsm_.dispatch(evt);
        snap.state_name = std::string(fsm_.current_state_name());
        snap.notifications = std::move(notification_buffer_);
        snap.unhandled_h = unhandled_handler_;
        snap.guard_rejected_h = guard_rejected_handler_;
        snap.deferred_h = deferred_handler_;
        snap.failure_h = failure_handler_;
        snap.exception_h = exception_handler_;
        snap.observer_h = user_observer_;
        return snap;
    }

    template <typename Event>
    void invoke_notifications_outside_lock(const Event& evt, const dispatch_snapshot& snap) {
        if (snap.observer_h) {
            for (const auto& info : snap.notifications) {
                try {
                    snap.observer_h(info);
                } catch (...) {
                    handle_exception_outside_lock(std::current_exception(), snap.exception_h);
                }
            }
        }
        if (snap.result.is_unhandled() && snap.unhandled_h) {
            try {
                snap.unhandled_h(get_event_name(evt), snap.state_name);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), snap.exception_h);
            }
        } else if (snap.result.is_guard_rejected() && snap.guard_rejected_h) {
            try {
                snap.guard_rejected_h(get_event_name(evt), snap.state_name);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), snap.exception_h);
            }
        } else if (snap.result.is_deferred() && snap.deferred_h) {
            try {
                snap.deferred_h(get_event_name(evt), snap.state_name);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), snap.exception_h);
            }
        }
        if (!snap.result.is_ok() && snap.failure_h) {
            try {
                snap.failure_h(get_event_name(evt), snap.state_name, snap.result.status);
            } catch (...) {
                handle_exception_outside_lock(std::current_exception(), snap.exception_h);
            }
        }
    }

    void handle_exception_outside_lock(std::exception_ptr ex, const exception_handler& local_h) {
        {
            std::scoped_lock lock(dispatch_mutex_);
            last_exception_ = ex;
        }
        if (local_h) {
            try {
                local_h(ex);
            } catch (...) {
            }
        }
    }

    exception_handler get_exception_handler_copy() {
        std::scoped_lock lock(dispatch_mutex_);
        return exception_handler_;
    }

    void worker_loop() {
        worker_thread_id_.store(std::this_thread::get_id(), std::memory_order_release);
        while (true) {
            event_handler task;
            {
                std::unique_lock<std::mutex> lock(queue_.mutex());

                while (worker_running_ && queue_.event_queue().empty() && queue_.timed_queue().empty()) {
                    queue_.cv().wait(lock);
                }

                while (worker_running_ && queue_.event_queue().empty() && !queue_.timed_queue().empty()) {
                    const auto now = std::chrono::steady_clock::now();
                    if (now >= queue_.timed_queue().top().deadline) {
                        break;
                    }
                    queue_.cv().wait_until(lock, queue_.timed_queue().top().deadline);
                }

                if (!worker_running_ && queue_.event_queue().empty() && queue_.timed_queue().empty()) {
                    break;
                }

                const auto now = std::chrono::steady_clock::now();
                if (!queue_.timed_queue().empty() && now >= queue_.timed_queue().top().deadline) {
                    task = queue_.timed_queue().top().task;
                    queue_.timed_queue().pop();
                } else if (!queue_.event_queue().empty()) {
                    task = std::move(queue_.event_queue().front());
                    queue_.event_queue().pop();
                }
            }

            if (task) {
                try {
                    task(fsm_);
                } catch (...) {
                    handle_exception_outside_lock(std::current_exception(), get_exception_handler_copy());
                }
            }
        }
        worker_thread_id_.store(std::thread::id{}, std::memory_order_release);
    }

    mutable async_event_queue<event_handler> queue_;
    mutable std::recursive_mutex lifecycle_mutex_;
    mutable std::recursive_mutex dispatch_mutex_;
    fsm_type fsm_;
    std::function<void(const transition_info&)> user_observer_{};
    std::vector<transition_info> notification_buffer_{};
    unhandled_handler unhandled_handler_{};
    guard_rejected_handler guard_rejected_handler_{};
    deferred_handler deferred_handler_{};
    dispatch_failure_handler failure_handler_{};
    exception_handler exception_handler_{};
    std::exception_ptr last_exception_{nullptr};

    std::atomic<bool> worker_running_{false};
    std::atomic<bool> is_stopping_{false};
    std::atomic<bool> is_polling_{false};
    std::atomic<std::thread::id> worker_thread_id_{};
    std::atomic<std::thread::id> stopping_thread_id_{};
    std::thread worker_thread_;
};

}  // namespace fsm

// --- End: thread_safe_fsm.hpp ---

// --- Begin: static_thread_safe_fsm.hpp ---
namespace fsm {

// Zero-allocation, statically bounded thread-safe FSM wrapper designed for hard real-time and embedded systems.
// Does NOT use std::function, heap allocations, std::vector, or std::future.
template <typename Table, typename Context = no_context, std::size_t QueueCapacity = 64,
          OverflowPolicy Policy = OverflowPolicy::DropIncoming,
          typename InitialState = typename Table::initial_state, typename Observer = no_observer>
class static_thread_safe_fsm {
  public:
    using fsm_type = fsm<Table, Context, InitialState, Observer>;
    using event_variant = typename Table::event_variant;
    using context_type = Context;

    static constexpr std::size_t state_count = fsm_type::state_count;
    static constexpr std::size_t transition_count = fsm_type::transition_count;
    static constexpr std::size_t event_count = fsm_type::event_count;
    static constexpr std::size_t queue_capacity = QueueCapacity;
    static constexpr OverflowPolicy overflow_policy = Policy;

    template <typename State>
    static constexpr bool has_state = fsm_type::template has_state<State>;

    template <typename Event>
    static constexpr bool has_event = fsm_type::template has_event<Event>;

    template <typename C = Context, typename = std::enable_if_t<std::is_same_v<C, no_context>>>
    static_thread_safe_fsm() {}

    explicit static_thread_safe_fsm(Context& ctx, Table table = Table{}) : fsm_(ctx, std::move(table)) {}

    explicit static_thread_safe_fsm(Context& ctx, InitialState initial, Table table = Table{})
        : fsm_(ctx, std::move(initial), std::move(table)) {}

    ~static_thread_safe_fsm() { stop_worker(); }

    // Non-copyable, non-movable
    static_thread_safe_fsm(const static_thread_safe_fsm&) = delete;
    static_thread_safe_fsm& operator=(const static_thread_safe_fsm&) = delete;
    static_thread_safe_fsm(static_thread_safe_fsm&&) = delete;
    static_thread_safe_fsm& operator=(static_thread_safe_fsm&&) = delete;

    [[nodiscard]] Context& context() noexcept { return fsm_.context(); }
    [[nodiscard]] const Context& context() const noexcept { return fsm_.context(); }

    [[nodiscard]] Context* get_context() noexcept { return fsm_.get_context(); }
    [[nodiscard]] const Context* get_context() const noexcept { return fsm_.get_context(); }

    template <typename Event>
    dispatch_result send(const Event& event) {
        std::scoped_lock lock(mutex_);
        return fsm_.dispatch(event);
    }

    // Zero-allocation queue submission
    template <typename Event>
    bool post(Event&& event, OverflowPolicy policy = Policy) {
        if (!worker_running_.load() && !is_calling_from_worker_thread()) {
            start_worker();
        }
        {
            std::scoped_lock lock(mutex_);
            if (!queue_.push(event_variant(std::forward<Event>(event)), policy)) {
                return false;
            }
        }
        cv_.notify_one();
        return true;
    }

    template <typename Event>
    bool enqueue(Event&& event, OverflowPolicy policy = Policy) {
        std::scoped_lock lock(mutex_);
        return queue_.push(event_variant(std::forward<Event>(event)), policy);
    }

    bool process_one() {
        event_variant evt;
        {
            std::scoped_lock lock(mutex_);
            auto popped = queue_.pop();
            if (!popped) {
                return false;
            }
            evt = std::move(*popped);
        }
        std::visit([this](const auto& e) { fsm_.dispatch(e); }, evt);
        return true;
    }

    std::size_t process_all() {
        std::size_t processed = 0;
        while (process_one()) {
            ++processed;
        }
        return processed;
    }

    [[nodiscard]] std::size_t pending_events() const {
        std::scoped_lock lock(mutex_);
        return queue_.size();
    }

    [[nodiscard]] bool is_queue_empty() const {
        std::scoped_lock lock(mutex_);
        return queue_.empty();
    }

    [[nodiscard]] bool is_queue_full() const {
        std::scoped_lock lock(mutex_);
        return queue_.full();
    }

    void start_worker() {
        std::scoped_lock lock(mutex_);
        if (worker_running_) {
            return;
        }
        worker_running_ = true;
        worker_thread_ = std::thread([this]() { worker_loop(); });
    }

    void stop_worker() {
        {
            std::scoped_lock lock(mutex_);
            if (!worker_running_) {
                return;
            }
            worker_running_ = false;
        }
        cv_.notify_all();
        if (worker_thread_.joinable()) {
            worker_thread_.join();
        }
    }

    [[nodiscard]] bool is_worker_running() const { return worker_running_.load(); }

    template <typename State>
    [[nodiscard]] bool is_in_state() const {
        std::scoped_lock lock(mutex_);
        return fsm_.template is_in_state<State>();
    }

    [[nodiscard]] std::string_view current_state_name() const {
        std::scoped_lock lock(mutex_);
        return fsm_.current_state_name();
    }

  private:
    [[nodiscard]] bool is_calling_from_worker_thread() const noexcept {
        return worker_thread_.get_id() == std::this_thread::get_id();
    }

    void worker_loop() {
        while (true) {
            event_variant evt;
            {
                std::unique_lock<std::mutex> lock(mutex_);
                cv_.wait(lock, [this]() { return !worker_running_ || !queue_.empty(); });

                if (!worker_running_ && queue_.empty()) {
                    break;
                }

                auto popped = queue_.pop();
                if (popped) {
                    evt = std::move(*popped);
                } else {
                    continue;
                }
            }

            std::visit([this](const auto& e) { fsm_.dispatch(e); }, evt);
        }
    }

    mutable std::mutex mutex_;
    std::condition_variable cv_;
    fsm_type fsm_;
    static_ring_buffer<event_variant, QueueCapacity> queue_;
    std::atomic<bool> worker_running_{false};
    std::thread worker_thread_;
};

}  // namespace fsm

// --- End: static_thread_safe_fsm.hpp ---

)raw_fsm_runtime";
        }
    }
};

}  // namespace fsm::codegen
