#pragma once

#include <cstdint>
#include <sstream>
#include <string>

#include "fsm/backend/cpp/cpp17_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp20_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp_model_emitter.hpp"
#include "fsm/backend/cpp/cpp_options.hpp"
#include "fsm/diagnostic/diagnostic_engine.hpp"
#include "fsm/ir/fsm_ir.hpp"
#include "fsm/middleend/passes/choice_inlining_pass.hpp"

namespace fsm::backend::cpp {

using ::fsm::diagnostic::DiagnosticEngine;
using ::fsm::middleend::passes::ChoiceInliningPass;

class CppGenerator {
  public:
    static std::string generate_header(const FsmIr& model, const GeneratorOptions& options = {}) {
        FsmIr processed_model = model;
        if (!processed_model.choice_nodes.empty()) {
            DiagnosticEngine diag;
            ChoiceInliningPass choice_pass;
            choice_pass.run(processed_model, diag);
        }

        std::ostringstream out;

        std::string std_str = (options.cpp_standard == CppStandard::Cpp20) ? "C++20" : "C++17";

        out << "/**\n";
        out << " * @file " << processed_model.name << ".hpp\n";
        out << " * @brief Auto-generated State Machine definition for '" << processed_model.name << "'\n";
        out << " * @note Generated by fsmc (Finite State Machine Compiler). Target standard: " << std_str << ".\n";
        if (options.standalone) {
            out << " * @note Mode: Standalone Self-Contained Header (Zero External Dependencies)\n";
        }
        out << " */\n\n";

        out << "#pragma once\n\n";

        if (options.standalone) {
            if (options.cpp_standard == CppStandard::Cpp20) {
                Cpp20StandaloneRuntime::emit(out, options);
            } else {
                Cpp17StandaloneRuntime::emit(out, options);
            }
        } else {
            out << "#include \"fsm/backend/cpp/runtime/fsm.hpp\"\n";
            if (options.thread_safe) {
                out << "#include \"fsm/backend/cpp/runtime/thread_safe_fsm.hpp\"\n";
                out << "#include \"fsm/backend/cpp/runtime/spsc_fsm.hpp\"\n";
            }
            out << "#include <string_view>\n";
            out << "#include <iostream>\n\n";
        }

        std::string effective_ns = options.target_namespace;
        if (effective_ns.empty()) {
            effective_ns = !processed_model.package.empty() ? processed_model.package : "fsm_generated";
        }

        if (!effective_ns.empty()) {
            out << "namespace " << effective_ns << " {\n\n";
        }


        CppModelEmitter::emit_model(out, processed_model, options);

        if (!effective_ns.empty()) {
            out << "\n} // namespace " << effective_ns << "\n";
        }


        return out.str();
    }
};

}  // namespace fsm::backend::cpp

namespace fsm::backend {
using cpp::CppGenerator;
}  // namespace fsm::backend
