#pragma once

#include <cstdint>
#include <sstream>
#include <string>

#include "fsm/backend/cpp/cpp17_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp20_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp_model_emitter.hpp"
#include "fsm/backend/cpp/cpp_options.hpp"
#include "fsm/ir/fsm_ir.hpp"

namespace fsm::codegen {

class CppGenerator {
  public:
    static std::string generate_header(const FsmIr& model, const GeneratorOptions& options = {}) {
        std::ostringstream out;

        std::string std_str = (options.cpp_standard == CppStandard::Cpp20) ? "C++20" : "C++17";

        out << "// ============================================================================\n";
        out << "// Auto-generated by fsmc (" << std_str << " State Machine Compiler Infrastructure)\n";
        out << "// Target: Compile-time Zero-Overhead FSM (" << std_str << ")\n";
        if (options.standalone) {
            out << "// Mode: Standalone Self-Contained Header (Zero External Dependencies)\n";
        }
        out << "// ============================================================================\n\n";

        out << "#pragma once\n\n";

        if (options.standalone) {
            if (options.cpp_standard == CppStandard::Cpp20) {
                Cpp20StandaloneRuntime::emit(out, options);
            } else {
                Cpp17StandaloneRuntime::emit(out, options);
            }
        } else {
            out << "#include \"fsm/runtime/cpp/fsm.hpp\"\n";
            if (options.thread_safe) {
                out << "#include \"fsm/runtime/cpp/thread_safe_fsm.hpp\"\n";
                out << "#include \"fsm/runtime/cpp/spsc_fsm.hpp\"\n";
            }
            out << "#include <string_view>\n";
            out << "#include <iostream>\n\n";
        }

        if (!model.ns.empty()) {
            out << "namespace " << model.ns << " {\n\n";
        }

        CppModelEmitter::emit_model(out, model, options);

        if (!model.ns.empty()) {
            out << "\n} // namespace " << model.ns << "\n";
        }

        return out.str();
    }
};

}  // namespace fsm::codegen
