/**
 * @file test_cmake_integration.cpp
 * @brief Integration test verifying the `fsm_target_sources` CMake build-system macro.
 *
 * Test Intent:
 * Prove that the CMake custom command integration `fsm_target_sources()` generates
 * C++ header files at build time from diagram source files (.puml/.mmd) and links them
 * cleanly into downstream consumer targets.
 *
 * Scenario:
 * - Build `test_cmake_integration` executable generated by `fsm_target_sources(test_cmake_integration ...)`.
 * - Verify runtime instantiation and state dispatching in the generated namespace `net_cmake`.
 */

#include <cassert>
#include <iostream>

#include "connection_fsm.hpp"

int main() {
    std::cout << "=================================================\n"
              << "  RUNNING CMAKE INTEGRATION (fsm_target_sources) \n"
              << "=================================================\n";

    net_cmake::ConnectionFSM sm;

    assert(sm.current_state_name() == "Disconnected");
    assert(sm.is_in_state<net_cmake::Disconnected>());

    sm.dispatch(net_cmake::ConnectCmd{});
    assert(sm.current_state_name() == "Connecting");
    assert(sm.is_in_state<net_cmake::Connecting>());

    sm.dispatch(net_cmake::HandshakeOkEvent{});
    assert(sm.current_state_name() == "Connected");
    assert(sm.is_in_state<net_cmake::Connected>());

    std::cout << "[PASS] fsm_target_sources CMake integration test passed successfully!\n"
              << "=================================================\n";
    return 0;
}
