#include "fsm/backend/cpp/cpp_generator.hpp"

#include <sstream>
#include <stdexcept>

#include "fsm/backend/cpp/cpp17_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp20_standalone_runtime.hpp"
#include "fsm/backend/cpp/cpp_backend_validator.hpp"
#include "fsm/backend/cpp/cpp_model_emitter.hpp"
#include "fsm/diagnostic/diagnostic_engine.hpp"
#include "fsm/middleend/passes/choice_inlining_pass.hpp"
#include "fsm/middleend/passes/fork_join_lowering_pass.hpp"
#include "fsm/middleend/passes/orthogonal_product_pass.hpp"

namespace fsm::backend::cpp {

std::string CppGenerator::generate_header(const FsmIr& model, const GeneratorOptions& options) {
    FsmIr processed_model = model;

    bool has_choice_structure = !processed_model.choice_nodes.empty();
    for (const auto& state : processed_model.states) {
        if (state.kind == ir::StateKind::Choice || state.kind == ir::StateKind::Junction) {
            has_choice_structure = true;
            break;
        }
    }
    if (has_choice_structure) {
        diagnostic::DiagnosticEngine diag;
        middleend::passes::ChoiceInliningPass choice_pass;
        choice_pass.run(processed_model, diag);
    }

    bool has_fork_join = false;
    for (const auto& state : processed_model.states) {
        if (state.kind == ir::StateKind::Fork || state.kind == ir::StateKind::Join) {
            has_fork_join = true;
            break;
        }
    }
    if (has_fork_join) {
        diagnostic::DiagnosticEngine diag;
        middleend::passes::ForkJoinLoweringPass fork_join_pass;
        fork_join_pass.run(processed_model, diag);
    }

    bool has_parallel_structure = false;
    for (const auto& state : processed_model.states) {
        has_parallel_structure =
            has_parallel_structure || state.kind == ir::StateKind::Parallel || !state.orthogonal_regions.empty();
    }
    if (has_parallel_structure) {
        diagnostic::DiagnosticEngine diag;
        middleend::passes::OrthogonalProductPass product_pass;
        product_pass.run(processed_model, diag);
        if (diag.has_errors()) {
            throw std::invalid_argument(diag.render_to_string());
        }
    }

    diagnostic::DiagnosticEngine backend_diagnostics;
    if (!CppBackendValidator::validate_model(processed_model, backend_diagnostics)) {
        throw std::invalid_argument(backend_diagnostics.render_to_string());
    }

    std::ostringstream out;

    std::string std_str = (options.cpp_standard == CppStandard::Cpp20) ? "C++20" : "C++17";

    out << "/**\n";
    out << " * @file " << processed_model.name << ".hpp\n";
    out << " * @brief Auto-generated State Machine definition for '" << processed_model.name << "'\n";
    out << " * @note Generated by fsmc (Finite State Machine Compiler). Target standard: " << std_str << ".\n";
    if (options.standalone) {
        out << " * @note Mode: Standalone Self-Contained Header (Zero External Dependencies)\n";
    }
    out << " */\n\n";

    out << "#pragma once\n\n";

    if (options.standalone) {
        if (options.cpp_standard == CppStandard::Cpp20) {
            Cpp20StandaloneRuntime::emit(out, options);
        } else {
            Cpp17StandaloneRuntime::emit(out, options);
        }
    } else {
        out << "#include \"fsm/backend/cpp/runtime/fsm.hpp\"\n";
        if (options.thread_safe) {
            out << "#include \"fsm/backend/cpp/runtime/thread_safe_fsm.hpp\"\n";
            out << "#include \"fsm/backend/cpp/runtime/spsc_fsm.hpp\"\n";
        }
        out << "#include <string_view>\n";
        out << "#include <iostream>\n\n";
    }

    std::string effective_ns = options.target_namespace;
    if (effective_ns.empty()) {
        effective_ns = !processed_model.package.empty() ? processed_model.package : "fsm_generated";
    }

    if (!effective_ns.empty()) {
        out << "namespace " << effective_ns << " {\n\n";
    }

    CppModelEmitter::emit_model(out, processed_model, options);

    if (!effective_ns.empty()) {
        out << "\n} // namespace " << effective_ns << "\n";
    }

    return out.str();
}

}  // namespace fsm::backend::cpp
