// ============================================================================
// Auto-generated by fsm-gen (C++20 State Machine Compiler)
// Target: Compile-time Zero-Overhead FSM (C++20)
// Mode: Standalone Self-Contained Header (Zero External Dependencies)
// ============================================================================

#pragma once

#include <atomic>
#include <concepts>
#include <condition_variable>
#include <functional>
#include <mutex>
#include <queue>
#include <stop_token>
#include <string_view>
#include <thread>
#include <tuple>
#include <type_traits>
#include <utility>
#include <variant>

namespace fsm {

struct no_context {};

template <typename... Ts>
struct type_list {};

namespace detail {
template <typename T, typename List>
struct contains;
template <typename T>
struct contains<T, type_list<>> : std::false_type {};
template <typename T, typename... Rest>
struct contains<T, type_list<T, Rest...>> : std::true_type {};
template <typename T, typename Head, typename... Rest>
struct contains<T, type_list<Head, Rest...>> : contains<T, type_list<Rest...>> {};

template <typename InList, typename OutList = type_list<>>
struct unique;
template <typename OutList>
struct unique<type_list<>, OutList> {
    using type = OutList;
};
template <typename Head, typename... Tail, typename... Out>
struct unique<type_list<Head, Tail...>, type_list<Out...>> {
    using type = std::conditional_t<contains<Head, type_list<Out...>>::value,
                                    typename unique<type_list<Tail...>, type_list<Out...>>::type,
                                    typename unique<type_list<Tail...>, type_list<Out..., Head>>::type>;
};
template <typename List>
using unique_t = typename unique<List>::type;

template <typename List>
struct to_variant;
template <typename... Ts>
struct to_variant<type_list<Ts...>> {
    using type = std::variant<Ts...>;
};
template <typename List>
using to_variant_t = typename to_variant<List>::type;
}  // namespace detail

template <typename G, typename E, typename S, typename C>
concept Guard = requires(const G& g, const E& e, const S& s, const C& c) {
    { g(e, s, c) } -> std::convertible_to<bool>;
} || requires(const G& g, const E& e, const S& s) {
    { g(e, s) } -> std::convertible_to<bool>;
} || requires(const G& g, const E& e) {
    { g(e) } -> std::convertible_to<bool>;
} || requires(const G& g) {
    { g() } -> std::convertible_to<bool>;
};

template <typename A, typename E, typename S, typename D, typename C>
concept Action = requires(const A& a, const E& e, S& s, D& d, C& c) { a(e, s, d, c); } ||
                 requires(const A& a, const E& e, S& s, D& d) { a(e, s, d); } ||
                 requires(const A& a, const E& e, D& d) { a(e, d); } || requires(const A& a, const E& e) { a(e); } ||
                 requires(const A& a) { a(); };

struct no_guard {
    [[nodiscard]] constexpr bool operator()(const auto&...) const noexcept { return true; }
};

struct no_action {
    constexpr void operator()(auto&...) const noexcept {}
};

template <typename Src, typename Evt, typename Dst, typename GuardType = no_guard, typename ActionType = no_action>
struct row {
    using source_state = Src;
    using event_type = Evt;
    using target_state = Dst;
    using guard_type = GuardType;
    using action_type = ActionType;

    template <typename G>
    using when = row<Src, Evt, Dst, G, ActionType>;
    template <typename A>
    using then = row<Src, Evt, Dst, GuardType, A>;
};

template <typename... Rows>
struct transition_table {
    using rows = std::tuple<Rows...>;
    using raw_states = type_list<typename Rows::source_state..., typename Rows::target_state...>;
    using unique_states = detail::unique_t<raw_states>;
    using state_variant = detail::to_variant_t<unique_states>;
};

template <typename State>
constexpr std::string_view get_state_name(const State&) noexcept {
    if constexpr (requires { State::name; }) {
        return State::name;
    } else {
        return "State";
    }
}

template <typename Guard, typename Event, typename State, typename Context>
constexpr bool invoke_guard(const Guard& g, const Event& evt, const State& s, Context* ctx) {
    if constexpr (requires {
                      { g(evt, s, *ctx) } -> std::convertible_to<bool>;
                  }) {
        return ctx ? g(evt, s, *ctx) : true;
    } else if constexpr (requires {
                             { g(evt, s) } -> std::convertible_to<bool>;
                         }) {
        return g(evt, s);
    } else if constexpr (requires {
                             { g(evt) } -> std::convertible_to<bool>;
                         }) {
        return g(evt);
    } else if constexpr (requires {
                             { g() } -> std::convertible_to<bool>;
                         }) {
        return g();
    } else {
        return true;
    }
}

template <typename Action, typename Event, typename SrcState, typename DstState, typename Context>
constexpr void invoke_action(const Action& a, const Event& evt, SrcState& src, DstState& dst, Context* ctx) {
    if constexpr (requires { a(evt, src, dst, *ctx); }) {
        if (ctx)
            a(evt, src, dst, *ctx);
    } else if constexpr (requires { a(evt, src, dst); }) {
        a(evt, src, dst);
    } else if constexpr (requires { a(evt, dst); }) {
        a(evt, dst);
    } else if constexpr (requires { a(evt); }) {
        a(evt);
    } else if constexpr (requires { a(); }) {
        a();
    }
}

template <typename State, typename Context>
constexpr void invoke_enter_hook(State& s, Context* ctx) {
    if constexpr (requires(State& st, Context& c) { st.on_enter(c); }) {
        if (ctx)
            s.on_enter(*ctx);
    } else if constexpr (requires(State& st) { st.on_enter(); }) {
        s.on_enter();
    }
}

template <typename State, typename Context>
constexpr void invoke_exit_hook(State& s, Context* ctx) {
    if constexpr (requires(State& st, Context& c) { st.on_exit(c); }) {
        if (ctx)
            s.on_exit(*ctx);
    } else if constexpr (requires(State& st) { st.on_exit(); }) {
        s.on_exit();
    }
}

template <typename Table, typename Context = no_context,
          typename InitialState = typename std::tuple_element_t<0, typename Table::rows>::source_state>
class fsm {
  public:
    using table_type = Table;
    using context_type = Context;
    using state_variant = typename Table::state_variant;

    constexpr fsm() : current_state_(InitialState{}), context_(nullptr) { enter_initial(); }
    constexpr explicit fsm(Context& ctx) : current_state_(InitialState{}), context_(&ctx) { enter_initial(); }
    constexpr explicit fsm(Context& ctx, InitialState init) : current_state_(std::move(init)), context_(&ctx) {
        enter_initial();
    }

    template <typename Event>
    bool dispatch(const Event& event) {
        return std::visit(
            [this, &event](auto& src) -> bool { return process_event<Event, std::decay_t<decltype(src)>>(event, src); },
            current_state_);
    }

    template <typename State>
    [[nodiscard]] constexpr bool is_in_state() const noexcept {
        return std::holds_alternative<State>(current_state_);
    }

    [[nodiscard]] std::string_view current_state_name() const noexcept {
        return std::visit([](const auto& s) { return ::fsm::get_state_name(s); }, current_state_);
    }

    [[nodiscard]] const state_variant& get_current_state_variant() const noexcept { return current_state_; }
    [[nodiscard]] Context* get_context() noexcept { return context_; }

  private:
    constexpr void enter_initial() {
        std::visit([this](auto& s) { ::fsm::invoke_enter_hook(s, context_); }, current_state_);
    }

    template <typename Event, typename SrcState>
    bool process_event(const Event& evt, SrcState& src) {
        bool handled = false;
        std::apply(
            [&](auto... row_inst) { ((!handled && (handled = try_transition<decltype(row_inst)>(evt, src))), ...); },
            typename Table::rows{});
        return handled;
    }

    template <typename Row, typename Event, typename SrcState>
    bool try_transition(const Event& evt, SrcState& src) {
        if constexpr (std::is_same_v<SrcState, typename Row::source_state> &&
                      std::is_same_v<Event, typename Row::event_type>) {
            if (::fsm::invoke_guard(typename Row::guard_type{}, evt, src, context_)) {
                ::fsm::invoke_exit_hook(src, context_);
                typename Row::target_state dst_state{};
                ::fsm::invoke_action(typename Row::action_type{}, evt, src, dst_state, context_);
                ::fsm::invoke_enter_hook(dst_state, context_);
                current_state_.template emplace<typename Row::target_state>(std::move(dst_state));
                return true;
            }
        }
        return false;
    }

    state_variant current_state_;
    Context* context_{nullptr};
};

template <typename Table, typename Context = no_context,
          typename InitialState = typename std::tuple_element_t<0, typename Table::rows>::source_state>
class thread_safe_fsm {
  public:
    using fsm_type = fsm<Table, Context, InitialState>;
    using event_handler = std::function<void(fsm_type&)>;

    thread_safe_fsm() : fsm_() {}
    explicit thread_safe_fsm(Context& ctx) : fsm_(ctx) {}
    ~thread_safe_fsm() { stop_worker(); }

    template <typename Event>
    void post(Event&& event) {
        {
            std::lock_guard<std::mutex> lock(mutex_);
            queue_.push([evt = std::forward<Event>(event)](fsm_type& m) { m.dispatch(evt); });
        }
        cv_.notify_one();
    }

    void start_worker() {
        if (worker_.joinable())
            return;
        running_ = true;
        worker_ = std::jthread([this](std::stop_token st) {
            while (!st.stop_requested()) {
                event_handler task;
                {
                    std::unique_lock<std::mutex> lock(mutex_);
                    cv_.wait(lock, [&] { return !queue_.empty() || !running_.load(); });
                    if (!running_.load() && queue_.empty())
                        break;
                    if (!queue_.empty()) {
                        task = std::move(queue_.front());
                        queue_.pop();
                    }
                }
                if (task) {
                    std::lock_guard<std::mutex> lock(mutex_);
                    task(fsm_);
                }
            }
        });
    }

    void stop_worker() {
        running_ = false;
        cv_.notify_all();
        if (worker_.joinable()) {
            worker_.request_stop();
            worker_.join();
        }
    }

    template <typename State>
    [[nodiscard]] bool is_in_state() const {
        std::lock_guard<std::mutex> lock(mutex_);
        return fsm_.template is_in_state<State>();
    }

    [[nodiscard]] std::string_view current_state_name() const {
        std::lock_guard<std::mutex> lock(mutex_);
        return fsm_.current_state_name();
    }

    [[nodiscard]] bool is_queue_empty() const {
        std::lock_guard<std::mutex> lock(mutex_);
        return queue_.empty();
    }

  private:
    fsm_type fsm_;
    mutable std::mutex mutex_;
    std::condition_variable cv_;
    std::queue<event_handler> queue_;
    std::atomic<bool> running_{false};
    std::jthread worker_;
};

}  // namespace fsm

namespace net20 {

// ============================================================================
// States
// ============================================================================

struct Disconnected {
    static constexpr std::string_view name = "Disconnected";
    // Description: Disconnected State
};

struct Connecting {
    static constexpr std::string_view name = "Connecting";
    // Description: Connecting to Server
};

struct Connected {
    static constexpr std::string_view name = "Connected";
    // Description: Connected and Ready
};

struct Suspended {
    static constexpr std::string_view name = "Suspended";
    // Description: Connection Suspended
};

// ============================================================================
// Events
// ============================================================================

struct ConnectCmd {};

struct HandshakeOkEvent {};

struct HandshakeFailedEvent {};

struct TimeoutEvent {};

struct NetworkDegradedEvent {};

struct DisconnectCmd {};

struct ConnectionLostEvent {};

struct NetworkRestoredEvent {};

// ============================================================================
// Guards
// ============================================================================

struct HasNetworkGuard {
    [[nodiscard]] constexpr bool operator()(const auto& /*evt*/, const auto& /*state*/,
                                            const auto& /*ctx*/) const noexcept {
        // TODO: Implement guard logic for HasNetworkGuard
        return true;
    }
};

struct NoNetworkGuard {
    [[nodiscard]] constexpr bool operator()(const auto& /*evt*/, const auto& /*state*/,
                                            const auto& /*ctx*/) const noexcept {
        // TODO: Implement guard logic for NoNetworkGuard
        return true;
    }
};

// ============================================================================
// Actions
// ============================================================================

struct InitSocketAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for InitSocketAction
    }
};

struct LogErrorAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for LogErrorAction
    }
};

struct SetupSessionAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for SetupSessionAction
    }
};

struct CleanupAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for CleanupAction
    }
};

struct PauseQueueAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for PauseQueueAction
    }
};

struct CloseSocketAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for CloseSocketAction
    }
};

struct ResumeQueueAction {
    constexpr void operator()(const auto& /*evt*/, auto& /*src*/, auto& /*dst*/, auto& /*ctx*/) const {
        // TODO: Implement action logic for ResumeQueueAction
    }
};

// ============================================================================
// Transition Table (Compile-Time Fluent DSL)
// ============================================================================

using ConnectionFSM20Table =
    fsm::transition_table<fsm::row<Disconnected, ConnectCmd, Connecting>::when<HasNetworkGuard>::then<InitSocketAction>,
                          fsm::row<Disconnected, ConnectCmd, Disconnected>::when<NoNetworkGuard>::then<LogErrorAction>,
                          fsm::row<Connecting, HandshakeOkEvent, Connected>::then<SetupSessionAction>,
                          fsm::row<Connecting, HandshakeFailedEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Connecting, TimeoutEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Connected, NetworkDegradedEvent, Suspended>::then<PauseQueueAction>,
                          fsm::row<Connected, DisconnectCmd, Disconnected>::then<CloseSocketAction>,
                          fsm::row<Connected, ConnectionLostEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Suspended, NetworkRestoredEvent, Connected>::then<ResumeQueueAction>,
                          fsm::row<Suspended, DisconnectCmd, Disconnected>::then<CloseSocketAction>,
                          fsm::row<Suspended, TimeoutEvent, Disconnected>::then<CleanupAction>>;

// ============================================================================
// State Machine Type Aliases
// ============================================================================

using ConnectionFSM20 = fsm::fsm<ConnectionFSM20Table, fsm::no_context, Disconnected>;
using ThreadSafeConnectionFSM20 = fsm::thread_safe_fsm<ConnectionFSM20Table, fsm::no_context, Disconnected>;

}  // namespace net20
