// ============================================================================
// Auto-generated by fsm-gen (C++17 State Machine Compiler)
// Target: Compile-time Zero-Overhead FSM (C++17)
// ============================================================================

#pragma once

#include <iostream>
#include <string_view>

#include "fsm/fsm.hpp"
#include "fsm/thread_safe_fsm.hpp"

namespace net {

// Forward declaration of Context (or include your context header)
struct NetworkContext;

// ============================================================================
// States
// ============================================================================

struct Disconnected {
    static constexpr std::string_view name = "Disconnected";
    // Description: Disconnected State
};

struct Connecting {
    static constexpr std::string_view name = "Connecting";
    // Description: Connecting to Server
};

struct Connected {
    static constexpr std::string_view name = "Connected";
    // Description: Connected and Ready
};

struct Suspended {
    static constexpr std::string_view name = "Suspended";
    // Description: Connection Suspended
};

// ============================================================================
// Events
// ============================================================================

struct ConnectCmd {};

struct HandshakeOkEvent {};

struct HandshakeFailedEvent {};

struct TimeoutEvent {};

struct NetworkDegradedEvent {};

struct DisconnectCmd {};

struct ConnectionLostEvent {};

struct NetworkRestoredEvent {};

// ============================================================================
// Guards
// ============================================================================

struct HasNetworkGuard {
    template <typename Event, typename State, typename Context>
    bool operator()(const Event& /*evt*/, const State& /*state*/, const Context& /*ctx*/) const {
        // TODO: Implement guard logic for HasNetworkGuard
        return true;
    }
};

struct NoNetworkGuard {
    template <typename Event, typename State, typename Context>
    bool operator()(const Event& /*evt*/, const State& /*state*/, const Context& /*ctx*/) const {
        // TODO: Implement guard logic for NoNetworkGuard
        return true;
    }
};

// ============================================================================
// Actions
// ============================================================================

struct InitSocketAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for InitSocketAction
    }
};

struct LogErrorAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for LogErrorAction
    }
};

struct SetupSessionAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for SetupSessionAction
    }
};

struct CleanupAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for CleanupAction
    }
};

struct PauseQueueAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for PauseQueueAction
    }
};

struct CloseSocketAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for CloseSocketAction
    }
};

struct ResumeQueueAction {
    template <typename Event, typename SrcState, typename DstState, typename Context>
    void operator()(const Event& /*evt*/, SrcState& /*src*/, DstState& /*dst*/, Context& /*ctx*/) const {
        // TODO: Implement action logic for ResumeQueueAction
    }
};

// ============================================================================
// Transition Table (Compile-Time Fluent DSL)
// ============================================================================

using ConnectionFSMTable =
    fsm::transition_table<fsm::row<Disconnected, ConnectCmd, Connecting>::when<HasNetworkGuard>::then<InitSocketAction>,
                          fsm::row<Disconnected, ConnectCmd, Disconnected>::when<NoNetworkGuard>::then<LogErrorAction>,
                          fsm::row<Connecting, HandshakeOkEvent, Connected>::then<SetupSessionAction>,
                          fsm::row<Connecting, HandshakeFailedEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Connecting, TimeoutEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Connected, NetworkDegradedEvent, Suspended>::then<PauseQueueAction>,
                          fsm::row<Connected, DisconnectCmd, Disconnected>::then<CloseSocketAction>,
                          fsm::row<Connected, ConnectionLostEvent, Disconnected>::then<CleanupAction>,
                          fsm::row<Suspended, NetworkRestoredEvent, Connected>::then<ResumeQueueAction>,
                          fsm::row<Suspended, DisconnectCmd, Disconnected>::then<CloseSocketAction>,
                          fsm::row<Suspended, TimeoutEvent, Disconnected>::then<CleanupAction>>;

// ============================================================================
// State Machine Type Aliases
// ============================================================================

using ConnectionFSM = fsm::fsm<ConnectionFSMTable, NetworkContext, Disconnected>;
using ThreadSafeConnectionFSM = fsm::thread_safe_fsm<ConnectionFSMTable, NetworkContext, Disconnected>;

}  // namespace net
