#!/usr/bin/env python3
"""
generate_standalone_runtime.py - Standalone Runtime Bundler for fsmc

This script automatically generates standalone single-header runtimes
(cpp17_standalone_runtime.hpp and cpp20_standalone_runtime.hpp) directly
from the canonical modular runtime headers in include/fsm/backend/cpp/runtime/.

Usage:
    python3 scripts/generate_standalone_runtime.py [--check] [--root <path>]
"""

import argparse
import os
import re
import sys

CORE_FILES = [
    "traits/type_list.hpp",
    "traits/dispatch_result.hpp",
    "traits/step_result.hpp",
    "traits/reflection.hpp",
    "traits/hook_traits.hpp",
    "traits/observer_traits.hpp",
    "traits/concepts.hpp",
    "type_traits.hpp",
    "static_vector.hpp",
    "transition.hpp",
    "transition_table.hpp",
    "detail/history_manager.hpp",
    "detail/deferred_manager.hpp",
    "detail/transition_executor.hpp",
    "fsm.hpp",
]

THREAD_FILES = [
    "spsc_ring_buffer.hpp",
    "static_ring_buffer.hpp",
    "async_types.hpp",
    "async_event_queue.hpp",
    "detail/reentrancy_tracker.hpp",
    "detail/notification_dispatcher.hpp",
    "thread_safe_fsm.hpp",
    "spsc_fsm.hpp",
]


def clean_file_content(filepath):
    """Reads a runtime header, strips #pragma once, local #includes, and returns system includes + body."""
    system_includes = []
    body_lines = []
    
    with open(filepath, "r", encoding="utf-8") as f:
        for line in f:
            stripped = line.strip()
            if stripped == "#pragma once":
                continue
            
            # Match system include
            m_sys = re.match(r"^#include\s*<([^>]+)>", stripped)
            if m_sys:
                inc = m_sys.group(1)
                if inc not in system_includes:
                    system_includes.append(inc)
                continue
            
            # Match local fsm include (skip it)
            if re.match(r'^#include\s*["<]fsm/', stripped):
                continue
            
            body_lines.append(line)
            
    # Strip leading/trailing empty lines from body
    while body_lines and not body_lines[0].strip():
        body_lines.pop(0)
    while body_lines and not body_lines[-1].strip():
        body_lines.pop()
        
    return system_includes, "".join(body_lines)

def bundle_files(base_dir, file_list):
    """Bundles multiple runtime files into unified system includes and unified body."""
    all_sys_includes = []
    bodies = []
    
    for rel_path in file_list:
        full_path = os.path.join(base_dir, rel_path)
        if not os.path.exists(full_path):
            raise FileNotFoundError(f"Runtime header not found: {full_path}")
        
        sys_incs, body = clean_file_content(full_path)
        for inc in sys_incs:
            if inc not in all_sys_includes:
                all_sys_includes.append(inc)
        
        bodies.append(f"// --- Begin: {rel_path} ---\n" + body + f"\n// --- End: {rel_path} ---\n")
        
    return all_sys_includes, "\n".join(bodies)

def generate_emitter_header(class_name, standard_name, core_incs, core_body, thread_incs, thread_body):
    """Generates the C++ emitter header file containing the raw string literals."""
    
    # Format system includes
    core_inc_str = "\n".join(f'#include <{inc}>' for inc in sorted(core_incs))
    thread_inc_str = "\n".join(f'#include <{inc}>' for inc in sorted(thread_incs) if inc not in core_incs)
    
    return f"""#pragma once

// ============================================================================
// Auto-generated by scripts/generate_standalone_runtime.py
// DO NOT EDIT DIRECTLY. Edit files in include/fsm/backend/cpp/runtime/ instead.
// Target: {standard_name} Standalone Runtime Emitter
// ============================================================================

#include <ostream>

#include "fsm/backend/cpp/cpp_options.hpp"

namespace fsm::codegen {{

class {class_name} {{
  public:
    static void emit(std::ostream& out, const GeneratorOptions& opts) {{
        out << R"raw_fsm_runtime(
// Core System Includes
{core_inc_str}
)raw_fsm_runtime";

        if (opts.thread_safe) {{
            out << R"raw_fsm_runtime(
// Thread-Safe System Includes
{thread_inc_str}
)raw_fsm_runtime";
        }}

        out << R"raw_fsm_runtime(

// ============================================================================
// Core Runtime ({standard_name})
// ============================================================================
{core_body}
)raw_fsm_runtime";

        if (opts.thread_safe) {{
            out << R"raw_fsm_runtime(
// ============================================================================
// Thread-Safe & Asynchronous Runtime ({standard_name})
// ============================================================================
{thread_body}
)raw_fsm_runtime";
        }}
    }}
}};

}}  // namespace fsm::codegen
"""

def main():
    parser = argparse.ArgumentParser(description="Generate C++ Standalone Runtime Emitters")
    parser.add_argument("--check", action="store_true", help="Check if generated files are up to date without modifying")
    parser.add_argument("--root", default=".", help="Root directory of fsmc workspace")
    args = parser.parse_args()

    runtime_dir = os.path.join(args.root, "include/fsm/backend/cpp/runtime")
    backend_cpp_dir = os.path.join(args.root, "include/fsm/backend/cpp")

    if not os.path.exists(runtime_dir):
        print(f"Error: Runtime directory not found: {runtime_dir}", file=sys.stderr)
        return 1

    core_incs, core_body = bundle_files(runtime_dir, CORE_FILES)
    thread_incs, thread_body = bundle_files(runtime_dir, THREAD_FILES)

    # 1. C++20 Standalone Runtime
    cpp20_code = generate_emitter_header(
        "Cpp20StandaloneRuntime", "C++20",
        core_incs, core_body,
        thread_incs, thread_body
    )
    cpp20_path = os.path.join(backend_cpp_dir, "cpp20_standalone_runtime.hpp")

    # 2. C++17 Standalone Runtime
    # For C++17, remove C++20 specific headers like <concepts>
    cpp17_core_incs = [i for i in core_incs if i != "concepts"]
    cpp17_thread_incs = [i for i in thread_incs if i != "concepts" and i != "stop_token"]
    cpp17_code = generate_emitter_header(
        "Cpp17StandaloneRuntime", "C++17",
        cpp17_core_incs, core_body,
        cpp17_thread_incs, thread_body
    )
    cpp17_path = os.path.join(backend_cpp_dir, "cpp17_standalone_runtime.hpp")

    files_to_write = [
        (cpp17_path, cpp17_code),
        (cpp20_path, cpp20_code),
    ]

    is_out_of_date = False
    for path, content in files_to_write:
        if args.check:
            if not os.path.exists(path):
                print(f"[OUT OF DATE] Missing {path}", file=sys.stderr)
                is_out_of_date = True
            else:
                with open(path, "r", encoding="utf-8") as f:
                    existing = f.read()
                if existing != content:
                    print(f"[OUT OF DATE] Content differs in {path}", file=sys.stderr)
                    is_out_of_date = True
        else:
            with open(path, "w", encoding="utf-8") as f:
                f.write(content)
            print(f"[GENERATED] Successfully updated {path}")

    if args.check:
        if is_out_of_date:
            print("Error: Standalone runtime headers are out of sync with include/fsm/backend/cpp/runtime/.", file=sys.stderr)
            print("Run 'cmake --build build --target generate_standalone_runtime' to update.", file=sys.stderr)
            return 1
        print("Success: Standalone runtime headers are 100% in sync with include/fsm/backend/cpp/runtime/.")

    return 0

if __name__ == "__main__":
    sys.exit(main())
