#pragma once

#include <algorithm>
#include <cstdint>
#include <map>
#include <memory>
#include <sstream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

#include "fsm/frontend/directive/guard_parser.hpp"
#include "fsm/ir/fsm_ir.hpp"

namespace fsm::backend::verification {

/**
 * @brief Test Vector for a single MC/DC evaluation.
 */
struct McdcTestVector {
    std::map<std::string, bool> condition_values;
    bool decision_outcome{false};
    std::string condition_tested;  ///< Condition whose independent effect is proven by this vector pair
};

/**
 * @brief Pair of test vectors proving independent effect of a condition for MC/DC (high-integrity testing).
 */
struct McdcIndependencePair {
    std::string condition_name;
    McdcTestVector vector_true;   ///< Condition is TRUE
    McdcTestVector vector_false;  ///< Condition is FALSE, while other conditions remain fixed
};

/**
 * @brief Simple AST for evaluating boolean expressions.
 */
class BoolExpr {
  public:
    virtual ~BoolExpr() = default;
    [[nodiscard]] virtual bool evaluate(const std::map<std::string, bool>& env) const = 0;
    virtual void collect_variables(std::vector<std::string>& vars) const = 0;
};

class VarExpr : public BoolExpr {
  public:
    explicit VarExpr(std::string name) : name_(std::move(name)) {}
    [[nodiscard]] bool evaluate(const std::map<std::string, bool>& env) const override {
        auto it = env.find(name_);
        return (it != env.end()) ? it->second : false;
    }
    void collect_variables(std::vector<std::string>& vars) const override {
        if (std::find(vars.begin(), vars.end(), name_) == vars.end()) {
            vars.push_back(name_);
        }
    }
    [[nodiscard]] const std::string& name() const noexcept { return name_; }

  private:
    std::string name_;
};

class NotExpr : public BoolExpr {
  public:
    explicit NotExpr(std::unique_ptr<BoolExpr> sub) : sub_(std::move(sub)) {}
    [[nodiscard]] bool evaluate(const std::map<std::string, bool>& env) const override { return !sub_->evaluate(env); }
    void collect_variables(std::vector<std::string>& vars) const override { sub_->collect_variables(vars); }

  private:
    std::unique_ptr<BoolExpr> sub_;
};

class BinaryExpr : public BoolExpr {
  public:
    enum Op { And, Or };
    BinaryExpr(Op op, std::unique_ptr<BoolExpr> left, std::unique_ptr<BoolExpr> right)
        : op_(op), left_(std::move(left)), right_(std::move(right)) {}

    [[nodiscard]] bool evaluate(const std::map<std::string, bool>& env) const override {
        if (op_ == And) {
            return left_->evaluate(env) && right_->evaluate(env);
        }
        return left_->evaluate(env) || right_->evaluate(env);
    }

    void collect_variables(std::vector<std::string>& vars) const override {
        left_->collect_variables(vars);
        right_->collect_variables(vars);
    }

  private:
    Op op_;
    std::unique_ptr<BoolExpr> left_;
    std::unique_ptr<BoolExpr> right_;
};

/**
 * @brief Safety-Critical Test Harness & MC/DC Test Suite Synthesizer.
 *
 * Automatically generates Modified Condition / Decision Coverage (MC/DC) test suites
 * with independence pairs for composite transition guards in high-integrity software.
 */
class McdcHarnessGenerator {
  public:
    /**
     * @brief Synthesizes complete GoogleTest unit test file verifying MC/DC coverage.
     */
    static std::string generate_gtest_harness(const FsmIr& ir) {
        std::ostringstream out;
        out << "// ============================================================================\n";
        out << "// Automated MC/DC Safety Verification Test Harness\n";
        out << "// Target Model: " << ir.name << "\n";
        out << "// Generated by fsmc (Finite State Machine Compiler)\n";
        out << "// ============================================================================\n\n";

        out << "#include <gtest/gtest.h>\n";
        out << "#include <string_view>\n\n";

        std::size_t test_idx = 0;
        for (const auto& t : ir.transitions) {
            if (!t.guard.has_value() || t.guard->empty()) {
                continue;
            }

            std::string raw_guard = *t.guard;
            std::string diag_guard = GuardExpressionParser::to_diagram_string(raw_guard);
            auto parsed_guard = GuardExpressionParser::parse(raw_guard);

            if (parsed_guard.atomic_guards.size() < 2) {
                continue;
            }

            auto expr_ast = parse_simple_expr(diag_guard, parsed_guard.atomic_guards);
            if (!expr_ast) {
                continue;
            }

            std::vector<std::string> conditions = parsed_guard.atomic_guards;
            auto pairs = compute_mcdc_pairs(*expr_ast, conditions);
            if (pairs.empty()) {
                continue;
            }

            ++test_idx;
            std::string test_name =
                "McdcCoverage_Trans_" + std::to_string(test_idx) + "_" + t.source + "_to_" + t.target;
            out << "/**\n";
            out << " * @brief MC/DC Test Suite for Transition: " << t.source << " -> " << t.target << "\n";
            out << " * Guard: [" << diag_guard << "]\n";
            out << " * Conditions (" << conditions.size() << "): ";
            for (size_t i = 0; i < conditions.size(); ++i) {
                if (i > 0)
                    out << ", ";
                out << conditions[i];
            }
            out << "\n */\n";
            out << "TEST(McdcSafetyHarness, " << test_name << ") {\n";
            out << "    // Decision evaluation lambda\n";
            out << "    auto evaluate_decision = [](bool ";
            for (size_t i = 0; i < conditions.size(); ++i) {
                if (i > 0)
                    out << ", bool ";
                out << conditions[i];
            }
            out << ") -> bool {\n";
            out << "        return (" << diag_guard << ");\n";
            out << "    };\n\n";

            for (const auto& pair : pairs) {
                out << "    // Independence pair for condition: " << pair.condition_name << "\n";
                out << "    {\n";
                out << "        // Vector 1: " << pair.condition_name << " = true\n";
                out << "        bool d1 = evaluate_decision(";
                for (size_t i = 0; i < conditions.size(); ++i) {
                    if (i > 0)
                        out << ", ";
                    out << (pair.vector_true.condition_values.at(conditions[i]) ? "true" : "false");
                }
                out << ");\n";
                out << "        EXPECT_EQ(d1, " << (pair.vector_true.decision_outcome ? "true" : "false") << ");\n\n";

                out << "        // Vector 2: " << pair.condition_name << " = false (all other conditions held fixed)\n";
                out << "        bool d2 = evaluate_decision(";
                for (size_t i = 0; i < conditions.size(); ++i) {
                    if (i > 0)
                        out << ", ";
                    out << (pair.vector_false.condition_values.at(conditions[i]) ? "true" : "false");
                }
                out << ");\n";
                out << "        EXPECT_EQ(d2, " << (pair.vector_false.decision_outcome ? "true" : "false") << ");\n";
                out << "        EXPECT_NE(d1, d2) << \"Condition '" << pair.condition_name
                    << "' failed independent outcome toggle.\";\n";
                out << "    }\n\n";
            }
            out << "}\n\n";
        }

        if (test_idx == 0) {
            out << "TEST(McdcSafetyHarness, NoCompositeGuards) {\n";
            out << "    // Model contains no composite boolean guard expressions requiring MC/DC.\n";
            out << "    SUCCEED();\n";
            out << "}\n";
        }

        return out.str();
    }

    /**
     * @brief Computes the MC/DC independence pairs for a boolean AST and list of conditions.
     */
    static std::vector<McdcIndependencePair> compute_mcdc_pairs(const BoolExpr& expr,
                                                                const std::vector<std::string>& conditions) {
        std::vector<McdcIndependencePair> result;
        std::size_t n = conditions.size();
        std::size_t total_combinations = 1ULL << n;

        // Build truth table
        std::vector<McdcTestVector> truth_table;
        truth_table.reserve(total_combinations);

        for (std::size_t mask = 0; mask < total_combinations; ++mask) {
            std::map<std::string, bool> env;
            for (std::size_t i = 0; i < n; ++i) {
                env[conditions[i]] = ((mask >> i) & 1ULL) != 0;
            }
            bool outcome = expr.evaluate(env);
            McdcTestVector tv;
            tv.condition_values = std::move(env);
            tv.decision_outcome = outcome;
            truth_table.push_back(std::move(tv));
        }

        // For each condition, find an independence pair (T1, T2) differing only in that condition
        for (std::size_t i = 0; i < n; ++i) {
            const auto& target_cond = conditions[i];
            bool found_pair = false;

            for (std::size_t mask1 = 0; mask1 < total_combinations; ++mask1) {
                if (((mask1 >> i) & 1ULL) == 0) {
                    continue;  // mask1 must have condition == true
                }
                std::size_t mask2 = mask1 ^ (1ULL << i);  // mask2 has condition == false, all others identical

                const auto& tv_true = truth_table[mask1];
                const auto& tv_false = truth_table[mask2];

                if (tv_true.decision_outcome != tv_false.decision_outcome) {
                    McdcIndependencePair pair;
                    pair.condition_name = target_cond;
                    pair.vector_true = tv_true;
                    pair.vector_true.condition_tested = target_cond;
                    pair.vector_false = tv_false;
                    pair.vector_false.condition_tested = target_cond;
                    result.push_back(std::move(pair));
                    found_pair = true;
                    break;
                }
            }

            if (!found_pair) {
                // Condition might be masked / non-essential in this formula
            }
        }

        return result;
    }

  private:
    static std::unique_ptr<BoolExpr> parse_simple_expr(const std::string& expr_str,
                                                       const std::vector<std::string>& atomic_conditions) {
        // Simple recursive parser or tokenizer
        // If atomic condition matches directly
        for (const auto& cond : atomic_conditions) {
            if (expr_str == cond) {
                return std::make_unique<VarExpr>(cond);
            }
        }

        // Check for top-level OR ('||')
        int paren_depth = 0;
        for (int i = static_cast<int>(expr_str.size()) - 1; i >= 1; --i) {
            if (expr_str[static_cast<size_t>(i)] == ')')
                paren_depth++;
            else if (expr_str[static_cast<size_t>(i)] == '(')
                paren_depth--;
            else if (paren_depth == 0 && expr_str[static_cast<size_t>(i)] == '|' &&
                     expr_str[static_cast<size_t>(i - 1)] == '|') {
                auto left = parse_simple_expr(trim(expr_str.substr(0, static_cast<size_t>(i - 1))), atomic_conditions);
                auto right = parse_simple_expr(trim(expr_str.substr(static_cast<size_t>(i + 1))), atomic_conditions);
                if (left && right) {
                    return std::make_unique<BinaryExpr>(BinaryExpr::Or, std::move(left), std::move(right));
                }
            }
        }

        // Check for top-level AND ('&&')
        paren_depth = 0;
        for (int i = static_cast<int>(expr_str.size()) - 1; i >= 1; --i) {
            if (expr_str[static_cast<size_t>(i)] == ')')
                paren_depth++;
            else if (expr_str[static_cast<size_t>(i)] == '(')
                paren_depth--;
            else if (paren_depth == 0 && expr_str[static_cast<size_t>(i)] == '&' &&
                     expr_str[static_cast<size_t>(i - 1)] == '&') {
                auto left = parse_simple_expr(trim(expr_str.substr(0, static_cast<size_t>(i - 1))), atomic_conditions);
                auto right = parse_simple_expr(trim(expr_str.substr(static_cast<size_t>(i + 1))), atomic_conditions);
                if (left && right) {
                    return std::make_unique<BinaryExpr>(BinaryExpr::And, std::move(left), std::move(right));
                }
            }
        }

        // Check for NOT ('!')
        if (!expr_str.empty() && expr_str.front() == '!') {
            auto sub = parse_simple_expr(trim(expr_str.substr(1)), atomic_conditions);
            if (sub) {
                return std::make_unique<NotExpr>(std::move(sub));
            }
        }

        // Check for enclosing parentheses
        if (expr_str.size() >= 2 && expr_str.front() == '(' && expr_str.back() == ')') {
            return parse_simple_expr(trim(expr_str.substr(1, expr_str.size() - 2)), atomic_conditions);
        }

        return std::make_unique<VarExpr>(expr_str);
    }

    static std::string trim(std::string_view s) {
        while (!s.empty() && (s.front() == ' ' || s.front() == '\t'))
            s.remove_prefix(1);
        while (!s.empty() && (s.back() == ' ' || s.back() == '\t'))
            s.remove_suffix(1);
        return std::string(s);
    }
};

}  // namespace fsm::backend::verification

namespace fsm::backend {
using verification::McdcTestVector;
using verification::McdcIndependencePair;
using verification::McdcHarnessGenerator;
}  // namespace fsm::backend
