const PRESETS = {
  connection: `stateDiagram-v2
    [*] --> Disconnected
    Disconnected --> Connecting : ConnectCmd
    Connecting --> Connected : HandshakeOkEvent / StartHeartbeat
    Connecting --> Disconnected : TimeoutEvent / LogFailure
    Connected : Ping / ResetWatchdog
    Connected --> Disconnected : DisconnectCmd / CleanupSession`,

  motor: `stateDiagram-v2
    [*] --> Idle
    Idle --> Accelerating : StartCmd
    Accelerating --> Running : TargetSpeedReached
    Running --> Decelerating : SlowDownCmd
    Decelerating --> Idle : SpeedZero
    Running --> Fault : OverheatEvent
    Fault --> Idle : ResetCmd`,

  mission: `stateDiagram-v2
    [*] --> Standby
    Standby --> Booting : PowerOn
    Booting --> Ready : BootComplete
    Ready --> InFlight : LaunchCmd [ClearanceOk]
    InFlight --> Orbit : InsertionOk
    Orbit --> Deorbiting : DeorbitCmd
    Deorbiting --> Landed : Touchdown
    Landed --> [*]`,

  timed_watchdog: `stateDiagram-v2
    [*] --> Healthy
    Healthy --> Healthy : HeartbeatPing / ResetTimer
    Healthy --> Degraded : after_500ms / RaiseWarning
    Degraded --> Healthy : HeartbeatPing
    Degraded --> Deadlock : after_1000ms / ForceRestart
    Deadlock --> [*]`,

  livelock_demo: `stateDiagram-v2
    [*] --> InitState
    InitState --> StateA
    StateA --> StateB
    StateB --> StateA`
};

let currentModel = {
  states: [],
  events: [],
  transitions: [],
  initialState: "Disconnected",
  activeState: "Disconnected",
  history: []
};

// Simple In-Browser Deterministic Parser & C++ Generator (Standalone JavaScript fallback)
function parseMermaid(text) {
  const lines = text.split('\n');
  const states = new Set();
  const events = new Set();
  const transitions = [];
  let initialState = "";

  for (let line of lines) {
    line = line.trim();
    if (!line || line.startsWith('stateDiagram') || line.startsWith('%%')) continue;

    // [*] --> InitState
    if (line.includes('-->')) {
      const parts = line.split('-->');
      const src = parts[0].trim();
      const rest = parts[1].trim();

      let dst = rest;
      let label = "";
      if (rest.includes(':')) {
        const sub = rest.split(':');
        dst = sub[0].trim();
        label = sub.slice(1).join(':').trim();
      }

      if (src === '[*]') {
        initialState = dst;
        states.add(dst);
        continue;
      }

      states.add(src);
      if (dst !== '[*]') states.add(dst);

      let evt = "Anonymous";
      let guard = "";
      let action = "";

      if (label) {
        let work = label;
        if (work.includes('/')) {
          const slash = work.split('/');
          action = slash[1].trim();
          work = slash[0].trim();
        }
        if (work.includes('[')) {
          const openB = work.indexOf('[');
          const closeB = work.indexOf(']');
          guard = work.substring(openB + 1, closeB).trim();
          work = (work.substring(0, openB) + work.substring(closeB + 1)).trim();
        }
        evt = work.trim() || "Anonymous";
      }

      if (evt !== "Anonymous") events.add(evt);
      transitions.push({ source: src, target: dst, event: evt, guard: guard, action: action });
    }
  }

  if (!initialState && states.size > 0) {
    initialState = Array.from(states)[0];
  }

  return {
    states: Array.from(states),
    events: Array.from(events),
    transitions: transitions,
    initialState: initialState
  };
}

function generateCppHeader(model, isCpp20 = true) {
  const stateStructs = model.states.map(s => `struct ${s} { static constexpr std::string_view name = "${s}"; };`).join('\n');
  const eventStructs = model.events.map(e => `struct ${e} {};`).join('\n');

  const rows = model.transitions.map(t => {
    const grd = t.guard ? t.guard : "fsm::no_guard";
    const act = t.action ? t.action : "fsm::no_action";
    return `    fsm::row<${t.source}, ${t.event}, ${t.target}, ${grd}, ${act}>`;
  }).join(',\n');

  return `// ============================================================================
// Generated by fsmc (Universal C++ FSM Compiler)
// Target Standard: ${isCpp20 ? 'C++20 (Concepts & Type-Safe Metaprogramming)' : 'C++17 (Zero-Overhead Transition Tables)'}
// ============================================================================
#pragma once

#include <string_view>
#include "fsm/fsm.hpp"

namespace fsm_generated {

// 1. State Definitions
${stateStructs}

// 2. Event Definitions
${eventStructs}

// 3. Transition Table Definition
using TransitionTable = fsm::transition_table<
${rows}
>;

// 4. State Machine Type Definition
using StateMachine = fsm::fsm<TransitionTable, fsm::no_context, ${model.initialState}>;

} // namespace fsm_generated
`;
}

function runModelChecker(model) {
  const diagnostics = [];

  // Livelock check
  const eventless = model.transitions.filter(t => t.event === "Anonymous");
  if (eventless.length > 1) {
    diagnostics.push({ severity: "SAFETY_CRITICAL", category: "Livelock", message: "Eventless transitions present (potential instantaneous cascade or livelock)." });
  }

  // Reachability check
  const reachable = new Set([model.initialState]);
  let changed = true;
  while (changed) {
    changed = false;
    for (const t of model.transitions) {
      if (reachable.has(t.source) && !reachable.has(t.target)) {
        reachable.add(t.target);
        changed = true;
      }
    }
  }

  for (const s of model.states) {
    if (!reachable.has(s)) {
      diagnostics.push({ severity: "WARNING", category: "Reachability", message: `State unreachable from initial state: '${s}'` });
    }
  }

  return diagnostics;
}

// UI Controllers
function updatePlayground() {
  const code = document.getElementById("editor").value;
  const isCpp20 = document.getElementById("stdSelect").value === "20";
  
  const parsed = parseMermaid(code);
  currentModel = {
    ...parsed,
    activeState: parsed.initialState,
    history: []
  };

  // Render C++ Code
  document.getElementById("cppPreview").textContent = generateCppHeader(currentModel, isCpp20);

  // Run Diagnostics
  const diags = runModelChecker(currentModel);
  const diagContainer = document.getElementById("diagnostics");
  diagContainer.innerHTML = "";
  if (diags.length === 0) {
    diagContainer.innerHTML = `<div class="diag-item INFO">✨ Model is formally verified and sound (0 errors, 0 warnings).</div>`;
  } else {
    for (const d of diags) {
      diagContainer.innerHTML += `<div class="diag-item ${d.severity}"><strong>[${d.category}]</strong> ${d.message}</div>`;
    }
  }

  // Render Mermaid Diagram
  renderMermaid(code);

  // Update Simulator
  updateSimulatorUI();
}

function renderMermaid(code) {
  const canvas = document.getElementById("mermaidCanvas");
  canvas.innerHTML = `<div class="mermaid">${code}</div>`;
  if (window.mermaid) {
    mermaid.contentLoaded();
  }
}

function updateSimulatorUI() {
  document.getElementById("activeStateBadge").textContent = currentModel.activeState;

  // Populate clickable event buttons
  const btnContainer = document.getElementById("eventButtons");
  btnContainer.innerHTML = "";

  for (const evt of currentModel.events) {
    const btn = document.createElement("button");
    btn.className = "btn-event";
    btn.textContent = evt;
    btn.onclick = () => dispatchEvent(evt);
    btnContainer.appendChild(btn);
  }
}

function dispatchEvent(eventName) {
  const matching = currentModel.transitions.find(t => t.source === currentModel.activeState && t.event === eventName);
  const historyLog = document.getElementById("historyLog");
  const time = new Date().toLocaleTimeString();

  if (matching) {
    const oldState = currentModel.activeState;
    currentModel.activeState = matching.target;
    document.getElementById("activeStateBadge").textContent = currentModel.activeState;

    const logEntry = document.createElement("div");
    logEntry.className = "log-entry";
    logEntry.innerHTML = `[${time}] <span class="event">${eventName}</span> : ${oldState} -> <span class="success">${matching.target}</span>`;
    historyLog.prepend(logEntry);
  } else {
    const logEntry = document.createElement("div");
    logEntry.className = "log-entry";
    logEntry.innerHTML = `[${time}] <span class="event">${eventName}</span> : Dropped (No transition from '${currentModel.activeState}')`;
    historyLog.prepend(logEntry);
  }
}

window.onload = () => {
  if (window.mermaid) {
    mermaid.initialize({
      startOnLoad: false,
      theme: 'dark',
      themeVariables: {
        darkMode: true,
        background: '#07090e',
        primaryColor: '#00f0ff',
        primaryBorderColor: '#00f0ff',
        lineColor: '#8b5cf6',
        secondaryColor: '#1e293b'
      }
    });
  }

  document.getElementById("editor").value = PRESETS.connection;
  document.getElementById("presetSelect").onchange = (e) => {
    document.getElementById("editor").value = PRESETS[e.target.value] || PRESETS.connection;
    updatePlayground();
  };
  document.getElementById("stdSelect").onchange = updatePlayground;
  document.getElementById("editor").oninput = updatePlayground;

  document.getElementById("copyBtn").onclick = () => {
    const code = document.getElementById("cppPreview").textContent;
    navigator.clipboard.writeText(code);
    alert("C++ header copied to clipboard!");
  };

  updatePlayground();
};
